pointfreeco/swift-composable-architecture

.github/workflows/ci.yml
Just a quick PR before I turn in.
I thought it would be nice to have all the examples tested in a separate CI job so that it's easy to see at a glance where the failure happened.
What do you think?
=> Test examples in a separate CI job.

README.md, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
=> Add step-by-step installation instructions

Examples/TicTacToe/Tests/GameSwiftUITests.swift, Sources/ComposableArchitectureTestSupport/TestStore.swift
- Fixed the documentation formatting
- Added an overload that only takes a state transformation
=> TestStore.scope tweaks

.github/workflows/ci.yml, Makefile
Makes local development a bit friendlier, too.
=> Update CI to use Xcode 11.4.1

Examples/TicTacToe/Sources/Core/GameCore.swift, Examples/TicTacToe/Sources/Views-UIKit/NewGameViewController.swift
This is totally unrelated to architectural concerns, just a minor cleanup. The project looks great!
=> Tic-tac-toe minor updates: win condition and fix to placeholder copy

.github/workflows/format.yml
From https://github.community/t5/GitHub-Actions/Run-action-only-when-a-PR-is-merged/m-p/56155/highlight/true#M9769
=> Only run swift-format when PRs are merged

README.md
Nice to show what the demos look like without requiring folks to pull the code down.
=> Add example apps image to README

README.md
=> Update examples image URL

.github/ISSUE_TEMPLATE/bug_report.md
Just a few small improvements.
=> A few issue template improvements

Makefile
For cleaner CI logs and easier debugging of failing builds/tests  #56
=> Adds -quiet flag to xcodebuild

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
=> Helpers for making stores stateless/actionless

Sources/ComposableArchitecture/Store.swift
Forgot to do this in the earlier PR.
=> Document Store.{state,action}less

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift
=> Add binding example to animation demo

.github/ISSUE_TEMPLATE/question.md, README.md, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
We've got a brand new [forum](https://forums.swift.org/c/related-projects/swift-composable-architecture), so let's make sure folks know!
=> Swift Forum

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift, Makefile, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
This makes it a lil more discoverable and friendlier for Xcode 11.3.
=> Add "run" function to Reducer

Sources/ComposableArchitecture/Effect.swift
A few things I noticed. Up for workshopping further.
=> Minor tweaks to Effect's API for consistency

Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
=> Typo fix in IfLetStore’s docs.

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift
Figured it'd be better to catch these in debug builds early.
=> Fatal error for identified array subscript misuse

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/ReusableComponents-Download.swift
Noticed this yesterday but forgot to PR.
=> Remove a few unnecessary initializers from demos

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/TicTacToe/Tests/AppCoreTests.swift, Examples/TicTacToe/Tests/TicTacToeTests.swift, Examples/TicTacToe/Tests/TwoFactorCoreTests.swift, Examples/TicTacToe/TicTacToe.xcodeproj/project.pbxproj, Examples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/AppCore.xcscheme, Examples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/TicTacToe.xcscheme, Examples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/TwoFactorCore.xcscheme, Sources/ComposableArchitecture/Internal/Debug.swift
Few things we talked about this morning...
=> Remove some old tests and guard debug code in #if DEBUG.

Examples/LocationManager/LocationManager/LocalSearchClient/LocalSearchModels.swift
Some good finds from @johankool!
=> LocationManager example app: Fix equality checks in client models.

Sources/ComposableArchitecture/SwiftUI/ViewStore.swift
Make it clear that it's not specifically for SwiftUI or specifically for views.
=> Update documentation for ViewStore

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift
=> Move documentation inside compiler directive

Examples/LocationManager/Mobile/LocationManagerView.swift, Examples/Search/Search/SearchView.swift, Examples/TicTacToe/Sources/RootView.swift, Examples/Todos/Todos/Todos.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Sources/ComposableCoreLocation/Models/Region.swift
Not optimizing for iPad or anything, just making it scale better.
=> Make demos render better on iPad

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
=> Implement IdentifiedArray.replaceSubrange

.github/workflows/format.yml, Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
This will allow us to take minor updates. Also ran swift-format manually since GH actions are having problems right now.
=> Update Format Workflow

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift
Hat tip to @mattt (https://twitter.com/mattt/status/1264976073965502464)
=> Simplify TestScheduler sorting

Examples/Search/Search/SearchView.swift, Examples/Search/Search/WeatherClient.swift, Examples/Search/SearchTests/SearchTests.swift
Noticed some stuff that was being done in an old style still.
=> Update Search Demo

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift
Talked about this yesterday. Wasn't as bad as I thought!
=> Remove recursion from TestScheduler.advance

Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/TimerTests.swift
This PR addresses the case you found earlier by cleaning up our cancellation logic.
=> Cancellation Fixes

README.md
Just a quick mention what "effect" means in this part of the readme. To address #173.
=> Update readme to better describe what the reducer returns.

Sources/ComposableArchitecture/Reducer.swift
Updated the identified array assertion and made a few tweaks.
=> Update assertion messaging

README.md
=> Add mention of RxSwift TCA fork in README

Sources/ComposableCoreMotion/MotionManager/MotionManagerLive.swift
Some ideas for dependencies cleanup.
=> Some cleanup for MotionManager

Sources/ComposableCoreLocation/Mock.swift
Add missing optional related to #205
=> Add a missing optional related to #205

.github/workflows/ci.yml, Makefile, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Hopefully this won't make CI more flakey.
=> Xcode 11.6/12 CI

Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
Fixes a small bug I found yesterday.
=> Stop audio when deleting memo that is playing

Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/TimerTests.swift
Fixes #232.
We can refine this as future betas are released, but hopefully it will unblock people for now.
=> Fix iOS 14 Cancellation Crash

.github/workflows/documentation.yml
This reverts commit 455af2de133b82f8d3339552e056a5051868cb25. Thanks @mluisbrown for the heads-up!
=> Revert "Update documentation.yml"

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndActionSheets.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift
Just a couple of typos in the CaseStudies project.
=> Typo fixes

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift, Tests/ComposableArchitectureTests/LCRNG.swift
This PR fixed https://github.com/pointfreeco/swift-composable-architecture/issues/253
=> Add implementation of shuffle on IdentifiedArray

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
=> Document ScrollViewReader problem

.github/workflows/ci.yml, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Looks like CI finally has beta 4!
=> Update CI to include Xcode 12

.spi.yml, .swiftpm/xcode/xcshareddata/xcschemes/ComposableArchitecture_watchOS.xcscheme, Makefile, Tests/ComposableCoreMotionTests/ComposableCoreMotionTests.swift
A few CI fixes to get SPI in better shape.
=> Swift Package Index fixes

Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableCoreLocation/Interface.swift, Sources/ComposableCoreLocation/Live.swift, Sources/ComposableCoreLocation/Mock.swift, Sources/ComposableCoreLocation/Models/AccuracyAuthorization.swift
Fix for https://github.com/pointfreeco/swift-composable-architecture/issues/306
https://developer.apple.com/documentation/corelocation/claccuracyauthorization
=> Add support for AccuracyAuthorization

Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift
Touched base with @willisplummer about https://github.com/pointfreeco/swift-composable-architecture/pull/294 and he said we could take the reins. Just a few small fixes for Xcode 12.
=> Voice Memos Fixes

Examples/TicTacToe/Sources/Core/LiveAuthenticationClient.swift
Good find on the forums here: https://forums.swift.org/t/tictactoe-random-error-combine-bug/38307/3
=> Use serial queue for Tic Tac Toe authorization

Sources/ComposableArchitecture/Reducer.swift
Replace `struct` with `enum` for actions
=> Fix Reducer Docs

README.md
=> Direct people to GH discussions instead of Swift forums

.github/workflows/ci.yml
They're unfortunately super flaky right now.
=> Disable Big Sur tests

Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift
Suggestion from @ryanbooker: https://github.com/pointfreeco/swift-composable-architecture/discussions/351
=> Simplify UIKit list case study

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift
=> Fatal error replacing identified elements with invalid ids

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
Doing a lil evening writing and wanted to address #357. Got a little side-stepped realizing we don't really document scoping a bit more deeply. Will try to flesh things out a bit more before merging so leaving as a draft for now, but didn't wanna lose track of it.
=> Document `scope` a bit more deeply

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift
Forgot to combine this back in.
=> Fix root reducer

Sources/ComposableArchitecture/Effect.swift
Ha kinda forgot about this in the shuffle.
=> Remove old Effect.fireAndForget()

README.md
Figure it's nice to leave a breadcrumb to a more substantial project.
=> Link to isowords

README.md
Some updates that came from the discussion in #445.
=> Clarify that Store's lack of queueing.

Examples/TicTacToe/Sources/Views-UIKit/AppViewController.swift, Sources/ComposableArchitecture/SwiftUI/TextState.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Tests/ComposableArchitectureTests/StoreTests.swift
#497 brought in a good clarification, but re-reading through the original docs and things felt a bit muddy. Here's an attempt at a quick rewrite.
=> Update `Store.ifLet` docs

Sources/ComposableArchitecture/Internal/Deprecations.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
We're working on some `scope`/`ViewStore` optimizations and so want to get a test in place to show the current behavior so that we can better see future improvements.
=> Add a few more store tests.

Sources/ComposableArchitecture/SwiftUI/Alert.swift
=> Fix typo in AlertState docs

Tests/ComposableArchitectureTests/StoreTests.swift
Let's also get this test into main for posterity.
=> Add test for publisher with many synchronous effects.

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
The fix in #471 introduced overhead in which every `ForEachStore` content block was being called eagerly, which means the creation of unnecessary stores. PRed is an alternative fix that still avoids the original crash reported, and seems safe in practice. The force unwrap is a little scary, but maybe unavoidable...
=> Fix ForEachStore

Sources/ComposableArchitecture/Store.swift
Like we discussed, this simplifies the internals a lil bit and shouldn't have much of measurable cost. If so we could maybe inline them away?
=> Remove convenience initializer on Store

Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift
=> Fix closure parameter.

README.md
i've added indonesian translation, also add `Translations` section to `Table of contents`
feel free for feedback
=> Add Indonesian Translation

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Basics.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudies/Internal/CircularProgressView.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AnimationsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-BasicsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-CancellationTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-TimersTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-LifecycleTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableFavoritingTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Examples/Search/SearchTests/SearchTests.swift, Examples/TicTacToe/Tests/LoginCoreTests.swift, Examples/Todos/TodosTests/TodosTests.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
Just some clean up because we'll be messing with this code soon in episodes.
=> Extract number fact dependency to a FactClient.

Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
Goes up to 9 cases + 1 default = 10 views in a tuple.
Addresses #602.
=> Add more SwitchStore overloads

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift
Had some debug code that puzzled me while testing some of the Case Path changes today.
=> Revert code that snuck in #267

Sources/ComposableArchitecture/Internal/Deprecations.swift
I accidentally deleted this in #632.
=> Bring back deprecated IfLetStore initializer.

Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
=> Add test for view store state access

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreTests.swift
- Adds a failing test demonstrating #661
=> Buffered Actions Failing Test

.github/workflows/format.yml, Makefile
This branch'll probably have a lil churn while trying to get the action to work.
=> Async/await swift-format support

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift
I've noticed that currently there seems no way to perform animations when alert actions are sent.
=> Enables animations for alert button actions

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndActionSheets.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AlertsAndActionSheetsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift
This PR refines the domain modeling I suggested in #680.
=> Update AlertState.Button APIs for animation

Examples/TicTacToe/tic-tac-toe/Tests/AppCoreTests/AppCoreTests.swift, Sources/ComposableArchitecture/Reducer.swift
=> Use `modify` helper in Tic-Tac-Toe integration test

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift
Now that the episode is out we can have a case study about `@FocusState`.
=> @FocusState case study.

README.md
Hello!
I added an italian translation at the following link.
https://gist.github.com/Bellaposa/5114e6d4d55fdb1388e8186886d48958
=> Italian Transaltion

Sources/ComposableArchitecture/Effect.swift, Tests/ComposableArchitectureTests/EffectTests.swift
Some small updates to the #705 PR.
=> Catch to effect updates

README.md
Hello there! After seeing that an Italian translation of the README.md was added in the latest release, I felt compelled to put my bilingual proficiency to the test. Here's the link if you want to test your French skills too 😁: 
[https://gist.github.com/nikitamounier/0e93eb832cf389db12f9a69da030a2dc](https://gist.github.com/nikitamounier/0e93eb832cf389db12f9a69da030a2dc)
=> Add French translation of README.md

.github/workflows/format.yml
Let's turn off the formatting action to get the red X off the repo root.
=> Turn off formatting action

Examples/TicTacToe/tic-tac-toe/Sources/GameCore/GameCore.swift, Examples/TicTacToe/tic-tac-toe/Sources/GameCore/Three.swift, Examples/TicTacToe/tic-tac-toe/Sources/GameSwiftUI/GameView.swift, Examples/TicTacToe/tic-tac-toe/Sources/GameUIKit/GameViewController.swift
Just a small domain modeling exercise.
=> Model Tic-Tac-Toe board using proper type

Sources/ComposableArchitecture/Beta/Concurrency.swift
Realizing we can just lean on the new `Publisher.values` bridge to simplify things.
=> Clean up `suspend(while:)`

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer.swift
Noticed these were anonymous for some reason.
=> Make file/line parameters explicit

Sources/ComposableArchitecture/Effect.swift
Just a minor change if you want.
=> Pass attemptToFulfill directly to Future

Sources/ComposableArchitecture/Store.swift
Fixes pointfreeco/swift-composable-architecture#745
=> Correct Store documentation

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadClient.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift
=> Simplify Reusable Download Component

Sources/ComposableArchitecture/SwiftUI/Binding.swift
Definitely complicated, but view state/actions are in general. These docs can probably be improved to better convey that.
=> Add documentation for `BindingAction.pullback`

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndActionSheets.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AlertsAndActionSheetsTests.swift
=> Fix unfunctional cancel button handlers in AlertsAndActionSheets case study

Sources/ComposableArchitecture/SwiftUI/Binding.swift
Had this file open in Xcode and a few things stood out, so made some edits.
=> Update bindable helpers docs

Sources/ComposableArchitecture/Beta/Concurrency.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
=> Fix macOS <11 builds with Xcode 13 RC

Sources/ComposableArchitecture/Store.swift
Should avoid confusion like that of #788.
=> Thread messaging

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreTests.swift
This shouldn't be merged till we merge #754.
=> Deprecate Store.publisherScope

Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Client.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Failing.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Live.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/SpeechRecognition/SpeechRecognitionTests/SpeechRecognitionTests.swift
This caught my eye and thought we could clean it up like we have some of the other long-living clients.
=> Clean up speech recognition case study.

Sources/ComposableArchitecture/Store.swift
=> Check main thread via Thread.isMainThread

.github/workflows/ci.yml
This would be useful to have before merging #863
=> Update Xcode version from 13.0 to 13.1

Examples/TicTacToe/tic-tac-toe/Sources/NewGameUIKit/NewGameViewController.swift
=> Fix typo in Tic-Tac-Toe demo

Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Tests/ComposableArchitectureTests/EffectTests.swift
=> Fix `Task.sleep` deprecation warnings

Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/AudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/FailingAudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/LiveAudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/AudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/FailingAudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/LiveAudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/Helpers.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
Just some more cleanup we chatted about.
=> Clean up Voice Memos demo

Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift, Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift, Examples/CaseStudies/tvOSCaseStudies/FocusView.swift
Noticed a deprecation warning for using an old TCA API. I'm not 100% satisfied with the fix yet...but it's probably better than leaving as is.
=> Fix UIKit Case Study warning

README.md
Hello, 
As per issue #933 , we @bashmoanas, @Abdeltwab, and myself Added an Arabic translation: 
https://gist.github.com/NorhanBoghdadi/1b98d55c02b683ddef7e05c2ebcccd47
=> Add Arabic Translation

Sources/ComposableArchitecture/Effects/Cancellation.swift
While investigating #968 I realised the in flight cancellation could probably be done inline. Avoids an extra call to `cancellablesLock` which resulted in ~70% performance bump
```swift
benchmark("cancelInFlight concatenate") {
let _ = Effect(value: 1)
._cancellable(id: 1, cancelInFlight: true)
.sink { _ in }
}
benchmark("cancelInFlight inline") {
let _ = Effect(value: 1)
.cancellable(id: 1, cancelInFlight: true)
.sink { _ in }
}
// cancelInFlight concatenate 16829.000 ns ±  29.10 %      78900
// cancelInFlight inline       9898.000 ns ±  28.35 %     136377
```
=> Cancel in flight effects inline instead of returning concatenated effect

Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectTests.swift
=> Don't consider an effect in-flight till it's kicked off

README.md
Hi Brandon and Stephen, I added a simplified Chinese translation.
=> Simplified Chinese Translation

Sources/ComposableArchitecture/Store.swift
As always, thanks for the amazing work 👏🏼
=> Fix a typo in Store docs

Examples/CaseStudies/UIKitCaseStudiesTests/UIKitCaseStudiesTests.swift
Hi there,
I thought it would be good to add some basic unit tests on the UIKitCaseStudies.
This PR adds two simple unit tests.
If you guys think that it won't be useful, we can close this PR.
=> Add unit tests to UIKitCaseStudies

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Concurrency.swift
Added priority to the new async `fireAndForget` and moved it to the Concurrency.swift file.
=> Add priority to async fireAndForget.

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
=> Use `eraseToEffect` mapping functions

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
Just a few small things I noticed.
=> Test Store documentation updates

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Basics.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/Internal/ResignFirstResponder.swift
We have this fix in Tic-Tac-Toe already, but I noticed it happening in the Case Studies app.
=> Add more workarounds for disabled field SwiftUI bug

Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift
Proposal of fix for #1160.
I've also added 2 new tests to avoid regression.
Let me know what you think. Thank you! :)
=> [Fix] Check the state does not actually change when no changes are expected

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Basics.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-BasicsTests.swift
=> Simplify effects basics case study.

Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift
Doing both at once is noisy in tests.
=> Fail if testing, runtime warn otherwise

README.md
Hi, thank you for using your wonderful library.
I have prepared a Japanese translation and would be happy if you could check it.
=> Add Japanese translation link to README

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift
The reuse of the `.tapped` action is maybe not optimal though.
=> Set the circle in the center of the view in the animation's study

Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Live.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/SpeechRecognition/SpeechRecognitionTests/SpeechRecognitionTests.swift
=> More clean up in speech demo

Examples/Todos/Todos/Todo.swift, Examples/Todos/Todos/Todos.swift, Examples/Todos/TodosTests/TodosTests.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
Just a bit more consistency with how reducers are generally defined.
=> Todo/VoiceMemo -> TodoState/VoiceMemoState

README.md
Hi, I took the time to contribute to this wonderful project by creating a translation to Spanish. I think this will help a lot of people in LatAm and Spain to understand TCA in their language.
The README includes the latest concurrency updates made. Feel free to ask me any questions.
Regards,
Pitt
=> Spanish Translation of TCA's README

Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
Updating the voice memos tests to be more in the style we recommend.
=> Update voice memo test dependencies directly on store.

README.md
HI, I found a very minor error in the README while translating the Japanese and have corrected it.
Could you please check them when you have time?
=> Fix README indent and missing bracket

Examples/README.md, README.md
Fixing minor typos while translating the docs.
=> Fix minor typos in README

Sources/swift-composable-architecture-benchmark/StoreScope.swift, Sources/swift-composable-architecture-benchmark/main.swift
We will be PR'ing some improvements to scoping performance soon so we want to break out this benchmark to its own suite to make it clearer.
=> Move scope benchmarks to its own suite.

Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/LiveAudioRecorderClient.swift
Thank you for many TCA sample projects!
I have a problem in Voicememos that is cant't play and low volume recoding voice.
I changed AVAudioSession setting in my project.
And, I think should change to sample project.
=> change AVAudioSession category

Sources/ComposableArchitecture/Internal/_StateObject.swift
In #1336, I assumed wrongly that `View` invalidation was still effective even when activating the `ObservableObjectPublisher` extracted from the first `ObservableObject` instance it encountered during the lifetime of the view.
This is not the case, and the `ObservableObjectPublisher` object instance that is activated needs to be issued by the `ObservableObject` currently exposed by `@ObservedObject` for `View` invalidation to work as expected.
This PR fixes this issue. The `ViewStore`'s `objectWillSend` publisher now emits blindly into another `ObservableObjectPublisher?` instance that we switch dynamically without recreating the subscription. As all interactions happen on the main thread, it is safe to do so.
=> Update `ObservableObjectPublisher` instances in `_StateObject`

Examples/CaseStudies/UIKitCaseStudies/RootViewController.swift
It didn't work, at least on my local (`Call to main actor-isolated initializer 'init(store:)' in a synchronous nonisolated context`)😛
Fixed by moving `dataSource` into the `RootViewController`
=> Fix the CaseStudies (UIKit)

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-RecursionTests.swift
Makes the case study on main look more similar to how it looks on protocol-beta. Also adds some tests.
=> Clean up the recursive case study.

Examples/Todos/Todos/Todos.swift, Examples/Todos/TodosTests/TodosTests.swift
We have a small bug in some collection indexing translation code. This should fix it.
=> Todos demo: fix sorting filtered todos

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md
Hi! Found some small typos while copying code snippets from Performance.md. Fixed in this PR.
=> Fix Performance.md brackets

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Publisher.swift
I'm guessing this is why it got quite noisy in latest commit :)
=> Remove dump calls

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Internal/Locking.swift, Sources/ComposableArchitecture/Internal/TaskCancellableValue.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TaskCancellationTests.swift
By making a few internal things public but hidden behind `@_spi` we can get more test coverage on things when testing in release.
How do we feel about doing this kind of thing?
=> [proof-of-concept] Use @_spi to test more in release.

Sources/Dependencies/Dependencies/MainQueue.swift, Sources/Dependencies/Dependencies/MainRunLoop.swift, Sources/Dependencies/Dependencies/RandomNumberGenerator.swift, Sources/Dependencies/Dependencies/UUID.swift
Regardless of #1471 evolution, this needs to be changed.
=> Replace `Effect<Action>` by `Effect<Action, Never>` in documentation

README.md
=> Remove a dangling `</summary>` tag

Sources/ComposableArchitecture/ViewStore.swift, Sources/swift-composable-architecture-benchmark/ViewStore.swift, Sources/swift-composable-architecture-benchmark/main.swift
Just wanna get something on main so that we can compare in the future.
=> View store benchmark

Sources/ComposableArchitecture/Effects/ConcurrencySupport.swift
Extending the work started with #1565.
=> Conditionally conform UncheckedSendable to Hashable, Codable

Sources/Dependencies/DependencyValues.swift
Fix a trivial incomplete documentation sample code.
=> Fix the documentation of DependencyValues

Sources/Dependencies/Dependencies/OpenURL.swift
=> Avoid `openURL` ambiguity

Sources/ComposableArchitecture/Effects/Cancellation.swift
Saw it while reading the documentation. Not sure if this is a typo, if not please close this PR
=> Fix a possible typo in withTaskCancellation

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md
=> Fix minor error on Performance document

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Examples/Todos/Todos/Todo.swift, Examples/Todos/Todos/Todos.swift, Examples/Todos/TodosTests/TodosTests.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ViewStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUI.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/BindingReducer.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
It occurred to us that this solution unfortunately is incompatible with view actions. We have an alternate solution that works, so I'll PR that in the future if no others materialize!
=> Revert #1790

Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift
=> Fix UIKit's "Navigate and Load" study

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
=> Bump `Dependencies` to 0.1.2

Package.swift
I added explicitly dependency on OrderedCollections based on https://github.com/pointfreeco/swift-composable-architecture/discussions/1818.
=> Explicitly depend on OrderedCollections

Sources/ComposableArchitecture/SwiftUI/Alert.swift
I'm aware the branch is unstable. Feel free to discard this if it doesn't suit your plans.
=> Fix build error in navigation branch after merge

README.md
=> Bump up doc version for 0.50.0 release

Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift, Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift
There are some more complicated ones with sendability checking to get to, but here are a few log-hanging fruit.
=> Fix some Xcode 14.3 warnings

Sources/ComposableArchitecture/Store.swift
Noticed this was missing. I tried to somewhat match the documentation for `TestStore`.
=> Adds missing documentation for the `Store` initializer

README.md
Hi! I have translated the README into Russian, hoping that it will help russian-speaking developers use TCA 🙂
=> Russian Translation

Sources/ComposableArchitecture/SwiftUI/Binding.swift
Hi there,
I found a mistake in the documentation for BindingAction in Binding.swift and have corrected it.
=> Fix Document in BindingAction

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/_CAsyncSupport/_CAsyncSupport.h, Sources/_CAsyncSupport/module.modulemap, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift, Tests/ComposableArchitectureTests/SerialExecutor.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
See https://github.com/pointfreeco/swift-dependencies/pull/83 for more info.
=> Revert #2033

Sources/ComposableArchitecture/ReducerProtocol.swift
If there ever was a nitpick ... 🤦‍♂️
(bumped into this by accident)
=> Missing space in Reducer constraints

Sources/ComposableArchitecture/Internal/Deprecations.swift
=> Update line-wrapping convention

Sources/ComposableArchitecture/Effect.swift
Hi again!
I corrected two small mistakes in the `Effect.swift` file. Please review the changes. 😄
=> Correct some comments in Effect.swift

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
From #2083
---
I was not sure if I could change the base branch without all the additional diff's from the prerelease branch so here is a separate PR.
=> Add Sendable conformance to PresentationState

Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md
Hi, I found a mistake in Testing.md and have corrected it.
=> Fix Document in Testing.md

Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftConcurrency.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/EffectDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/EffectRun.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUI.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Publisher.swift, Sources/ComposableArchitecture/Effects/TaskResult.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/TestStore.swift
Also includes some miscellaneous doc reference fixes.
=> Make Send sendable

Sources/ComposableArchitecture/Documentation.docc/Tutorials/01-YourFirstFeature.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/02-AddingSideEffects.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/03-TestingYourFeature.tutorial
Thanks for creating such a fantastic tutorial!
I made some changes to fix typos and improve readability.
=> Fix typo in the "Meet the Composable Architecture" tutorial

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-YourFirstPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0016.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0017.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0008-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0010.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0005-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0005.swift
A quick run-through of tutorials before the interview tomorrow 😅
These are mostly minor typos, but even such tiny things can drive beginners away.
P.S. Fantastic job with these tutorials 🙌
=> Small fixes in the DocC

Sources/ComposableArchitecture/ViewStore.swift
=> fix ViewStore binding doc comment

README.md
Added Hindi (Indian) language in README.md
=> Added Hindi (Indian) language in README.md

Examples/Standups/Dependencies/DataManager.swift, Examples/Standups/README.md, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/ViewStore.swift
Note that the diff line where it looks like a no-op is actually adding a missing newline to end of file
=> Fix some swiftdoc and small tidy

Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift, Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift, Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Examples/Integration/Integration/BindingLocalTestCase.swift, Examples/Integration/Integration/NavigationStackBindingTestCase.swift, Examples/Integration/Integration/PresentationItemTestCase.swift, Examples/Integration/Integration/SwitchStoreTestCase.swift, README.md, Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/ViewStore.swift, Sources/swift-composable-architecture-benchmark/StoreScope.swift, Sources/swift-composable-architecture-benchmark/ViewStore.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Please see https://github.com/pointfreeco/swift-composable-architecture/discussions/2223 for context and discussion.
=> Add `Store.send` and `Store.withState`

Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Effect.swift
Joins `ReducerOf` and `StoreOf` for simplifying some call sites.
=> Add `EffectOf`

Examples/Search/Search/SearchView.swift, Examples/TicTacToe/tic-tac-toe/Sources/AppSwiftUI/AppView.swift, Examples/Todos/Todos/Todos.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift
=> Update some demos to use `NavigationStack`

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0000.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0004-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0006.swift
Fixes an issue brought up in #2271
=> Fix delegate equatability in tutorial.

Sources/ComposableArchitecture/SwiftUI/Binding.swift
This adds the new `BindingViewStore` initializers available on `WithViewStore` to `ViewStore`.
I believe these are useful for when you want to store your `ViewStore` as an `@ObservedObject` on your view (as described in the [Performance](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/performance) article) to avoid compiler performance issues. For example:
```swift
struct NotificationSettingsView: View {
let store: StoreOf<Settings>
@ObservedObject var viewStore: ViewStore<ViewState, Settings.Action>
init(store: StoreOf<Settings>) {
self.store = store
self.viewStore = ViewStore(store, observe: ViewState.init)
}
struct ViewState: Equatable {
// ...
init(bindingViewStore: BindingViewStore<Settings.State>) {
self._enableNotifications = …
```
=> Add BindingViewStore initializers for ViewStore

Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindableStoreTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
=> Fix `WithViewStore` initializer ambiguity

Sources/ComposableArchitecture/TestStore.swift
=> Deprecate `TestStore` scoping

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Reducer/Reducers/BindingReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/FullScreenCover.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/NavigationDestination.swift, Sources/ComposableArchitecture/SwiftUI/NavigationLinkStore.swift, Sources/ComposableArchitecture/SwiftUI/NavigationStackStore.swift, Sources/ComposableArchitecture/SwiftUI/Popover.swift, Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift, Sources/ComposableArchitecture/SwiftUI/Sheet.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/UIKit/AlertStateUIKit.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Sources/ComposableArchitecture/ViewStore.swift
Better for documentation and auto-fill.
=> Add named closure arguments

README.md, Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md
=> Bump version in docs

Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md
I found a mistake in Bindings.md and fixed it.
=> Fix document in Bindings.md

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
I found a mistake in StackBasedNavigation.md and fixed it.
=> Remove unnecessary parameter of NavigationStackStore in StackBasedNavigation.md

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md, Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/Effects/Throttle.swift, Tests/ComposableArchitectureTests/ThrottleTests.swift
We may have too eagerly removed this operator from 1.0 so let's bring it back.
=> Bring back throttle

Sources/ComposableArchitecture/SwiftUI/FullScreenCover.swift
see https://github.com/pointfreeco/swift-composable-architecture/discussions/2351
=> prevent crash on catalina from missing symbol

Sources/ComposableArchitecture/Effects/Cancellation.swift
* Fix missing send
* hope it helps!
=> Fix Effect.run Example in Documentation

Examples/Integration/Integration/SwitchStoreTestCase.swift
Little action error in `Integration` target.
=> Fix SwitchStoreTestCase

README.md
This is an additional modification from https://github.com/pointfreeco/swift-composable-architecture/pull/2481:
I wrapped `FeatureView` with `WindowGroup` in `MyApp/body`
=> Fixed the example code in README.md

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
- remove unused paramter(isDuplicate)
=> fix WithViewStore extension document

Sources/ComposableArchitecture/Reducer/Reducers/OnChange.swift, Tests/ComposableArchitectureTests/Reducers/OnChangeReducerTests.swift
=> Drop `Equatable` constraint on `Value` in `_OnChangeReducer`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration.xcodeproj/project.pbxproj, Sources/ComposableArchitecture/Internal/AreOrderedSetsDuplicates.swift
Just something we discussed today.
=> Short circuit == when ordered sets don't have same size.

README.md
This PR updates and fixes documentation links in README.
=> Update documentation links in README

Sources/ComposableArchitectureMacros/ObservableStateMacro.swift
I changed DiagnosticsError's message.
=> fix DiagnosticsError message

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.5.md
=> Fix typo in MigratingTo1.5.md

Examples/Integration/Integration.xcodeproj/project.pbxproj, Examples/Integration/Integration/IntegrationApp.swift, Examples/Integration/Integration/Legacy/IfLetStoreTestCase.swift, Examples/Integration/IntegrationUITests/Legacy/IfLetStoreTests.swift, Examples/Integration/TestCases/TestCase.swift, Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/ScopeCacheTests.swift, Tests/ComposableArchitectureTests/StoreFilterTests.swift
Fixes #2632.
I was able to get a unit test and integration test to verify the fix.
=> Don't replay changes to invalidated child stores.

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-MultipleDestinations.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0008-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0010.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0011.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0012.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0013.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0014.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0015.swift
Noted a few things while watching @vincent-pradeilles work his way through it.
=> Tutorial fixes

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-SharedStateTests.swift
This is just moving some things around and renaming things. Bigger changes to shared state coming soon :)
=> Clean up shared state case study

Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift
Thank @bobspryn for the report.
=> Fix retain cycle in `PresentationModifier`

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-ComposingFeatures.tutorial
I would have liked to add `@testable import XxxApp` as well, but I couldn't think of a good app name 😅
=> Fix "Composing features" tutorial

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0006-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0013.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0016.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0017.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0007-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-TestingPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004.swift
The new Observation tools in 1.7.0 are incredible..! Thanks for the release 🚀 
While re-doing the latest version of the tutorial, I found a few things that need to be fixed.
=> Fix Navigation tutorial

Sources/ComposableArchitecture/Effects/TaskResult.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/FullScreenCover.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/NavigationDestination.swift, Sources/ComposableArchitecture/SwiftUI/NavigationStackStore.swift, Sources/ComposableArchitecture/SwiftUI/Popover.swift, Sources/ComposableArchitecture/SwiftUI/Sheet.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/ViewStore.swift
=> remove invalid newlines

Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift
=> Added missing namespace for Scope when in ReducerMacro 

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md
I found a mistake and fixed it.
=> Fixed the article of tree-based navigation

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
Case name should be specified but missed.
=> Fix StackBasedNavigation.md

Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift
The Favorites case study doesn't list any favorites. 
Here is a small fix for that.
=> Fix Favorites case study by using episode mocks

ComposableArchitecture.xcworkspace/xcshareddata/xcschemes/ComposableArchitecture.xcscheme, Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift, Tests/ComposableArchitectureTests/CompatibilityTests.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift, Tests/ComposableArchitectureTests/ObserveTests.swift, Tests/ComposableArchitectureTests/Reducers/ForEachReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/IfCaseLetReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/IfLetReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/ScopeCacheTests.swift, Tests/ComposableArchitectureTests/ScopeTests.swift, Tests/ComposableArchitectureTests/StorePerceptionTests.swift
This allows us to test more things about TCA in release mode.
=> Emit test failure when warning in release.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package@swift-5.9.swift, Sources/ComposableArchitecture/Observation/ObservationStateRegistrar.swift
An upstream fix to Perception needs to be applied here.
Fixes #3028
=> Bump Perception availability

Sources/ComposableArchitecture/Documentation.docc/Articles/Reducers.md, Sources/ComposableArchitecture/Macros.swift
Tough to get into the weeds here, so I kept things short, but if you have ideas to flesh out and improve let's discuss!
=> Add a note about nested enum reducers in docs

Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
=> Fix for throttle logic.

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Reducers.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md, Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Reduce.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUIIntegration.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/MeetingNavigation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-YourFirstFeature.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-ComposingFeatures.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-NavigationStacks.tutorial, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift
=> Fix a bunch of references.

README.md
Added visionOS to supported platforms description
=> Update README.md to include visionOS

Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md
It'd be good to have a place to point folks to when encountering the issue.
=> Note Swift bug in documentation

Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
=> Remove duplicates in app storage key.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/SharedState/SharedChangeTracking.swift
Another fix for a symbol mentioned in https://github.com/pointfreeco/swift-issue-reporting/issues/100
=> Shared: Update `XCTFail` to `reportIssue`

Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift
fix minor typo in FileStorageKey.
=> Fix minor typo in FileStorageKey

Sources/ComposableArchitecture/RootStore.swift
A relatively simple `Box` to `LockIsolated` conversion. Technically the locking will make processing an action slightly more expensive, so if we want to accept the `Box` as safe enough, we could unchecked-send it instead, or leave the warning till we address the core issue in the future.
=> Address `RootStore` sendability warnings

Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ResuableOfflineDownloads/ReusableComponents-Download.swift, Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ReusableFavoriting.swift, Package.resolved
Replaced deprecated APIs and updated examples with the latest APIs.
=> Update `05-HigherOrderReducers` CaseStudies

Examples/SyncUps/SyncUps/App.swift, Sources/ComposableArchitecture/Internal/DispatchQueue.swift, Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/SharedTests.swift
=> Fix potential deadlock in Shared

.github/ISSUE_TEMPLATE/bug_report.yml
Let's update the issue template to push people towards providing a reproducing project instead of "steps to reproduce".
=> Update issue template.

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, .github/workflows/ci.yml, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Makefile, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
This is just a draft for now...
=> Improve CI jobs

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/03-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ResuableOfflineDownloads/ReusableComponents-Download.swift, Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ReusableFavoriting.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/05-HigherOrderReducers-ReusableOfflineDownloadsTests.swift
Figured we should start updating the demos to run in Swift 6 mode, so I'm starting with just the SwiftUI case studies.
=> Update case studies to run in Swift 6 mode.

.github/workflows/format.yml, Makefile
This should update the format.yml workflow to use the now bundled swift-format.
=> Update format action to use Xcode 16

README.md
I created a Turkish translation of the README file.
=> Create Turkish translation of TCA's README
