pointfreeco/swift-composable-architecture

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-LoadThenPresent.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-StrictReducers.swift, Examples/TicTacToe/Tests/GameSwiftUITests.swift, Examples/TicTacToe/Tests/LoginSwiftUITests.swift, Examples/TicTacToe/Tests/NewGameSwiftUITests.swift, Examples/TicTacToe/Tests/TwoFactorSwiftUITests.swift, Sources/ComposableArchitectureTestSupport/TestStore.swift
This modifies the `TestStore` interface to be a little more inline with `Store`. Rather than expose a 5-argument initializer to `TestStore`'s auto-complete, we can instead disclose this transformation as a `scope` method. Should hopefully simplify things for folks that don't need to `scope` by only exposing a single initializer!
=> Introduce TestStore.scope

README.md, Sources/ComposableArchitecture/CasePaths/EnumReflection.swift, Sources/ComposableArchitecture/CasePaths/Operators.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/SwiftUI/ViewStore.swift
Fixes some minor documentation issues.
=> Documentation clean up

.github/workflows/format.yml
Looks like actions can't run on forks: https://github.com/stefanzweifel/git-auto-commit-action/issues/25#issuecomment-570800796
So instead of formatting PRs we can instead let master auto-format itself when need be.
=> Run swift-format on master post-merge

.github/workflows/format.yml
Seems more reliable to always run. Otherwise the build can "fail" weirdly on merges of README-only changes.
=> Remove paths from format action

Sources/ComposableArchitecture/SwiftUI/ViewStore.swift
This removes the 'get' parameter definition for the following function:
```
public func binding(
send localStateToViewAction: @escaping (State) -> Action
) -> Binding<State> {
self.binding(get: { $0 }, send: localStateToViewAction)
}
```
=> removed unused parameter definition

Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift
When the app is compiled in Release configuration with `.debug()` function still attached to a reducer, `return .none` short-circuts the reducer instead of just removing debug feature.
Just released an app to TestFlight, that doesn't work there but works on-device in Debug configuration : )
=> Remove debug gracefully for Release configurations

.github/workflows/format.yml, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
Fixes #21 and a few other things, which I will review.
=> Assorted fixes for collections of state

Examples/TicTacToe/Sources/Core/GameCore.swift, Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift
#25 inadvertently broke Xcode previews, which would crash during compilation due to a `_modify` block on `IdentifiedArray` that yielded _and_ accessed the value that it just yielded.
We can explore different avenues for optimizing `IdentifiedArray` in the future.
=> Fix Xcode previews crash

.github/workflows/format.yml
Hm, https://github.com/pointfreeco/swift-composable-architecture/pull/33 doesn't seem to have worked as advertised. Formatting was skipped for some reason: https://github.com/pointfreeco/swift-composable-architecture/runs/654060950?check_suite_focus=true
Might have to revoke my kudos...
=> Run swift-format when master is pushed

Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
Fixes #39.
Apparently nested `Group`s have problematic behavior with respect to `onAppear`, and so our usage of `Group` in `IfLetStore` can unexpectedly lead people to that SwiftUI bug.
Luckily we can avoid it entirely.
=> Don't use Group in IfLetStore.

Sources/ComposableArchitectureTestSupport/TestStore.swift
**Crash**
I'm getting a crash because of "Simultaneous accesses to state", apparently this is the culprit:
```swift
public func assert() {
func runReducer(state: inout State, action: Action) {
let effect = self.reducer.callAsFunction(&state, action, self.environment)
...
}
...
runReducer(state: &self.state, action: receivedAction)
...
}
```
I did this change in the assert function. by avoiding passing the state to the inner function the crash not longer happens. 
```swift
func runReducer(action: Action) {
let effect = self.reducer.callAsFunction(&self.state, action, self.environment)
...
}
runReducer(action: self.fromLocalAction(action))
```
Here is the console log
```
Simultaneous accesses to 0x600003bbd780, but modification requires exclusive access.
Previous access (a modification) …
```
=> Fix crash on TCA Test support

.github/workflows/ci.yml
Was passing on the branch that we merged in...but it's now failing. We should revisit this, but maybe something's wrong with that particular build environment on GitHub Actions right now.
=> Disable CI on 11.3.1 for examples

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Sources/ComposableArchitecture/TestSupport/TestStore.swift
No reason to do `dlopen` and `dlsym` every time we do an `XCTFail`.
=> Perform dlopen and dlsym just once.

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
* Identifier-based subscript should get direct `modify` access, with caveats.
* Add `remove(id:)` method.
Addressing discussion from #76.
=> Identified Array Updates

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift
As discussed https://github.com/pointfreeco/swift-composable-architecture/pull/85#issuecomment-627583778 the example doesn't need to use `Reducer.combine` because it only has 1 reducer.
Note that the type declaration can't be removed because the compiler can't infer the type of the global environment.
=> Remove unnecessary combine in the example

Sources/ComposableArchitecture/Reducer.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
As requested here there is this little method. Is a Reducer.combine as an instance method so you can chain a reducer with another. Quite useful when you want to chain a "main" reducer with a "child" reducer. The static Reducer.combine feels more adequate when all reducers have the same "importance". 
I've added a method that accepts a single other reducer as that's what my [original tweet](https://twitter.com/alexito4/status/1260279123907416064) was about but feel free to ping me if you prefer another API. I wouldn't add an overload with varargs because at that point you may want to use the static one.
I've also toyed around with a label ->  `mainReducer.combine(with: childReducer)`, not sure what you prefer. 
I've tried to follow your wording on the docs, but feel free to suggest edits. …
=> Added Reducer.combine instance method

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadClient.swift, Examples/MotionManager/MotionManager/MotionClient/Live.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Live.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Tests/ComposableArchitectureTests/EffectTests.swift
The `async` and `sync` APIs don't quite feel right when we also have `future` and `result`.
=> Rename certain Effect APIs

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/TimerTests.swift
There was a small bug in the test scheduler where if two timers have emissions that later coalesce to happen simultaneously, then it is possible for them to emit in the wrong order. We need to track the order in which the timers were started in order to fix this, and we can do that with a simple auto-incrementing id instead of a UUID.
I haven't run the full demo test suite locally to see if there are any places in our demo tests where we may have been accidentally depending on this logic. Will let CI do that for me...
=> Fix ordering of simultaneous work in test scheduler.

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift, Tests/ComposableArchitectureTests/SchedulerTests.swift
Another small test scheduler bug, this time due to the sorting not properly sorting first by date and then by id.
=> Another fix for order test scheduler intervals.

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
Seems like we should avoid this in release builds.
=> Wrap WithViewStore debugging in compiler directive

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift
Bring back background color so that touches are recognized on full screen, not just text.
=> Animations case study dark mode

Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
=> Make Reducer.debug API more like Publisher.print

Sources/ComposableArchitecture/Internal/Debug.swift, Tests/ComposableArchitectureTests/DebugTests.swift
While state is generally a value type that cannot recursively reference itself, state still could contain the occasional reference type, which could contain a recursive reference to itself, so let's do what `dump` does and keep track of recursive items.
=> Gracefully handle recursive state debug output

README.md
The original creators and maintainers of ReactiveFeedback have created a fork in the [ReactiveCocoa](https://github.com/ReactiveCocoa) organisation, called Loop, and are no longer maintaining the ReactiveFeedback repo. Loop should now be considered the canonical version of this project.
cc: @sergdort and @andersio
=> Change link to Loop / ReactiveFeedback project

Examples/LocationManager/Common/AppCore.swift, Examples/LocationManager/Common/MapView.swift
Currently `MapView` removes and then re-adds all annotations regardless of if it's currently displayed or not. This causes an unpleasant flashing after each region change. 
This PR diffs the new point of interests with the existing ones to decide which annotations should be removed / added.
=> Add and remove map annotations only when necessary

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
I'd love to figure out why `sort` didn't work without these methods, but it seemed like the elements were sorted correctly, but the ids were not.
=> Implement sort() and sort(by:) for IdentifiedArray.

Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift
=> Navigation case study fixes

Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Internal/Diff.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
We found this while working off a feature branch, so just wanting to get it into master.
=> Correctly show (no state changes) in diff.

Sources/ComposableArchitecture/Effects/Timer.swift
@dannyhertz tipped us off to this. This documentation is a little out of date because cancellation is now automatically baked into all effect timers.
=> Update docs for Effect.timer

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Internal/Locking.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
=> Avoid simultaneous access crash on double-cancel

README.md
This ReactiveSwift fork has been merged: https://github.com/trading-point/swift-composable-architecture/pull/1
So let's link to it! We can change the wording here when we get an RxSwift fork 😉
=> Link to ReactiveSwift fork

Sources/ComposableArchitecture/Internal/Create.swift
Let's hide these from rest of the library.
=> Encapsulate Publishers.Create and AnyPublisher(_ callback:)

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/ViewStore.swift
[This](https://forums.swift.org/t/why-isnt-send-method-atomic/36984) question on the forum made me realize that we need to better clarify this assertion failure. This is one idea, open to others though.
=> Clarify assertion failure for incorrect send usage

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Store.swift
Hey! Huge fan of PointFree videos and TCA in particular, thanks for you great work 👏 
According to apple docs it is preferred to call `.subscribe()` instead of `.receive(subscriber:)`. I know, this looks super counterintuitive, did same on my project at first.
`.receive(subscriber:)` is function that is required by protocol, and `.subscribe()` is some function that is implemented inside Combine that eventually  calls `.receive(subscriber:)`. So this fix shouldn't break anything
https://developer.apple.com/documentation/combine/publisher/3204756-subscribe
> Always call this function instead of receive(subscriber:). Adopters of Publisher must implement receive(subscriber:). The implementation of subscribe(_:) provided by Publisher calls through to receive(subscriber:).
=> Replace 'receive(subscriber:)' with 'subscribe()'

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift, Tests/ComposableArchitectureTests/SchedulerTests.swift
Fixes the bug we just uncovered. Turns out that `debounce` works by scheduling interval work that is cancelled, and so if you are not careful about when such work is inserted into the queue it won't get properly removed and will just become recurring work forever. Easiest way to reproduce this is to do `.debounce` followed by `.receive(on:)`, because after the first trigger of the debounce the `receive(on:)` work is queued, and then accidentally removed, which leaves the debounce work around to execute ad infinitum 😬
The fix is to keep around a unique identifier for removing work after it is executed (instead of assuming `scheduled.removeFirst()` will remove the right thing), and to insert the next interval work into the queue immediately before executing the work.
=> Fix scheduling for debounce

README.md
The fork was renamed to `reactiveswift-composable-architecture` to avoid confusion.
It's not urgent as GitHub nicely redirects on renamed repos.
=> Reflect repo rename of ReactiveSwift fork

Sources/ComposableArchitecture/Scheduling/TestScheduler.swift
This probably will have a negligible effect on most test code, but it could improve larger stress tests.
=> Speed up TestScheduler work removal

Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
Our use of `EmptyView` was clever, but while messing with code related to this I realized we could optimize it away entirely.
=> Optimize IfLetStore ViewBuilder code

Sources/ComposableArchitecture/Reducer.swift
As we talked about in #153, This adds an explicit check to ensure that actions reference IDs present in IdentifiedArrays.
Currently there is a crash that seems unintentional. This enforces the semantics of `forEach` in a clear way.
=> Make forEach explictly check that the ID is present in the IdentifiedArray

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-OptionalState.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-LoadThenPresent.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Examples/TicTacToe/Sources/Core/AppCore.swift, Examples/TicTacToe/Sources/Core/LoginCore.swift, Examples/TicTacToe/Sources/Core/NewGameCore.swift, Examples/TicTacToe/Sources/Views-SwiftUI/LoginSwiftView.swift, Examples/TicTacToe/Tests/LoginCoreTests.swift, Examples/TicTacToe/Tests/LoginSwiftUITests.swift, Examples/TicTacToe/Tests/NewGameCoreTests.swift, Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift
This was spurred after a bunch discussions today: #152, #153, #154, #155.
Right now, `optional` reducers will happily toss actions they like to process into the void. This can lead to very subtle bugs where we are sending actions to the reducer and expecting things to happen, but because some sub-state is `nil` nothing happens at all.
Adding this assertion even revealed a "bug" in our TicTacToe logic, where we handle `nil`ing out `LoginState` upon login _before_ letting the `loginReducer` handle its own action. If loginReducer were instrumented with some analytics, we'd be losing those. So I think this (or something like it) would be helpful in the future.
(cc @peterkovacs)
=> Add assertion to Reducer.optional

Examples/LocationManager/CommonTests/CommonTests.swift, Sources/ComposableCoreLocation/Models/Location.swift, Tests/ComposableCoreLocationTests/ComposableCoreLocationTests.swift
I needed to persist Location data, so thought it'd be useful if the `Location` wrapper was `Codable`.
In this implementation the wrapper just proxies the properties of `CLLocation` using `@dynamicMemberLookup`. Let me know what you think.
(Note: I removed the `floor` init parameter as it seems to be a computed property with no useful way of creating one from scratch)
=> Adds Codable support to Location wrapper in ComposableCoreLocation

Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-LoadThenPresent.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Makefile, Sources/ComposableArchitecture/Effect.swift
The naming of the types in these case studies no longer reflect the language we use in describing them, so seems worth updating.
=> Update Naming of Navigation Case Studies

Makefile
The `--quiet` flag hides a little too much information from us.
=> Remove --quiet so that we can diagnose test failures

Tests/ComposableArchitectureTests/ReducerTests.swift
This should fix the flaky `testDebug` test. It seems that the queue we do printing on may sometimes need more time to get its job done.
=> Use expectation fulfillment in testDebug.

Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift
As reported in #182, we have a crash in the voice memos demo when you delete a memo while it is playing. This is happening because there is an in-flight timer effect that keeps running even after the data is removed, and hence we try to run the reducer logic on a row that no longer exists.
The fix is easy enough, we just need to cancel some effects when removing the row, and in fact the assertion we have in `forEach` precisely describes what the problem is, so that's nice!
=> Fix voice memos crasher

Sources/ComposableArchitecture/Reducer.swift
Given that the unit tests for Reducer.swift also mention `merging`, I'm assuming that the implementation is correct and that it is the documentation that needs to change. Given that the semantics of concatenating differ from those of merging, I think it is valuable to ensure the correct wording is used.
By the way - thank you for this great library. I recently used this on a small project, and despite being my first time using a unidirectional architecture I found it quite easy to incorporate.
=> Aligned documentation with the implementation

Examples/Todos/Todos/Todos.swift, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/Internal/EffectThrottleTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
Inspired by #185 we wanted to provide more customization for printing actions because sometimes we may want to only know the action being sent but not all of the associated values that were packaged into the action.
=> Specify action formatting when using `.debug`

Sources/ComposableArchitecture/Store.swift
Added a debug print of an action sent recursively to the store. Useful if the stacktrace is long or Xcode does not show the action in the debug-tooltip (nothing to do with this library, but a bug that happens to me quite frequently).
=> Print offending action on Store.send assertion

Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Effect.swift
This PR updates the `debug` higher-order reducer to use `merge` instead of `concatenate` in order to avoid a bug in the Combine framework.
It doesn't "fix" #194, but it does prevent a very common manifestation of the bug.
=> Merge debug reducer to avoid Combine leak

.github/workflows/ci.yml, .github/workflows/format.yml, Sources/ComposableArchitecture/ViewStore.swift
Combine's beta includes a new `assign(to:)` on publisher that can feed state updates to a `@Published` publisher. We don't want this, so let's ping `objectWillChange` directly.
https://developer.apple.com/documentation/combine/publisher/assign(to:)
=> Don't use @Published for ViewStore state

Sources/ComposableCoreLocation/Interface.swift, Sources/ComposableCoreLocation/Live.swift
In CoreLocation the location getter is optional and here it raise a fatal error.
https://developer.apple.com/documentation/corelocation/cllocationmanager/1423687-location
This PR make it optional.
=> Make location getter work like Corelocation.location getter

Sources/ComposableArchitecture/SwiftUI/Alert.swift
And a PR for the blog post — https://github.com/pointfreeco/pointfreeco/pull/673.
=> Fixes small `viewStore` ⇒ `self.store` typo in `AlertState`’s docs.

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-OptionalState.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-LoadThenPresent.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Examples/TicTacToe/Sources/Core/AppCore.swift, Examples/TicTacToe/Sources/Core/LoginCore.swift, Examples/TicTacToe/Sources/Core/NewGameCore.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer.swift
As [suggested in the forums](https://forums.swift.org/t/reducer-optional-assert-with-more-info/38281?u=alejandro_martinez) this PR adds #file and #line default parameters to an `optional()` reducer method to add the information into the assertion message.
Questions I would like to ask:
- Are you happy if the function replaces the property (breaking change) or do you want to keep both?
- Feel free to suggest edits on the wording of the message.
- What other places would you like to see this change? `forEach` maybe?
Once this is clarified I will update the examples and tests 😄
=> Added file and line to optional assert

Sources/ComposableArchitecture/Internal/Deprecations.swift
Thinking we can make these warnings errors since we've had a bunch of releases. All should be auto-fixable still.
=> Make deprecated interfaces unavailable

Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Pretty sure this fixes #216. 
I took the liberty of adding in the tests that @mbrandonw and @stephencelis added in [this branch](https://github.com/pointfreeco/swift-composable-architecture/compare/iflet) and they are now all passing 🎉 
FYI I got this working first in my ReactiveSwift port (not yet pushed) and then back ported it to here 😄 
cc: @fonkadelic
=> Fix issue with `ifLet` where `else` was being called too often

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift
As discussed in this [topic](https://forums.swift.org/t/animation-effect/38617) on the Swift Forums, it would be nice to have an Effect to handle animation keyframes like demonstrated in the animation case study. It makes implementing animations more ergonomic by avoiding duplication for each animation.
This PR shows how to implement such Effect in the case study rather than adding it to the core library.
=> Add keyFrames Effect in animations case study

Examples/TicTacToe/Sources/Core/AuthenticationClient.swift
The alert for authentication errors in the TicTacToe example displays messages like this:
```The operation couldn’t be completed. (AuthenticationClient.AuthenticationError error 0.)```
The alert should display the strings defined in `AuthenticationError.localizedDescription`, such as
```Unknown user or invalid password.```
`AuthenticationError` conforms to `Error`, and implements `localizedDescription`. But this property is not a protocol requirement for `Error`. It is added to `Error` via an extension, and is therefore not a customization point.
This PR modifies `AuthenticationError` to conform to `LocalizedError`, and implements `errorDescription` instead of `localizedDescription`. When the alert asks for `error.localizedDescription`, the default implementation will call through to …
=> Fix TicTacToe auth error localization

.github/workflows/ci.yml, Makefile, Sources/ComposableArchitecture/Effect.swift
This fixes a bug in iOS 13.2 when it comes to `fireAndForget` effects. Apparently they don't ever complete due to a bug in `Deferred` wrapping an `Empty`. So I've fixed that and added more CI coverage on older iOS versions.
=> Fix fireAndForget on iOS 13.2

.github/workflows/ci.yml, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/StoreTests.swift
As of the third beta, assign(to:) takes an `inout Publisher.Publisher`, so it no longer surfaces an escape hatch through which one could mutate a store's state.
Fixes #238.
=> Store can use @Published again

.github/workflows/ci.yml, Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
Xcode 12 beta 4 seems to have fixed all the problems we were seeing in beta 3, so we should be able to safely restore the old logic and we could maybe migrate to the new logic whenever we drop iOS 13 and macOS 10.15 support.
Also looks like GitHub already has beta 4 on its runners, so adding CI.
=> Restore original cancellation logic

README.md
This is something I noticed when using the code from the documentation:
There's also an option that the warning was left there intentionally, but I'll take my chance 😄
=> Fix warning when handling numberFactResponse action in documentation

README.md
I've seen folks ask about the acronym a couple times now, most recently in this thread: https://forums.swift.org/t/programatic-dismiss-navigation-animation-based-on-state-binding/39275/5
So might be nice to go all in by introducing it early since folks are using it anyway.
=> Lift TCA acronym out of folded FAQ?

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift
Good find from https://forums.swift.org/t/recursive-reducer-and-sending-actions-through-effects/39540
=> Fix Recursive Reducer

Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-LongLivingTests.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
Inspired by @mackoj's PR #263 we wanted to take a pass at making the error messaging better for when you get a test failure due to unfinished effects. We can now tell you what action started the uncompleted effect, which should help you track down what is going on:
=> Better error messages for uncompleted effects.

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-SharedStateTests.swift
This is a follow up to #260 - rather than removing something that I (erroneously) thought was unused, I've added tests to verify it's behaviour.
I attempted to write some other tests for the shared behaviour, for example by incrementing the counter, then asserting that the profile's `count` has the correct value, but was unable to test this because the setters for `ProfileState` are private. I had two ideas to address this:
1. Remove the private access modifier (but they may be there for some reason - ex. to further indicate that these should just "mirror" state from elsewhere rather than being changed directly)
2. Add a new type of Step that allows you to delegate to XCTAssert, similar to `do` but it would pass in the current state, allowing you to assert it's current values without …
=> Added some tests for Shared State case study.

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift, Examples/TicTacToe/Sources/Core/LoginCore.swift, Examples/TicTacToe/Sources/Core/TwoFactorCore.swift, Examples/TicTacToe/Sources/Views-UIKit/LoginViewController.swift, Examples/TicTacToe/Sources/Views-UIKit/TwoFactorViewController.swift, Examples/TicTacToe/Tests/LoginSwiftUITests.swift, Examples/TicTacToe/Tests/TwoFactorSwiftUITests.swift, Sources/ComposableArchitecture/Internal/LocalizedStringKey.swift, Sources/ComposableArchitecture/SwiftUI/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Tests/ComposableArchitectureTests/LocalizedStringKeyTests.swift
=> Localizable Alerts and Action Sheets

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Tests/ComposableArchitectureTests/IdentifiedArrayTests.swift
IdentifiedArray.reverse() just reverse the elements but doesn't reverse the `ids`.
=> Add reverse implementation in IdentifiedArray

Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Previously, test stores maintained similar logic to real stores, but we can take advantage of higher-order reducers and local mutable state to drive test stores with real stores under the hood.
Fixes #277.
=> Drive Test Store with a real Store

Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift
PR adds `throws` support to test store assertions, and attempts to show the raw string representations of data that doesn't diff.
=> Test Store Ergonomics

Examples/TicTacToe/Sources/Core/LoginCore.swift, Examples/TicTacToe/Sources/Core/TwoFactorCore.swift, Examples/TicTacToe/Tests/LoginCoreTests.swift
Addressing the good find reported in #289. Experiments with a fix that has the child 2FA module expose a "teardown cancel token" for its parent login module.
=> Fix Tic Tac Toe Optional Bug

Examples/Todos/Todos/Todos.swift
=> Update Todos app to run its forEach reducer first

Sources/ComposableCoreLocation/Live.swift
The start/stop heading methods were not implemented in the live core location manager. I added them!
=> Implement heading methods for core location library

Sources/ComposableArchitecture/ViewStore.swift
This PR fixes #325, where view store-derived bindings cannot be animated in `withAnimation` blocks. The behavior is as follows:
- If a binding has been made animatable via the `.animation` modifier, it will always favor this animation.
- If a binding is not animatable, it will animate when mutated in a `withAnimation` block.
- If a binding has been made animatable via the `.animation` modifier and is mutated in a `withAnimation` block, it will always favor the animation passed to the `.animation` modifier.
This is unfortunately the opposite behavior of bindings derived from Swift UI constructs like `@State`, where `withAnimation` can be used to override the `.animation` modifier. It does not seem possible to reproduce Swift UI's built-in behavior, though (filed feedback FB8965154), so …
=> Fix Binding animations

Sources/ComposableArchitecture/Reducer.swift
Replace deprecated `optional` with `optional()`
=> Replace deprecated optional with optional()

Sources/ComposableArchitecture/TestSupport/TestStore.swift
This broke a lil when we refactored the TestStore to use a real store under the hood.
=> Only include actions in TestStore debug output

Examples/README.md
Just removing these from the examples README 😄
=> Remove LocationManager and MotionManager examples from README

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-BindingBasicsTests.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
Some good feedback on naming here, so prepping this.
=> FormAction → BindingAction

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
This improves upon the issue brought up in #381 and active discussion of #382.
=> Improve performance of ForEachStore

Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
This is a sketch towards making the testing suite a touch more composable.
Common user-journey steps can be abstracted into a `Step.sequence` and can be vended by helper functions in the test.
example usage:
```swift
testStore.assert([
login2fa(),
enter2faCode(),
dismiss(),
])
```
where squirreled away elsewhere:
```swift
func login2fa() -> Step {
.sequence([
.send(.emailTextChanged) { ... },
.send(.passwordTextChanged) { ... },
.send(.loginButtonTapped) { ... },
])
}
```
=> Adds `StepType.sequence(Step)`

.github/workflows/ci.yml, Sources/ComposableArchitecture/TestSupport/TestStore.swift
Provides a nice ergonomic upgrade for debugging tests.
Before:
After:
=> Tie long-living effect assertions to line of originating action

Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift
1. The AppState example is missing a generic. Based on the context of the documentation, I filled in what I thought would be appropriate
2. The ForEachStore example was missing a colon and comma.
=> Addresses a couple of documentation issues for IdentifiedArray

Sources/ComposableArchitecture/SwiftUI/TextState.swift, Tests/ComposableArchitectureTests/DebugTests.swift
TextState currently dumps a lot of info when fed through TCA's debug output system. This shortens things up to make it more readable in tests.
=> TextState: DebugOutputConvertible

Sources/ComposableArchitecture/Effect.swift
We've experimented with this and it is a bit nicer to iterate on features without having to do the extra dance of ignoring output and failure all the time.
=> Add more permissive fire-and-forget effect

README.md
I think this is now obsolete. In fact we should probably migrate TicTacToe to use a Swift package, as we've done in isowords.
=> Remove SPM instructions

Sources/ComposableArchitecture/ViewStore.swift
Adding convenience initialiser for `ViewStore` when state is `Void`.
Rationale for change:
1. It simplifies the creation of `ViewStore` from `store.stateless` allowing for `ViewStore(store.stateless)`
2. It mirrors the available initialisers for `WithViewStore` SwiftUI helper view, so that you can both use `WithViewStore(store.stateless)` and `ViewStore(store.stateless)`
=> Convenience initialised for stateless ViewStore

Package.swift, Sources/ComposableArchitecture/TestSupport/FailingEffect.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift
Adds support for `Effect.failing` to improve unit test exhaustivity.
=> Failing Effects

README.md
Hello!
I've added korean translation version of Readme.md 🎉 
As the next step, I will translate [Part 1](https://www.pointfree.co/collections/composable-architecture/a-tour-of-the-composable-architecture/ep100-a-tour-of-the-composable-architecture-part-1) to [Part 4](https://www.pointfree.co/collections/composable-architecture/a-tour-of-the-composable-architecture/ep103-a-tour-of-the-composable-architecture-part-4)
=> Add korean version readme

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
Alternative fix for #469, #434.
=> Safely unwrap ForEachStore rows

Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift, Examples/CaseStudies/UIKitCaseStudies/Internal/ActivityIndicatorViewController.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Examples/TicTacToe/Sources/Views-UIKit/GameViewController.swift, Examples/TicTacToe/Sources/Views-UIKit/LoginViewController.swift, Examples/TicTacToe/Sources/Views-UIKit/TwoFactorViewController.swift
I noticed while playing around with the demos that the UIKit demos are setting the background color to `white`, which breaks some of the views in dark mode (the counter label ends up being white on a white background). Setting them to `systemBackground` fixes this.
I tested all of the views that I changed manually and they work in both light and dark mode now. #teamdarkmode
=> Fix background colors in UIKit demos to work in light and dark mode

Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift
Make it explicit in the documentation for `ifLet` that either the `else` or `unwrap` closure will be called based on the *initial* state of the optional state (`nil` or non-`nil`).
=> Clarify docs for UIKit `ifLet` function

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-OptionalState.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Examples/CaseStudies/UIKitCaseStudies/Internal/IfLetStoreController.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
We noticed this awhile back but must have forgotten about it.
=> Add @ViewBuilder to ForEachStore and IfLetStore

Sources/ComposableArchitecture/Effects/Timer.swift, Tests/ComposableArchitectureTests/TimerTests.swift
As discussed in [an issue](https://github.com/pointfreeco/swift-composable-architecture/discussions/532#discussioncomment-711916) *not* cancelling in flight timer with an existing ID is fairly unusual/unexpected behavior. This PR just sets the cancelInFlight parameter to true for the underlying timer effect.
=> Cancel in flight timers with the same id

Sources/ComposableArchitecture/SwiftUI/Presentation.swift
The project was not compiling for tvOS.
I fixed it by making the popover function unavailable for tvOS 👍
=> fix: compile tvOS

Sources/ComposableArchitecture/Internal/Breakpoint.swift, Sources/ComposableArchitecture/Reducer.swift
Currently, debug builds will crash when the breakpoint signal is raised. Since we consider these breakpoints to be non-fatal (and skip them in release mode), let's simply ignore them when a debugger isn't attached.
=> Only breakpoint when debugger is attached

Examples/TicTacToe/Sources/Core/AppCore.swift, Examples/TicTacToe/Sources/Views-SwiftUI/AppSwiftView.swift, Examples/TicTacToe/Sources/Views-UIKit/AppViewController.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
Uses the new `Reducer.pullback` that works with state case paths, and the new `SwitchStore` view.
=> Update Tic-Tac-Toe to use enum state

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Debouncing.swift, Sources/ComposableArchitecture/Effects/Timer.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/Identified.swift, Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/TextState.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/TestSupport/FailingEffect.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Sources/ComposableArchitecture/ViewStore.swift
This year, apple release [DocC with Xcode 13](https://developer.apple.com/videos/play/wwdc2021-10166). [DocC](https://developer.apple.com/documentation/docc) is new framework to generate documentation right inside Xcode.The generated documentation can be viewed from `Help > Developer Documentation(⌘⇧0)` or as webpage.
`symbol link` is a way to link certain type with wrapping it inside double backtick. on the generated document, it will become a link, and when pressed will redirect to respective page.
|without wrapper| with wrapper|
|---|---|
|![Screen Shot 2021-06-11 at 20 00 07](https://user-images.githubusercontent.com/16457495/121690155-ad64f000-caef-11eb-9abc-1ac264f19eac.jpg)|![Screen Shot 2021-06-11 at 19 59 41](https://user-images.githubusercontent.com/16457495/121690169-b2c23a80-ca …
=> Support DocC Xcode 13

Package.swift
**Describe the bug**
Xcode fails to resolve packages with:
```
invalidManifestFormat("/var/folders/mt/ywrj52cs19d30dw61wt2blyh0000gn/T/TemporaryFile.N1nYD8.swift:23:3: error: expected expression in list of expressions
],
^
/var/folders/mt/ywrj52cs19d30dw61wt2blyh0000gn/T/TemporaryFile.N1nYD8.swift:40:2: error: expected \']\' in container literal expression
)
^
/var/folders/mt/ywrj52cs19d30dw61wt2blyh0000gn/T/TemporaryFile.N1nYD8.swift:19:17: note: to match this opening \'[\'
dependencies: [
^
/var/folders/mt/ywrj52cs19d30dw61wt2blyh0000gn/T/TemporaryFile.N1nYD8.swift:24:12: error: extra argument \'targets\' in call
targets: [
^
/var/folders/mt/ywrj52cs19d30dw61wt2blyh0000gn/T/TemporaryFile.N1nYD8.swift:22:6: error: type \'String?\' has no member \'package\'
.package(url: …
```
=> Update Package.swift: Fix syntax error

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreTests.swift
We directly mutate store state when `send` is called, and additionally for each synchronous effect that may feed back into the reducer. This PR collapses all those mutations into a single one so that each `send` results in a single mutation. For SwiftUI this should result in identical behavior. For UIKit and any other manual subscription to a store, it should result in fewer emissions to contend with.
=> Coalesce synchronous effectful mutations to state

Sources/ComposableArchitecture/TestSupport/TestStore.swift
It occurred to me that this is only there for testing actions received by the store, and now that we have our simpler DSL steps for testing, we can test simple features without ever having to worry about conforming the action type to be equatable, or at the very least delay this requirement a bit longer.
=> Remove equatable constraint from TestStore.Action

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
Deprecating the `.binding` helper that takes a `CasePath` directly and adding a new one that only takes an extraction.
=> Don't use CasePath in .binding

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-BasicsTests.swift
Two small things I found while testing some of the new case path stuff:
* The web socket case study has an effect that needs to a `.recieve(on:)`
* The failing `FactClient` should be wrapped in `#if DEBUG`.
=> Fix websocket case study and FactClient.

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift
Relying on the array-based `ForEachStore` means potential crashes when SwiftUI evaluates views that it shouldn't. We always prefer using `IdentifiedArray`, so let's update this example accordingly.
=> Fix recursive case study

Sources/ComposableArchitecture/ViewStore.swift
I had an issue with a ComposableCollectionView, so that fix resolves the issue.
- `ComposableCollectionView` is a dataSource of self and it returns `store.items.count` from `numberOfItemsInSection` method
- `ComposableCollectionView` subscribes to `state.items.count` changes and updates itself
- After loading data, published `state.items.count` is equal to 10, but `viewStore.items.count` is 0
- So state update is received before the `ViewStore.state` acually changed
The fix is that `ViewStore.state` is taken directly from the `Store` now, so we don't even have to assign a new `Store.state` to the `ViewStore.state` anymore, but instead of this we should send `ViewStore.objectWillChange` event from the subscription
=> Change ViewStore state update behavior

Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
A more elegant fix to problem in #496 suggested by @stephencelis in #665.
When using IfLetStore, an action from scoped child store to nil out local state might result in local state being replayed back to earlier value right before the view is removed. The issue can be seen in
https://github.com/pointfreeco/swift-composable-architecture/blob/ba2b9e08e2776bbb02f27ab7123dae767f106fad/Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift#L50-L54
where initial state is copied and used later when the scope transformation returns nil.
This solution ensures that the last nil-value sent to the store will play back the last seen non-nil value.
=> Fix IfLetStore so that it does not replay first seen state on nil-value

Sources/ComposableArchitecture/Effects/Throttling.swift, Tests/ComposableArchitectureTests/EffectThrottleTests.swift
The `Effect.throttle` operator had multiple data races when updating `throttleTimes` and `throttleValues` shared state, because:
1. `Effect.throttle` can be called from any scheduler.
2. The internal `flatMap` runs on the current chain scheduler, but the
throttled (delayed) value runs on the passed in `scheduler` parameter
(which can be different).
By protecting shared state with a lock (similar to the cancellables'), these data races should be addressed.
Additionally, the `Effect.throttle` should return all values in the `scheduler` passed in, so that the API contract is honored and values come from where callers expect them to.
- Add new `throttleLock` `recursive lock to protect `throttleTimes` and `throttleValues` shared state in `Effect.throttle` operator.
- Ensure all values in …
=> Fix `Effect.throttle` data races and scheduler value return

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift
This eliminates a helper introduced in #667 by inlining the state, and it fixes `ForEachStore` using the same logic.
=> Keep last non-nil value around for ForEachStore

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Refreshable.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-RefreshableTests.swift, Sources/ComposableArchitecture/Beta/Concurrency.swift, Sources/ComposableArchitecture/Experimental/Concurrency.swift
Based on the work in the [most recent](https://www.pointfree.co/episodes/ep154-async-refreshable-composable-architecture) Point-Free episode, we are introducing _beta_ support for an async/await aware `.send` method. This API could change in the future with future Xcode betas, so use with caution 🙂.
This method allows you to send an action into the store and the suspend while some piece of boolean state is `true`. This can be particularly handy for interfacing with SwiftUI's new `.refreshable` API:
```swift
.refreshable { 
await viewStore.send(.pulledToRefresh, while: \.isLoading)
}
```
=> Add an async/await aware .send method to View Store.

.github/workflows/format.yml, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Refreshable.swift
Ha looks like @allevato was preparing a branch at the same time we were looking at this yesterday: https://forums.swift.org/t/support-for-swift-format-on-xcode-beta-13-0b1/50205/3
The GitHub action on the previous commit was successful (other than the final commit to the `main` branch), so this should be good to merge!
=> Update swift-format for Swift 5.5

Sources/ComposableArchitecture/Effects/Throttling.swift, Tests/ComposableArchitectureTests/EffectThrottleTests.swift
Effect.throttle didn't clean up `throttleValues` shared state on the delayed values path, leading the first value strategy (`latest: false`) to return incorrect (old) values on some scenarios.
Opened as separate PR following discussion on #678. 
- Add missing `throttleValues[id]` clean up in `Effect.throttle` delayed value path.
=> Fix `Effect.throttle` delayed value shared state cleanup

Sources/ComposableArchitecture/Effect.swift
macOS 11.0 introduced an overload of Publisher.flatMap(maxPublishers:_:)
for when the failure type is Never, documented here:
https://developer.apple.com/documentation/combine/publisher/flatmap(maxpublishers:_:)-qxf
This causes a compiler error in Effect.fireAndForget when the minimum
deployment target is 11.0 or later:
Sources/ComposableArchitecture/Effect.swift:364:7: error: ambiguous use of 'flatMap(maxPublishers:_:)'
self
^
Combine.Publisher:3:17: note: found this candidate
public func flatMap<T, P>(maxPublishers: Subscribers.Demand = .unlimited, _ transform: @escaping (Self.Output) -> P) -> Publishers.FlatMap<P, Self> where T == P.Output, P : Publisher, Self.Failure == P.Failure
^
Combine.Publisher:3:17: note: found this candidate
public func flatMap<P>(maxPublishers: …
=> Fix build error when minimum target is macOS 11.0

.github/workflows/ci.yml, Tests/ComposableArchitectureTests/ViewStoreTests.swift
I think the runners have gotten more reliable (we use it for swift-format), so let's start running CI against macOS 11 and Xcode 13.
=> Also run CI on Big Sur

Sources/ComposableArchitecture/ViewStore.swift
In #689 @p4checo brings up the fact that the view store documentation says it should only be interacted with on the main thread, when this isn't _quite_ the full story. Here's an idea for clarifying that.
=> Clarify view store thread safety

Sources/ComposableArchitecture/ViewStore.swift
#698 brought up some interesting points that make it clear we need to flesh out the docs for `viewStore.publisher`.
=> Add some docs about ViewStore publisher.

Tests/ComposableArchitectureTests/DebugTests.swift
We can delete this once we release the new stuff.
=> Don't run testNestedDump on beta.

Sources/ComposableArchitecture/Effect.swift, Tests/ComposableArchitectureTests/EffectTests.swift
This PR adds a `catchToEffect<T>(_ f: @escaping (Result<Output,Failure>) -> T)` which basically is a `catchToEffect` followed by a map function:
given:
```swift
enum StateAction {
case opSuccess(OpValue)
case opFailure(Error)
}
```
then you can do this:
```swift
case .doSomething:
return env.doingSomething()
.catchToEffect {
switch $0 {
case let .success(value):
return .opSuccess(value)
case let .failure(error):
return .opFailure(error)
}
}
```
Since `catchToEffect()` with map is (usually?) used to map result to state actions, there is a place for a shorter operator that accepts action enum cases with associated values that map directly to `Output` and `Failure` types:
```swift
...
case .doSomething:
return env.doingSomething()
.catchToEffect(StateAction.opSuccess, StateAction.opFailure) …
```
=> Add `catchToEffect()` with mapping function

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
I think we only support Xcode 12+ these days, which means we can use `#fileID` in our debug helpers.
=> Convert #file to #fileID for debug purposes

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Tests/ComposableArchitectureTests/WithViewStoreAppTest.swift
This makes a few improvements to `WithViewStore.debug()`:
- Shows a state diff alongside the existing console emission. The diff should hopefully help folks see when a view is observing too much state.
- Improves the formatting of the `State` and `Action` generics to include any types they may be nested in.
- Adds `file`/`line` number for additional context.
As an example, when added to Tic-Tac-Toe's `LoginView`:
```
WithViewStore<LoginView.ViewState, LoginView.ViewAction, _>@LoginSwiftUI/LoginView.swift:44 (Initial state)
ViewState(
alert: nil,
email: "",
isActivityIndicatorVisible: false,
isFormDisabled: false,
isLoginButtonDisabled: true,
password: "",
isTwoFactorActive: false
)
WithViewStore<LoginView.ViewState, LoginView.ViewAction, _>@LoginSwiftUI/LoginView.swift:44 (Changed state) …
```
=> WithViewStore debug state diffs

Sources/ComposableArchitecture/Beta/Concurrency.swift
Capture lists don't work by reference for value types, so we weren't handling cancellation here.
=> Fix cancellation of ViewStore.suspend

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
The warning was:
Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift:141:28: warning: redundant conformance constraint 'EachContent' : 'View'
public init<EachContent: View>(
^
Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift:146:16: note: conformance constraint 'EachContent' : 'View' implied here
EachContent: View,
^
I fixed the warning by removing the redundant constraint from the type
parameter.
=> Fix a redundant conformance constraint warning in ForEachStore

Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/EffectDebounceTests.swift, Tests/ComposableArchitectureTests/EffectDeferredTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/EffectThrottleTests.swift, Tests/ComposableArchitectureTests/MemoryManagementTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TimerTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
Seems like we should always prefer it when it's available?
=> Update tests to use `XCTAssertNoDifference`

Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift
Forgot to make this change when we introduced customizable diff formats.
=> Use proportional diffing for TestStore failures

Sources/ComposableArchitecture/Store.swift
Any async Effect (including fireAndForget) could result in a runtime crash when updating internal state like `effectCancellables`
This adds a debug warning to let users know
=> Add threading warning to Store.send

Sources/ComposableArchitecture/Internal/Deprecations.swift
Have had some confusion about upgrade paths, so let's improve the warnings with some examples.
=> Improve deprecation warnings for old binding helpers

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/DebugTests.swift
=> Update to thread warnings.

Sources/ComposableArchitecture/Store.swift
I don't know why I had this as a `var`, but it should be a `let`.
=> Change initialThread to a let.

Sources/ComposableArchitecture/SwiftUI/Binding.swift
This ensures that bindable state properties are displayed in a useful way when using `.dump` snapshot tests on your app state.
Fixes #776
=> Conform BindableState to CustomDebugStringConvertible

Sources/ComposableArchitecture/SwiftUI/Binding.swift
[This forum post](https://forums.swift.org/t/propery-wrapper-decoding-difference-between-singlevaluecontainer-and-init-from-decoder/51918) reminded me that we had to work around a bug in Tagged:
https://github.com/pointfreeco/swift-tagged/blob/73f93e1fb534b88ba467ae90f8730167e804a32d/Sources/Tagged/Tagged.swift#L67-L75
I'm not sure if there's a bug filed for this behavior or not.
=> Fix "BindableState: Codable" strategies

Sources/ComposableArchitecture/TestSupport/FailingEffect.swift
Deletes unnecessary preprocessor macros around `Effect.failing`, obsoleted when `XCTFail` got a Release build stub in XCTDynamicOverlay.
It'll also help resolve [related issue in Composable-Core-Location package](https://github.com/pointfreeco/composable-core-location/issues/14)
=> Remove #if DEBUG/#endif surrounding `Effect.failing`

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift
I was playing around with `.publisherScope` and noticed you might be able to shorten `Store.ifLet`. The tests pass but I don't really know the implications of this change.
=> Clean up `Store.ifLet`

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindingTests.swift
Fixes #809.
In #765, we introduced a safer, conciser way of deriving SwiftUI bindings from view stores by leveraging dynamic member lookup:
```swift
// before:
viewStore.binding(keyPath: \.displayName, action: SettingsAction.binding)
// after:
viewStore.$displayName
```
This syntax worked great for the most part, but it unfortunately broke the ability to layer additional reducer logic on mutations to a particular nested field:
```swift
// Only associates the '.$userSettings' portion of the key path with the action sent to the reducer.
TextField("Display name", text: viewStore.$userSettings.displayName)
// reducer
case .binding(\.$userSettings.displayName): // 😳 Never matches!
// some additional logic here
```
This PR deprecates the super-concise syntax for something that's still concise, …
=> Deprecate dynamic member lookup on view stores in favor of ViewStore.binding

Sources/ComposableArchitecture/Internal/Create.swift, Sources/ComposableArchitecture/Internal/CurrentValueRelay.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
This is a proof of concept as a way to provide consistent ordering for StorePublisher subscribers (discussed in #698). @mbrandonw mentioned:
> It would be great if it could be fixed at the library level
so I thought I'd give it a try. Pretty sure it will need to be made thread safe and have some extensive tests/benchmarks added.
I can see the benefits of sticking with CurrentValueSubject and I haven't thoroughly tested this... just checking to see if it's something worth exploring further. I used [CombineExt/CurrentValueRelay](https://github.com/CombineCommunity/CombineExt/blob/main/Sources/Relays/CurrentValueRelay.swift) as a starting point.
=> Alternative to `CurrentValueSubject` in `ViewStore`

.github/workflows/ci.yml, Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-BindingBasicsTests.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift
The most recent release broke support for Xcode 12.4, which we didn't have in CI. This restores it, and should hopefully address the issues that came up in #813.
=> Fix bindable deprecations

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
While debugging something I realized that `ViewStore.debug` was printing too much to the console.
=> Don't print to console when dumping state for ViewStore.debug

Sources/ComposableArchitecture/SwiftUI/Binding.swift
Noticed a small typo where the action enum case was missing a closing parentheses. :P
=> Fix typo in `BindingAction.pullback(_:)` docs

Examples/TicTacToe/App/RootView.swift
The tic-tac-toe example double prints all the actions. This is because .debug is applied twice to the appReducer. Once in RootView.swift and once in AppCore.swift. This PR removes it from RootView.swift.
=> Remove duplicate debug

Sources/ComposableArchitecture/SwiftUI/TextState.swift
The `accessibilityLabel` modifier does not work all that well with the `TextState` as there's a different return type for iOS 14 and iOS 15. The former is defined as an extension on `ModifiedContent` while latter on `Text`. With that in mind, it makes sense to support the more recent modifiers.
I currently managed to build this only for iOS. For macOS the compiler complains about wrong return type `ModifiedContent<...>`. The source code designates  `@available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)` so it should in theory work.
TODO:
=> ✨ Add support for accessibility modifiers on TextState

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift
There is a `.resetButtonTapped` action which indicates that a reset method should exist, but it is not there yet.
This pull request adds a reset button to the view and it sends the `.resetButtonTapped` to trigger a reset.
=> Add reset button to form binding case

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
We've had an improved DSL for awhile now. It's time to deprecate the old API.
=> Deprecate `TestStore.assert`

Package.swift
Several dependencies we have specified at old, less-performant versions, some of which do not always compile (swift-custom-dump `< 0.3.0` does not compile in Xcode 13.2's new build system).
Let's force some updates, which should be a safe, non-breaking change.
=> Bump Dependencies

Sources/ComposableArchitecture/TestSupport/TestStore.swift
Very small bit of cleanup. We're doing some acrobatics that aren't necessary in the test store.
=> Don't use Store.scope or ViewStore.send in TestStore

Sources/ComposableArchitecture/Effects/Concurrency.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
Libraries like NIO and GRDB are [avoiding this duplication](https://forums.swift.org/t/supporting-concurrency-in-a-library/54095/3), so we may as well, too.
=> Limit async/await to Swift 5.5.2 (Xcode 13.2)

Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift
Took a bunch of experimentation to figure out something that fixes #928, but this appears to work!
=> Fix iOS 14 alert/confirmationDialog runtime crash

Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
Possible fix for #946 
Main issue with `PassthroughSubject` is that it could only forward 1 value from an upstream `PassthroughSubject`, ie. nested cancellable effects. This should fix that by subscribing directly to the upstream publisher.
=> Update `.cancellable` implementation to fix #946

Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift
Hi!
I love this new runtime warning feature, however I think there's a better way to get SwiftUI image handle than hardcode a SwiftUI symbol name. In this PR, I iterate over dyld images and search SwiftUI directly. I think this approach is more straightforward.
=> Improved way to get SwiftUI image handle

Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift, Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift
Hi there!
Noticed that the UIKitCaseStudies' List example had a small problem with `countLabel` of `CounterViewController`.
It wasn't updating accordingly when incrementing/decrementing.
This PR fixes it.
=> Fix UIKitCaseStudies' List example

Sources/ComposableArchitecture/Effects/Cancellation.swift
This PR should fix #993 which was introduced by #949.
It looks like `PrefixUntilOutput` might keep the output publisher alive until receiving a completion. This is something I overlooked.
=> Fix memory leak caused by `Effect.cancellable`

Examples/Todos/Todos/Todos.swift, Examples/Todos/TodosTests/TodosTests.swift
Fixed a bug in Todos example app where moving items returns the wrong todos indices if the completed filter is enabled
> The issue is happening because the `source` and `destination` are captured from the `filteredTodos` array while the move operation is happening in the original `todos` array
[before]: https://user-images.githubusercontent.com/8127757/152877651-fbfecfc6-0c20-4cbd-b31c-341b96f07be9.gif
[after]: https://user-images.githubusercontent.com/8127757/152877638-78e43d4a-4e8b-4bc6-950d-d67e30337554.gif
| Before | After |
|-|-|
| ![Before][before] | ![After][after] |
=> Fix edit while filtered bug in todos example app

Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
This PR disfavors the variadic cancellation to prevent a sequence of ids from being treated as a single cancellation id eg: 
```swift
case let .delete(ids):
for id in ids {
state.rows.remove(id: id)
}
return .cancel(ids: ids) // currently treated as AnyHashable(ids) instead of [AnyHashable]
```
It also changes the array parameter to a sequence to prevent the same issue for occurring with sub sequences.
=> `Effect.cancel(ids:)` prefer sequence of ids over variadic list.

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Timers.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ElmLikeSubscriptions.swift, Examples/TicTacToe/tic-tac-toe/Sources/GameSwiftUI/GameView.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/ViewStore.swift
This PR follows the discussion #1012 and implements the solution proposed by @iampatbrown.
I've reordered the "Animations" case from `CaseStudies`, and it indeed fixes the issue with `GeometryReader`. 
It also seems to solve the `Stepper` issues! I'll check with `ScrollViewReader` later.
I'll hunt other uses and mentions in the documentation in a second step if the implementation is greenlighted.
I've used `newInstance()` instead of `copy()` because the latter could suggest that both instances would behave separately once generated. This is of course open to discussion.
Please let me know what you think!
=> Fix `WithViewStore` issues with `View`s using escaping closures

Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
Makes it so runtime warnings invoke `XCTFail` during tests.
=> Runtime Warning Finesse

Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift
Allows runtime warning to appear at call site
=> Add transparent attribute to runtimeWarning

Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift
Apparently Xcode orders multiple XCTest failures on the same line alphabetically, which means that the messages can sometimes show up in a counterintuitive order. A slight change of the message makes for a better order.
Also added a test to make sure that cancelling `Effect.task` works as we expect.
=> Update failure message for better order.

Package.swift
The latest release of swift-case-paths fixes an [issue](https://github.com/pointfreeco/swift-case-paths/issues/63)
that can lead to crashes when using TCA. This commit upgrades the version to include the fix.
=> Upgrade swift-case-paths to 0.8.0

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
As discussed in #1009
Making this a draft so I can add more information tomorrow. Ran out of time. 
I had a quick look on GitHub and only found a couple of projects using the variadic overload.
=> Effect.cancel(ids:) prefer array of ids and deprecate variadic overload

Sources/ComposableArchitecture/Effect.swift
I'm wondering if there's appetite for this sort of change? I find myself needing to map after erasing to an effect (similar to how catching to an effect also usually needs a map), since many of my dependencies' publishers don't return effects of ready-to-use actions. A convenience operator that combines `eraseToEffect` and `map` as I've implemented would be useful to have, and I bet other users of TCA would benefit as well. If it's not a big enough benefit to include in the core library, no big deal though!
=> Add a map-style overload to eraseToEffect

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift
> echo.websocket.org was shut down sometime in 2021 when the company was acquired and changed their name. Try going to [www.websocket.org](http://www.websocket.org/) and you'll see the service is not longer available.
>
> https://stackoverflow.com/a/70438302
I replaced `wss://echo.websocket.org` with `wss://echo.websocket.events` (which is provided by the answerer of the link above) since the `.org` one is no longer available.
=> Fix invalid web socket server URL

Sources/ComposableArchitecture/Effects/Cancellation.swift
Our current recommendation of using a dedicated type for effect cancel tokens unfortunately leads to the equivalent of a linear search due to Swift's default hashing behavior:
```swift
struct A: Hashable {}
struct B: Hashable {}
A().hashValue == B().hashValue // true
```
This PR introduces an internal wrapper type that includes the type's unique identifier in the hashing logic, which should improve the hashing of these identifiers:
```swift
struct CancelToken: Hashable {
let id: AnyHashable
let discriminator: ObjectIdentifier
init(id: AnyHashable) {
self.id = id
self.discriminator = ObjectIdentifier(type(of: id.base))
}
}
CancelToken(id: A()).hashValue == CancelToken(id: A()).hashValue // true
CancelToken(id: B()).hashValue == CancelToken(id: B()).hashValue // true
CancelToken(id: …
```
=> Improve performance of type-safe effect cancel token lookup

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Refreshable.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Timers.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Lists-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-LoadThenNavigate.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-LoadThenPresent.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-Sheet-PresentAndLoad.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Lifecycle.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift, Examples/Search/Search/SearchView.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginCore/LoginCore.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorCore/TwoFactorCore.swift, Examples/Todos/Todos/Todos.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Debouncing.swift, Sources/ComposableArchitecture/Effects/Timer.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift
While it's easy enough to create instances of hashable structs for cancel tokens, it's effectively using static info under the hood (more so as of #1077). So let's consider adding overloads that take `Any.Type` instead. In use:
```diff
-struct CancelId: Hashable {}
-return .cancel(id: CancelId())
+enum CancelId {}
+return .cancel(id: CancelId.self)
```
=> Add cancel overloads that take types

Sources/ComposableArchitecture/Effect.swift, Tests/ComposableArchitectureTests/EffectTests.swift
This has come up before (#868), and we think it will be useful, especially with some new features coming soon to TCA that make it play nicer with Swift's concurrency tools.
=> Async fire-and-forget

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-LongLivingTests.swift
We have a few case studies that could probably be polished up a bit, and this is one that stood out to me. Seems nicer to use a Notification Center directly in the reducer instead of control it with a wrapper effect.
=> Modernize case study using Notification Center

Sources/ComposableArchitecture/Effects/Throttling.swift, Tests/ComposableArchitectureTests/EffectThrottleTests.swift
Given that Effect cancellation now has endpoints that can take types as identifiers and those were extended to debounce, it seems natural to expose the same functionality for throttle.
=> Add throttle overloads that take types

Examples/TicTacToe/App/RootView.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginSwiftUI/LoginView.swift, Examples/TicTacToe/tic-tac-toe/Sources/NewGameSwiftUI/NewGameView.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorSwiftUI/TwoFactorView.swift
Apparently there is a bug in SwiftUI that causes "AttributeGraph: cycle detected" to be printed to the console if you disable a textfield while it is focused. This doesn't have anything to do with TCA and exists in simple vanilla SwiftUI apps too.
The fix is to force all fields to unfocus before sending actions that could disable UI components.
This has come up a number of times (#363, #395, and more recently in #1111). This fix was introduced to us by @mywristbands in #363 ([SO article](https://stackoverflow.com/a/69653555)) but we didn't see it when it was originally posted. Thanks for the tip!
We also brought back `Form` views which were previously removed (#448) due to other SwiftUI bugs. It seems those bugs have been fixed because I can no longer reproduce the crash reported in #395.
=> Fix for attribute cycle in tic-tac-toe.

Sources/ComposableArchitecture/Effects/Concurrency.swift
This should fix #1130, but it's also something we will be doing in our upcoming TCA concurrency updates, so might as well get a little bit of this in now.
Effectively this means that one no longer needs to do `Effect.task { @MainActor ... }` if using this API inside a reducer. It will be done automatically for you, and you don't even need `.receive(on: ...)`.
_However_, we still do [not recommend](https://github.com/pointfreeco/swift-composable-architecture/blob/bd919feddb51e08e66fdb89ca92588de1f38c710/Sources/ComposableArchitecture/Effects/Concurrency.swift#L23-L30) using `Effect.task` directly in a reducer unless you are willing to deal with the annoyances that come with it when testing. In particular, you either need to add some super short expectations in order to allow the task to do …
=> Force effect tasks to be on @MainActor.

Sources/ComposableArchitecture/Effects/Animation.swift, Sources/ComposableArchitecture/TestSupport/TestStore.swift
This was brought up a long time ago by @mayoff in the Swift [forums](https://forums.swift.org/t/an-alternative-take-on-animating-asynchronous-effects/45000), but at the time we didn't think it was necessary since scheduler animations seemed to cover all its use cases. However, with some of the concurrency updates we will be bringing to the library soon this kind of operator is going to be handy when used with `Effect.task`.
=> Add animation operator to Effect.

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift
This is the only obvious problem I could find in the library when running in Xcode 14. I'm not exactly sure what the problem is but it seems we can't fulfill this expectation on a non-main thread?
=> Fix tests in Xcode 14.

Sources/ComposableArchitecture/Internal/Deprecations.swift
The new exhaustive check around state changes was not backported, so some tests could start to fail when upgrading TCA.
@vermont42 discovered this when running the tests from our intro series of episodes: https://github.com/pointfreeco/episode-code-samples/issues/118
=> Fix deprecated "TestStore.assert" APIs

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/DebugTests.swift
#1162 points out that the warning can appear at inopportune times, like in tests. We should push the warning to the view layer, instead.
=> Only warn for unused binding actions sent from view stores

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Refreshable.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-BindingBasicsTests.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift
The library requires Swift 5.5 because we have a bunch of compiler checks for 5.4 and 5.5. This PR removes all of those checks.
The diff is best viewed with whitespace off.
=> Clean up compiler checks.

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-SystemEnvironment.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-BasicsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Examples/Search/Search/WeatherClient.swift, Examples/Search/SearchTests/SearchTests.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Failing.swift, Examples/SpeechRecognition/SpeechRecognitionTests/SpeechRecognitionTests.swift, Examples/TicTacToe/tic-tac-toe/Sources/AuthenticationClient/AuthenticationClient.swift, Examples/TicTacToe/tic-tac-toe/Tests/AppCoreTests/AppCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginCoreTests/LoginCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginSwiftUITests/LoginSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorCoreTests/TwoFactorCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorSwiftUITests/TwoFactorSwiftUITests.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/FailingAudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/FailingAudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Package.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/TestSupport/UnimplementedEffect.swift, Tests/ComposableArchitectureTests/EffectTests.swift
We've found that the "failing" naming of dependencies can be confusing. While it's accurate in isolation, when you're writing tests, "failure" is already a loaded term. We'd like to move in the direction of the "unimplemented" terminology (which is funnily enough where we started, when we had some preexisting dependencies that would `fatalError`).
This PR:
- Renames `Effect.failing` to `Effect.unimplemented`, soft-deprecating `Effect.failing` in the process. We can warn in a future version.
- Uses `XCTUnimplemented` and `UnimplementedScheduler` in examples
=> "Failing" -> "Unimplemented"

ComposableArchitecture.xcworkspace/contents.xcworkspacedata, Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftUI.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftUIDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Articles/UIKit.md, Sources/ComposableArchitecture/Documentation.docc/ComposableArchitecture.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/EffectDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Reducer.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Store.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/StoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwitchStore.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ViewStore.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ViewStoreDeprecations.md, Sources/ComposableArchitecture/SwiftUI/Binding.swift
This PR takes a first stab at introducing some structure to TCA's documentation. It's minimal organization for a better Table of Contents experience:
It does its best to hide away deprecated APIs and surface most import APIs first and in a progressive manner. We have a lot more to do, but it's a start!
=> DocC Structure

Tests/ComposableArchitectureTests/ReducerTests.swift
We have a few flakey tests that occasionally fail on CI due to expectation timeouts. We've seen that some failures take awhile for XCTest to process, so let's see if bumping this will help...
=> Bump timeout on flakey tests

Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift
Solution #1193 was probably not correct (though probably helps in its own right). I think `.background` priority, especially on a CI box, made scheduling of this logging easy to miss.
=> Another flakey test fix

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AnimationsTests.swift
Hi, thank you making this cool library.
While studying [SwiftUI Case Studies], I found a couple things to suggest.
I made 2 commits:
- https://github.com/pointfreeco/swift-composable-architecture/commit/aabc8299db91935e527a5653beb168a869f79c7c
- remove two unnecessary `nil` literals in `AnimationsState` and `FocusDemoState`
- https://github.com/pointfreeco/swift-composable-architecture/commit/9668ac5ee0d446134d18de781ada9014bd60c6a6
- In 01-GettingStarted-Animations.swift
- move Circle's initial location to center of the screen for better visibility.
- align 'circleColor' property's value with actual color using `colorInvert()` so that rainbow keyFrames colors match the circle's actual color, not inverted.
```swift
case .rainbowButtonTapped:
return .keyFrames(
values: [Color.red, .blue, …
```
=> [SwiftUI Case Studies] Revise initialState and layout in Animations

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AnimationsTests.swift
Backports the cancellation logic from #1189 and writes a test.
=> Small updates to animations case study.

Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognitionApp.swift
The Speech framework doesn't work in previews, so this introduces a little "lorem" client that just spits out some lorem ipsum at a rate of 3 words / second.
=> Use a 'lorem' speech client in previews.

README.md
"Other versions" in README is not marked up.
↓
Can be fixed by inserting a blank line after  `</summary>`.
=> Fixed broken other versions in README

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift
Hi, I found that some enum `Action` cases have different names compared to most others.
It would be nice to rename those for naming consistency.
```diff
// "dismissed" should be placed at the end of the case name.
- case dismissAlert
+ case alertDismissed
- case dismissAuthorizationStateAlert
+ case authorizationStateAlertDismissed
// also rename enum for cancellable id, like the others.
- enum CancelID {}
+ enum CancelId {}
```
Tests of the changed files have all passed.
Please let me know what you think. Thanks! 😃
=> Rename enum Action cases to be consistent

Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
Not quite sure why this fails intermittently, but it's coverage we can spare.
=> Don't run flakey test on CI

Examples/Todos/Todos/Todos.swift, Examples/Todos/Todos/TodosApp.swift
Slightly more code, but uses simple Swift concurrency instead of relying on an operator.
=> Clean up Todos sort debouncing

Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift
The audio player and recorder functionality for the voice memos demo doesn't actually work in previews, but also the mocks we are using don't show off the true functionality of the feature. This puts in more interesting mocks so that you can actually play around with the feature as if it were running real, live dependencies.
=> Voice memos dependency previews

Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AlertsAndConfirmationDialogsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AnimationsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-BindingBasicsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-SharedStateTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-BasicsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-CancellationTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-LongLivingTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-RefreshableTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-TimersTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-LifecycleTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableFavoritingTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Examples/CaseStudies/tvOSCaseStudiesTests/tvOSCaseStudiesTests.swift, Examples/Search/SearchTests/SearchTests.swift, Examples/SpeechRecognition/SpeechRecognitionTests/SpeechRecognitionTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/AppCoreTests/AppCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/GameCoreTests/GameCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/GameSwiftUITests/GameSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginCoreTests/LoginCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginSwiftUITests/LoginSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/NewGameCoreTests/NewGameCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/NewGameSwiftUITests/NewGameSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorCoreTests/TwoFactorCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorSwiftUITests/TwoFactorSwiftUITests.swift, Examples/Todos/TodosTests/TodosTests.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Tests/ComposableArchitectureTests/TaskResultTests.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Hi everyone!
In my opinion, the test class (which inherits from the [XCTestCase](https://developer.apple.com/documentation/xctest/xctestcase) class) doesn't need to be overridden.
And I found that some test classes already have `final`, but some don't.
So I want to add `final` keyword to every test class by default.
Please comment if there are cases where it should not be `final class` intentionally, or if you have other opinions.
Thanks!
(ref.) Airbnb Swift Style Guide - [Default classes to `final`.](https://github.com/airbnb/swift#final-classes-by-default)
=> Add `final` keyword to every test class by default

Examples/VoiceMemos/VoiceMemos/RecordingMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemosApp.swift, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Identified.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/ViewStore.swift
We use "Global" and "Local" to describe transformations between domains, but it can be confusing because "global" doesn't feel very relative without a "more [global]" qualifying it. Let's instead adopt more relative terminology. For the most part this means global-local becomes parent-child, and in other cases I've updated the terminology to be more domain-specific.
Also snuck a few small cleanup fixes in this PR.
=> Cleanup: Global/Local -> Parent/Child

Sources/ComposableArchitecture/Effects/Cancellation.swift
Fixes a concurrency warning in Cancellation.swift. There's a lot more work to do in this file before it's ready for Swift 6, but this was an easy one.
=> Require sendable cancel ID.

Examples/SpeechRecognition/SpeechRecognition.xcodeproj/project.pbxproj, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Client.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Live.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Lorem.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/VoiceMemos/VoiceMemos.xcodeproj/project.pbxproj, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/AudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/LiveAudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/MockAudioPlayer.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/AudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/LiveAudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/MockAudioRecorder.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/Dependencies/Dependencies/Calendar.swift, Sources/Dependencies/Dependencies/Date.swift, Sources/Dependencies/Dependencies/Locale.swift, Sources/Dependencies/Dependencies/TimeZone.swift, Sources/Dependencies/DependencyKey.swift, Sources/Dependencies/DependencyValues.swift
Based on a [conversation](https://github.com/pointfreeco/swift-composable-architecture/discussions/1282#discussioncomment-3449849) in #1282, we now allow people to also supply a `previewValue` when conforming to `DependencyKey` which will be used in Xcode previews only. If no `previewValue` is provided it will default to the `testValue`.
I also fixed some errors that prevented TCA from compiling in Xcode 13. This is for the core library only. The case studies and some demo apps will only compile on Xcode 14 since we want to only show the most modern way of interacting with the library in those projects.
=> Add previewValue to DependencyKey, and fixed build errors on Xcode 13.

Sources/Dependencies/Dependencies/Date.swift
Inspired by @Jeehut's https://github.com/pointfreeco/swift-composable-architecture/discussions/1282#discussioncomment-3456006, this PR adds a convenience `now` property to the date generator dependency.
This means you can use the friendlier, more modern `now` verbiage in your features and tests:
```swift
// In your reducer type:
@Dependency(\.date.now) var now
// In your reducer method/body:
self.now  // Date
// In your tests:
store.dependencies.date.now = Date(timeIntervalSince1970: 0)
```
=> Add `now` convenience property to date dependency

Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Package.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Throttling.swift
We just made a [fix](https://github.com/pointfreeco/combine-schedulers/commit/9e42b4b0453da417a44daa17174103e7d1c5be07) to combine-schedulers that was breaking DocC builds from Xcode since beta 4. But, that exposed a few spots we were implicitly using that Foundation import, so let's make things more explicit.
=> Update combine-schedulers and fix implicit Foundation imports.

Sources/swift-composable-architecture-benchmark/Common.swift, Sources/swift-composable-architecture-benchmark/Effects.swift, Sources/swift-composable-architecture-benchmark/main.swift
Let's get a simple baseline benchmark in place for merging effects, which is a common operation baked into composing reducers.
=> Add benchmark for effect merging

Sources/ComposableArchitecture/Effect.swift
It can be useful to explicitly create `Send` types when building helpers that call `Effect.run` under the hood, but the lack of `@MainActor` on the closure prevents it from being invoked without a Swift 6 warning. This fixes the warning.
=> `Send` should explicitly wrap `@MainActor` closure

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadClient.swift, Examples/CaseStudies/SwiftUICaseStudies/CaseStudiesApp.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Examples/Search/Search/SearchApp.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognitionApp.swift, Examples/TicTacToe/App/RootView.swift, Examples/TicTacToe/tic-tac-toe/Sources/AppCore/AppCore.swift, Examples/Todos/Todos/TodosApp.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemosApp.swift, Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift, Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Animation.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Debouncing.swift, Sources/ComposableArchitecture/Effects/Deferring.swift, Sources/ComposableArchitecture/Effects/Publisher.swift, Sources/ComposableArchitecture/Effects/Throttling.swift, Sources/ComposableArchitecture/Internal/TaskCancellableValue.swift, Sources/ComposableArchitecture/Reducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/swift-composable-architecture-benchmark/Effects.swift, Tests/ComposableArchitectureTests/EffectFailureTests.swift, Tests/ComposableArchitectureTests/EffectOperationTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift
Currently, highly composed applications built with the library suffer from producing massively merged effects where each layer is erased. The creation and running of such effects can be expensive, even if every layer of the effect was just a `Effect.none`.
If you wanna see something really wild, check out the [underlying type][effect-lol] for the effect that is run in the store when `.onAppear` is sent in our case studies app. That's nearly 4,000 lines of pretty formatted type info. To contrast, with the changes in this PR that monstrous effect is squashed down to a single `Effect.none`.
Here are some benchmarks to show how things have changed:
```
Effects.Merged Effect.none (create, flat)   13667.000 ns ±  11.25 %     100456
Effects.Merged Effect.none (create, nested) 14250.000 ns ± …
```
=> Update Effect internals to be more efficient.

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Store.swift
In the last PR #1316 we left the naming of certain things in a weird spot, so we are correcting that now.
=> Rename some generics in the store rescoping.

Examples/Todos/TodosTests/TodosTests.swift
Hi there,
After the comments from @mbrandonw on #1317, I've replaced` uuid: { UUID.incrementing() } ` to just: `uuid: UUID.incrementing` to fix autogenerated UUID on Todo tests.
I also added an extra test adding two todos to verify this method will work as expected for more than one item.
Regards,
Pedro
=> Remove closure and pass UUID.incrementing as parameter on AppEnvironment

Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift, Sources/Dependencies/DependencyValues.swift
It is possible to define test dependencies via `TestDependencyKey` and never have a `DependencyKey` conformance. By default we want to warn about test dependencies used in production, but we should _not_ warn if the test dependency is overridden by a `dependency` reducer modifier.
Swift property semantics always does a `get` to the underlying property, so we need to set some temporary state when overriding dependencies to avoid emitting this warning. Not sure if other property trickery could simplify the implementation in this PR.
Thanks @andreyz for the report!
=> Don't warn for overridden test dependencies

Sources/ComposableArchitecture/Effects/Debouncing.swift, Sources/ComposableArchitecture/Effects/Deferring.swift, Sources/ComposableArchitecture/Effects/Timer.swift
Because publishers can be animated (and in general are responsible for scheduling work within a specific context), we should continue to force these helpers through our publisher endpoints, otherwise our next release could break animated schedulers.
We can consider soft-deprecating these endpoints, but we need to figure out the upgrade paths.
=> Force `Effect.{debounce,deferred}` through publisher

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/WithViewStoreAppTest.swift
We've found that `WithViewStore`s overloads can really tax the compiler, so it's time to get prepare to remove them. The vast majority of uses are in SwiftUI views, so we can privilege the helper for that use case, and require a bit of extra work of manually observing a view store via `@ObservedObject` in the other cases.
In the future it would be nice to deprecate `WithViewStore` entirely, but we would want to offer a simpler tool, _e.g._ a property wrapper called `@ObservedStore` that smashes the concepts of `Store` and `ViewStore` together without a lot of boilerplate. This would lessen compiler strain by avoiding escaping closures and generic transforms in the view builder layer. Unfortunately, we still haven't figured out how to get property wrappers to work in a way that we find …
=> Add deprecations to non-view `WithViewStore` initializers

Sources/ComposableArchitecture/Store.swift
This PR suggests another possible performance improvement.
Right now we use `.removeFirst()` to access the next action. We could instead use an incrementing index and clear `bufferedActions` at the end of the `send` block. 
There have been [discussions](https://github.com/pointfreeco/swift-composable-architecture/discussions/618#discussioncomment-935699) about using `Deque` instead of `Array`, I think this could be a possible alternative. 
I've held off on this one in the past because I was unclear on the memory implications. With all the performance improvements lately, I thought it would be a good time to revisit it and see what people thought. 
Here's the `Store scoping` benchmarks for `main` vs this pr:
```
name                                   time        std        iterations …
```
=> Defer action removal until performing last action

Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md
=> Capture `state.count` when entering `.task` in `GettingStartted.md`

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Debouncing.swift, Sources/ComposableArchitecture/Effects/Deferring.swift
These implementations are problematic for test schedulers because they schedule two discrete units of work. While we can probably work around it, let's avoid the bug for now.
=> Use publishers in `Effect.debounce` and `Effect.deferred`

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Internal/_StateObject.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/ViewStore.swift
The latest version of `WithViewStore` now uses a `@StateObject` that holds the `ViewStore` value it initially accessed (#1325). This allows to avoid many `ViewStore` instantiations and state comparisons in some cases.
However, the `@StateObject` property wrapper is only available for iOS 14+ (and other Apple OSes of this generation). Because TCA is currently supporting iOS 13, an availability check is performed to switch over the `StateObject` variant when possible, and fall back to `ObservedObject` like it was the case before. Because of the way result builders are working, this availability check wraps the whole `StateObject` branch in an `AnyView`.
`AnyView` have usually bad press. Their performance in extremal setups (root or leaf view) is usually [on par with fully typed …
=> Add `_StateObject`, an iOS 13 compatible substitute of `StateObject`

Sources/ComposableArchitecture/Store.swift
`Store.send` is currently spinning up a task for every batch of actions sent through it, even if no effects are in-flight. This issue compounds itself recursively when long-living effects feed actions back into the store.
Instead, let's only spin up tasks when we need to.
Fixes #1337
=> Fix long-living effect leak

Examples/TicTacToe/tic-tac-toe/Tests/AppCoreTests/AppCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorSwiftUITests/TwoFactorSwiftUITests.swift, Package.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
Ever since #1312 we've been getting some intermittent test failures. This is happening because we have a few tests that work directly with effects instead of using a `TestStore`, and those tests are leaving behind some artifacts that are being picked up by other tests.
This will not affect anyone using the library. This is only a problem in the library itself. We should probably audit all of those tests to make sure that things are cleaned up, or even better switch them all to use `TestStore` so that everything remains in a closed system.
=> Fix a few flakey tests

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift
Try to fix another non-deterministic Swift concurrency issue with tests.
=> Fix flakey test

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftUIDeprecations.md, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
Spurred by the discussions in #1340 I've added more documentation to both `WithViewStore` and the new `observe` argument in its initializer.
=> More docs for WithViewStore and new observe argument

Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/EffectDeprecations.md, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Publisher.swift, Sources/ComposableArchitecture/Effects/Throttling.swift, Sources/ComposableArchitecture/Effects/Timer.swift, Sources/ComposableArchitecture/Internal/Create.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift
We'll keep the type alias for the `Publisher` conformance, but given the changes made to TCA for concurrency, `Effect` should typically only be used these days in reducers to feed actions back into the store, and not more generally as publishers of any output.
=> Rename `Effect<Output, _>` to `Effect<Action, _>`

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/CompatibilityTests.swift
Simplified the test case for what we expect to happen with re-entrant actions from state observations, and moved the comments in Store.swift over to the test file.
=> Simplify re-entrant tests

Sources/ComposableArchitecture/TestStore.swift
Unfortunately for us, Swift does not offer a [reliable way to test integrated concurrency](https://forums.swift.org/t/reliably-testing-code-that-adopts-swift-concurrency/57304). Because of this, the Composable Architecture does what it can to insert instructions to the runtime to yield for some time and allow the work of an effect to get kicked off. We do this to try to simplify things for end-TCA users so that they don't need to manually instrument their own dependencies with async streams and channels for simple async work.
It's not perfect, though, especially when CI machines are typically underpowered virtual boxes that perform differently than what we expect locally. There are a couple tests in TCA that are flakey on GitHub CI that we could instrument to prevent flakiness, but …
=> Do more to avoid concurrency flakiness in tests

Sources/Dependencies/DependencyKey.swift, Tests/ComposableArchitectureTests/DependencyKeyTests.swift
Hey pointfreeguys,
This is a 1 line PR to slightly improve ergonomics of conforming to `DependencyKey` protocol. By choosing a default type for the `Value` associated type, we can omit the typealias when defining a key with only a `liveValue`.
The choice of default type is kinda arbitrary, but imho its quite common (at least in my codebases, hope Im not alone 😅) to want to use `Self`. E.g. `struct API: Dependency { static var liveValue: Self { .init() } }`. For that reason, this is an actual improvement to the everyday ergonomics.
Afaik the change is purely additive, I can't think of any existing valid Swift code that breaks as a result of the change. Can't speak for future Swift code 🤷‍♂️😅 but I think we should be fine.
I've started a …
=> added Self as default associatedtype value for TestDependencyKey.value

Examples/CaseStudies/SwiftUICaseStudies/CaseStudiesApp.swift, Examples/Search/Search/SearchApp.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognitionApp.swift, Examples/TicTacToe/App/RootView.swift, Examples/Todos/Todos/TodosApp.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemosApp.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Tests/ComposableArchitectureTests/DebugTests.swift
We want to revisit some of these debugging APIs in the future, so let's keep them around, but underscore them to allow for more flexible evolution.
=> `ReducerProtocol.debug` -> `ReducerProtocol._printChanges`

.github/workflows/documentation.yml, .gitignore, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved
Let's be consistent and always check this into our repos. It should provide a stabler CI environment and shouldn't affect downstream consumers of TCA.
=> Check in `Package.resolved`

Makefile, Sources/Dependencies/Dependencies/OpenURL.swift
Fixes #1428.
Also gets CI running on `macCatalyst`.
=> OpenURL fix for macCatalyst

Sources/ComposableArchitecture/Documentation.docc/Articles/DependencyManagement.md
Corrects a minor typo in the DependencyManagement documentation. Under chapter "Designing dependencies", protocol AudioPlayerClient should be a struct.
=> Correct typo in DependencyManagement docs

README.md
The `number` closure parameter was erroneously deleted after a migration of the code sample.
This PR adds it back.
Sorry I had to recreate yet another PR because I couldn't re-target the branch without adding a bunch of unrelated commits 😅
=> Fix missing parameter in code sample

Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerProtocol.md, Sources/ComposableArchitecture/ReducerProtocol.swift
Now that https://github.com/apple/swift/issues/60550 is fixed we can add back `ReducerProtocolOf`.
=> Add back ReducerProtocolOf for 5.7.1

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift
Our new internal helper for printing is still a work-in-progress, and customizing it was broken on `ReducerProtocol` release, as pointed out in https://github.com/pointfreeco/swift-composable-architecture/discussions/1465. This at least gets things building again.
=> Fix `_printChanges`

ComposableArchitecture.xcworkspace/contents.xcworkspacedata, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/TaskResult.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift, Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/Dependencies/Dependencies/OpenURL.swift, Sources/Dependencies/Dependencies/RandomNumberGenerator.swift, Sources/Dependencies/Dependencies/URLSession.swift, Sources/Dependencies/Dependencies/UUID.swift, Sources/Dependencies/DependencyValues.swift, Sources/Dependencies/Internal/RuntimeWarnings.swift, Tests/ComposableArchitectureTests/EffectFailureTests.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift, Tests/ComposableArchitectureTests/EffectTaskTests.swift, Tests/ComposableArchitectureTests/TaskResultTests.swift, Tests/DependenciesTests/DependencyValuesTests.swift
Dependencies is not currently usable outside Apple platforms due to unrestricted use of platform-only APIs. This PR should guard their availability a bit better and allow for compilation on Linux at the very least, allowing Dependencies code to be written in multiplatform libraries.
=> Loosen platform requirements for Dependencies library

Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Tests/ComposableArchitectureTests/ReducerBuilderTests.swift
Hopefully this doesn't cause problems elsewhere 🤞
=> Fix bad `buildFinalResult` warning on Swift 5.7

README.md
Fixing minor typos while studying the new Reducer Protocol. 😃
=> Fix typos in new Reducer Protocol README

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift
One step from our roadmap: https://github.com/pointfreeco/swift-composable-architecture/discussions/1477
=> Hard-deprecate `Reducer` struct type alias

Sources/ComposableArchitecture/Effects/Publisher/Timer.swift
Removed the unused `let` keyword from the Timer Use Example comment.
=> Remove not used let keyword in Timer Use Example comment.

Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md
Corrects a minor typo in the GettingStarted.md.
=> Fix typo in GettingStarted.md

Sources/ComposableArchitecture/Documentation.docc/Articles/DependencyManagement.md
Corrects a minor typo in the DependencyManagement.md.
=> Fix typo in DependencyManagement.md

Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Articles/DependencyManagement.md, Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftConcurrency.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md
Hi again!
Reading every new article of `ReducerProtocol` release, I caught all the small typos. Please review!
Thank you for continuing to develop TCA. 👍🏻
=> Fix typos in every DocC-Articles

Examples/CaseStudies/SwiftUICaseStudies/00-Core.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Basics.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Cancellation.swift, Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-NavigateAndLoad.swift
A PR about TCA's the `OpenURL` `Dependency` reminded me that we can use the built-in `@Environment(\.openURL)` in `CaseStudies`.
=> Remove a few dependencies to UIKit in SwiftUI's CaseStudies

.github/workflows/ci.yml, Examples/CaseStudies/tvOSCaseStudies/FocusView.swift, Examples/CaseStudies/tvOSCaseStudies/RootView.swift, Package.swift, Sources/Dependencies/Dependencies/Calendar.swift, Sources/Dependencies/Dependencies/Date.swift, Sources/Dependencies/Dependencies/Locale.swift, Sources/Dependencies/Dependencies/OpenURL.swift, Sources/Dependencies/Dependencies/TimeZone.swift, Sources/Dependencies/DependencyValues.swift
~~As pointed out in #1489, we somehow lost compatibility with Swift 5.5 (Xcode 13.2). While we hope to drop support when we hit 1.0, let's try to keep compatibility in the meantime.~~
Unfortunately, it does not appear that Swift 5.5 is up to task when it comes to the new `ReducerProtocol`. While we'd be happy to support it for folks that are stuck building on Xcode <=13.2.1, we personally don't have the bandwidth to investigate the problem. I've opened #1494 to track this.
=> Require Swift 5.6

Examples/Todos/Todos/Todos.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift
We have 2 unnecessary escaping closures in `ForEachStore` and `SwitchStore`. It's not actually gonna buy us anything in practice, but still they are definitely not needed.
=> Remove some escaping closures

Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift, Tests/ComposableArchitectureTests/DependencyKeyWritingReducerTests.swift
Documents some tricky behavior in `transformDependency` and fixes a bug with fusion logic.
=> More docs on transformDependency and a fusion fix.

Sources/ComposableArchitecture/Documentation.docc/Articles/SwiftConcurrency.md
Noticed a simple typo on a read through of the concurrency migration docs. Hope the tiny PR is kosher!
=> Fixes a small typo in concurrency docs

Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
This annotation slipped through #1493.
=> Remove one unnecessary `@escaping` annotation

Sources/ComposableArchitecture/ViewStore.swift
Considering that `viewStore.send(_:while:)` is `@MainActor`, it seems this one should be too.
=> Make ViewStore.yield(while:) main actor.

Sources/ComposableArchitecture/Documentation.docc/Articles/DependencyManagement.md
Fix #1522.
DocC doesn't support generating docs for multiple targets yet, so we had to disable hosting docs for the Dependencies module for now. We'll hopefully be able to revisit this in the future.
=> Remove broken link

README.md
New to TCA (and Swift for that matter) and was just building the Basic Usage section and ran into some minor errors, these minor changes correct the steps so you can build and run the example.
Using the latest Xcode and Swift 5.7 and the new TCA ReducerProtocol builds.  Key changes are:
- 'number' was undefined in the numbersapi.com code and complier flagged 'using' as an error
- wrapping the FeatureView() in a WindowGroup to fix errors
- sample didn't work since my simulator flagged using HTTP, since there is no HTTPS support added an exception to allow API requests to work.
=> Fixes for the 'Basic Usage' to allow project to build and run

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift
Hi, I improved the layout of `Web Socket` case study.
Let me know what you think. Thank you! 😄 
- The layout of the Web Socket was different from that of other cases. I modified it to have the same tone and manner.
- Also, there are multiple blue text buttons clustered together, making it a bit confusing. I modified it so that the roles of buttons are clearly distinguished.
- Messages are now stacking upward. And when re-connecting, the stacked messages are removed.
- I changed some text.
Please check out gif examples below. (1.5x speed)
|as-is|to-be|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/71127966/196712568-2b5619ae-8562-4ae0-8177-b250c7906e57.gif" width="250">|<img src="https://user-images.githubusercontent.com/71127966/196712670-8d751c16-379f-4ca9-b4b9-247fa4b23e …
=> Improve the layout of `Web Socket` case study

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadClient.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Examples/Search/Search/WeatherClient.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechClient/Client.swift, Examples/TicTacToe/tic-tac-toe/Sources/AuthenticationClient/AuthenticationClient.swift, Examples/VoiceMemos/VoiceMemos/AudioPlayerClient/AudioPlayerClient.swift, Examples/VoiceMemos/VoiceMemos/AudioRecorderClient/AudioRecorderClient.swift, Examples/VoiceMemos/VoiceMemos/Dependencies.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/DependencyManagement.md, Sources/ComposableArchitecture/Effect.swift
The `XCTUnimplemented` helper is a more general tool than XCTest, and can surface valuable runtime warnings in your application even if you never write a single test. Because of this we'd like to distance our tools from the `XCT` prefix where it feels appropriate.
As a small step, this means renaming `XCTUnimplemented` to `unimplemented`. While `XCTUnimplemented` still works today, it is soft-deprecated to push folks towards `unimplemented`, and assuming this course feels good, we'll eventually hard-deprecate it.
The one repercussion is that folks used to defining "unimplemented" dependencies using `static let unimplemented` will run into circular reference issues:
```swift
extension APIClient {
static let unimplemented = Self(
fetchUser: unimplemented("\(Self.self).fetchUser")  // 🛑
)
} …
```
=> `XCTUnimplemented` -> `unimplemented`

Examples/Search/Search/WeatherClient.swift
Since all the members are sendable, the `WeatherClient` does not need to conform to Sendable Protocol explicitly. It is implicitly Sendable.
=> refactor : remove unnecessary conformance to Sendable Protocol

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableFavoritingTests.swift
Hi! I removed a redundant `FavoriteError` struct in ReusableFavoritingTests.swift
And changed the hard-coded AlertState's title so that it's easier to maintain.
=> Remove redundant error type in ReusableFavoritingTests.swift

Sources/ComposableArchitecture/Internal/Deprecations.swift
> https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.43.0
> The Reducer type alias is now hard-deprecated to be renamed to AnyReducer
But it is not actually hard-deprecated.
=> Make `Reducer` actually deprecated

.github/ISSUE_TEMPLATE/bug_report.yml
It's great to remind filers to attempt to reproduce issues in vanilla SwiftUI and include those findings in their initial report. But, the new checklist item may exclude the filing of issues that TCA would want to respond to. In the past, such issues have led to good discussions on GitHub, documentation enhancements, and, I think, even additions to TCA.
_Note_: Despite being wordy, I used "this bug is _also_ reproducible" rather than simply "this bug is reproducible". My intent is to clearly imply that vanilla SwiftUI issues are still welcome, rather than perhaps imply vanilla issues shouldn't be filed.
Thoughts?
=> Nudge issue filers to repo in vanilla SwiftUI

.github/workflows/ci.yml, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/Dependencies/Dependencies/Clocks.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
Adopting the same as https://github.com/pointfreeco/swift-clocks/pull/5
=> Update swift-clocks conditional to match

Examples/TicTacToe/tic-tac-toe/Sources/AuthenticationClient/AuthenticationClient.swift, Sources/Dependencies/Dependencies/Calendar.swift, Sources/Dependencies/Dependencies/Locale.swift, Sources/Dependencies/Dependencies/TimeZone.swift, Sources/Dependencies/Dependencies/URLSession.swift, Sources/Dependencies/DependencyValues.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
It's currently possible to emit XCTest failures when testing reducers that access dependency values that emit failure upon access, which includes the calendar, locale, time zone, and URL session dependencies.
We may need a more holistic solution for folks that define these kinds of dependencies outside the library, but this will make the library-level failures a bit more lenient.
=> Avoid failure when setting test dependency values

Sources/ComposableArchitecture/Effects/ConcurrencySupport.swift
This change makes it easier to have unchecked types (eg, Color, Image) in State objects.
=> Add equatable conformance to UncheckedSendable when value is equatable

Sources/ComposableArchitecture/Reducer/ReducerBuilder.swift, Sources/ComposableArchitecture/Reducer/Reducers/CombineReducers.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Optional.swift, Tests/ComposableArchitectureTests/CompatibilityTests.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/ForEachReducerTests.swift, Tests/ComposableArchitectureTests/ReducerBuilderTests.swift, Tests/ComposableArchitectureTests/ScopeTests.swift
Turns out a lot of the bugs we were working around with `CombineReducers` inference, as well as `buildFinalResult` warnings (previously: #1467) go away if we use `some ReducerProtocol<State, Action>` on Swift 5.7 instead of the concrete alternative.
@slavapestov Not sure if you're aware of these functional differences between inference of generics vs. opaque constrained types or would like some fresh bug reports. It can take some time to file them, but if they're not being tracked yet we can try to file down a repro.
=> Use opaque reducers in 5.7 to fix builder inference

Tests/DependenciesTests/DependencyValuesTests.swift
While answering a question about `@Dependency` I started to wonder if there really is a difference between using `@Dependency` in an early binding vs a late binding.
For example, is there a difference between these two dependencies that each use a `@Dependency`:
```swift
struct ChildDependencyEarlyBinding: DependencyKey {
var fetch: () -> Int
static var liveValue: Self {
@Dependency(\.someDependency) var someDependency
return Self { someDependency.fetch() }
}
}
struct ChildDependencyLateBinding: DependencyKey {
var fetch: () -> Int
static var liveValue: Self {
return Self {
@Dependency(\.someDependency) var someDependency
return someDependency.fetch()
}
}
}
```
Because accessing `someDependency` goes through the `@Dependency` property wrapper, which then resolves the dependency, it …
=> Add test for early vs late binding of @Dependency.

Sources/ComposableArchitecture/TestStore.swift, Sources/swift-composable-architecture-benchmark/Dependencies.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
Following #1603, this PR renames a few new internal `Effect` introduced in recent changes, as an homogenous adoption will likely make the transition easier. I've kept three `Effect` with `Never` failures as `EffectPublisher`, as they're directly using `Combine` immediately after.
=> Rename a few new occurrences of `Effect` to `EffectTask` or `EffectPublisher`

Examples/CaseStudies/SwiftUICaseStudies/00-RootView.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Composition-TwoCounters.swift, README.md
We still had some old copy around `pullback` and `combine` that I'm sure are confusing.
=> Update case studies/docs for Scope and reducer builders

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Composition-TwoCounters.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md, Sources/ComposableArchitecture/ReducerProtocol.swift
Hey there, I caught some typos and syntax errors.
Please review the changes, Thanks! 😄
=> Fix typos in ReducerProtocol.swift

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md
Specifying the type of `viewStore` vended by `WithViewStore` can greatly help compilation times.
=> Update performance article

Tests/ComposableArchitectureTests/TestStoreTests.swift
Just some additional testing of the behaviour change in #1620 to verify it also applies to `TestStore.receive`
=> Test to confirm dependencies are also controlled in receive's updateExpectingResult closure

Tests/DependenciesTests/DependencyValuesTests.swift
This PR adds a test that covers the case where we override only a property of a `DependencyKey`. It checks that accessing the property from the dependency is producing the same result as directly exposing this property as a dependency.
It didn't seem obvious to me that it would work at first sight, but feel free to close the PR if you think this is superfluous.
=> Add a test that checks that nested dependencies are correctly overridden

Sources/ComposableArchitecture/TestStore.swift
In an early prototype for non-exhaustive test stores we explored an API that would allow subclassing `TestStore`. We abandoned that approach, but accidentally left the class open. So let's close it.
=> Close TestStore.

Sources/Dependencies/DependencyValues.swift, Tests/DependenciesTests/DependencyValuesTests.swift
Right now we infer the dependency context from whether or not we think the code is running in a test context. This causes problems when running tests on an application target, because the entry point of the application will actually execute, causing live dependencies to be used in a test context. Those failures bleed over to the test target. This is only an issue when testing application targets. Libraries and SPM modules work just fine.
Now technically it is just really bad that Xcode even runs the entry point of the application. This can cause you to accidentally execute API requests, track analytics, write data to disk, etc. without you knowing. TCA is just warning you that this is happening by yelling loudly and failing the test suite.
I'm starting to think it's not worth implicitly …
=> Don't implicitly infer test context.

Sources/Dependencies/Dependencies/OpenURL.swift
This simplifies the implementation of the `OpenURL` dependency and should allow to build dynamic frameworks with `APPLICATION_EXTENSION_API_ONLY`.
This should address #1673.
As a consequence, this raises the minimal availability of this dependency to iOS 14 and macOS 11.
=> Base `OpenURL` dependency on SwiftUI

Package.resolved, Sources/ComposableArchitecture/UIKit/AlertStateUIKit.swift
Replaced AlertState<Action>.ButtonRole with ButtonState<Action>.Role 
Replaced AlertState<Action>.Button with ButtonState<Action>
=> Fix ButtonRole and Button deprecations

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndConfirmationDialogs.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/DownloadComponent.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AlertsAndConfirmationDialogsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AnimationsTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-SharedStateTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/02-Effects-WebSocketTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableFavoritingTests.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/04-HigherOrderReducers-ReusableOfflineDownloadsTests.swift, Examples/Search/Search/SearchView.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/SpeechRecognition/SpeechRecognitionTests/SpeechRecognitionTests.swift, Examples/TicTacToe/tic-tac-toe/Package.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginCore/LoginCore.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorCore/TwoFactorCore.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginSwiftUITests/LoginSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorCoreTests/TwoFactorCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorSwiftUITests/TwoFactorSwiftUITests.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Makefile, Package.swift
While updating some examples to use the new `AlertState` and `ConfirmationDialogState` initializers, I thought it would probably be worth bumping [SwiftUINavigation](https://github.com/pointfreeco/swiftui-navigation) to the latest version. 
I had a feeling the examples didn't need to support a minimum version but was unsure. I just updated what I could find. 
In addition to updating the examples I have included some small fixes I noticed along the way. Happy to create separate PRs if needed. 
Summary of changes:
- Updated all examples that use `AlertState` and `ConfirmationDialogState`
- Added missing preview for `Search` example
- Remove unused `TestClock` from `ReusableComponentsFavoritingTests`
- Bumped swift tool version to `5.6` and platform requirement to `.iOS(.v15)` for …
=> Bump SwiftUINavigation and update examples

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md
On my way of `migrating to the reducer protocol`, I've found this small typo in the 4th code snippet of [Optional and pullback reducers section](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/migratingtothereducerprotocol/#Optional-and-pullback-reducers).
=> Fix code typo in the article 'Migrating to the reducer protocol'

README.md
Link the `0.47.0` documentation in `README.md` and move the `0.46.0` link under the collapsable `Other versions` section.
=> Link latest version documentation in README

Sources/ComposableArchitecture/ViewStore.swift
[Details](https://github.com/pointfreeco/swift-composable-architecture/issues/1783)
In a nutshell: binding works differently from @SwiftUI.State binding and could lead to a crash.
=> Resolve binding key path crash

Sources/ComposableArchitecture/ViewStore.swift
This PR works on top of #1784 and:
* Reduces the number of moving parts
* Restores implicit animations by directly producing the binding from the observable object
* Strongly retains the store in the binding to avoid losing writes
=> Simplify/fix #1784

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
When calling `TestStore.receive(_:…)` with a predicate or a case path and exhaustivity on, the current code in `main` never actually calls the `matching` predicate. This PR fixes that, with unit tests.
=> Make TestStore.receive actually match the action predicate

Sources/ComposableArchitecture/Effect.swift
This is to allow reclaiming 'Effect' at a later time without the 'Failure' generic in the near future.
=> Deprecate 'Effect' for 'EffectTask'

Sources/ComposableArchitecture/Documentation.docc/ComposableArchitecture.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/SwiftUIDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/TestStore.swift
Another step towards getting to `Effect<Action>` for reducers is to eventually remove the publisher interface to `Effect`. For now we are going to soft-deprecate `EffectPublisher` and eventually hard deprecate it and then remove it in 1.0.
Most likely no one is even using this type. The most likely place to use it would be in the return type of dependencies, and now people should migrate towards using Swift's concurrency tools for that.
=> Soft-deprecate EffectPublisher

Tests/ComposableArchitectureTests/EffectCancellationTests.swift
I think `testNestedCancels` has wrong cancellable id
=> Wrong cancel id on testNestedCancels

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Examples/Todos/Todos/Todo.swift, Examples/Todos/Todos/Todos.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ViewStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUI.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/BindingReducer.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
This PR proposes a solution to allow `BindingReducer` to work on `ViewState`. It consists in a simple protocol that you conform your `State` to, and a new property wrapper to expose `@Bindable` properties to `ViewState`. It also renames and deprecates a few types and methods in preparation for the version 1.0.
- `@BindableState` has been deprecated and renamed `@BindingState`, as "able" names are usually reserved for protocols.
- A `BindableStateProtocol` is introduced. You conform the `State` hosting `@BindingState` properties to it. The name of this protocol is transient and it will be renamed `BindableState` for the version 1.0.
- A `@BindingViewState` property wrapper is introduced. You use this property wrapper to annotate bindable values in your `ViewState`
- You directly create a …
=> Allow `BindingReducer` to work with `ViewState`

Sources/ComposableArchitecture/ViewStore.swift
While #1784 manages to work around a longstanding bug in SwiftUI, it unfortunately seems to introduce another one, as found in #1798. In the interest of addressing this regression with a patch release, let's revert things and re-evaluate if the problem is fixable.
@barabashd If you'd like to explore a fix that manages to avoid the crash in #1798, please let us know what you find! As for the original crash you encountered, it was mainly due to what we believe is a bug in Apple's SwiftUI framework. We actually provide a tool to work around this bug, called [`ForEachStore`](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/foreachstore), which allows you to compose into an array of features in a fashion similar to the ad hoc approach you …
=> Revert #1784: Resolve binding key path crash

Sources/ComposableArchitecture/ViewStore.swift
Attempt to fix #1800
The current method creates a binding with a location type of `ObservableObjectLocation`. By wrapping the binding the location type becomes `FunctionalLocation`. Bindings that use `ObservableObjectLocation` seem to have their getter called while evaluating if a views inputs have changed. This doesn't seem to be the case with `FunctionalLocation`. Which kind of makes sense.
I've confirmed this works for #1783 and #1798 as well as checked animations work as expected.
@stephencelis @mbrandonw @tgrapperon maybe you can stress test this a bit to see if there are any unwanted effects. I imagine there is going to be some sort of optimisation that can be applied to bindings that use `ObservableObjectLocation`, but don't really think that's relevant here.
=> Wrap view store binding to avoid reading stale state

Sources/ComposableArchitecture/Effect.swift
According to "[Road to 1.0](https://github.com/pointfreeco/swift-composable-architecture/discussions/1477)", missing `deprecated` on https://github.com/pointfreeco/swift-composable-architecture/pull/1788 ?
=> Add missing deprecated

Examples/Integration/Integration.xcodeproj/project.pbxproj, Examples/Integration/Integration/BindingsAnimationsTestBench.swift, Examples/Integration/Integration/EscapedWithViewStoreTestCase.swift, Examples/Integration/Integration/IntegrationApp.swift, Examples/Integration/IntegrationUITests/EscapedWithViewStoreTests.swift
This adds a test case for `ViewStore` from `WithViewStore` being escaped. We're taking measures to propagate the invalidation, but this should assert that they're still effective if `WithViewStore` implementation changes.
The test checks simultaneously a capture by a `GeometryReader`, and by some `Stepper`'s `onIncrement`. Both issues were solved by the same solution, but it is not exactly clear why the `Stepper`'s escape was causing an issue, so I feel it is better to check both. Because they share the same fix, they're tested in the same UITest though. I've also checked that each would spot a regression by reverting the `ViewStore` copy in `WithViewStore`.
I've also added a `Binding` animations test bench. This is not checked automatically, but this puts side to side binding animations …
=> Add a UI test for escaped `ViewStore` from `WithViewStore`, and a `Binding` animations test bench

Sources/ComposableArchitecture/SwiftUI/Presentation.swift
Really looking forward to the new navigation APIs in TCA and started experimenting with this branch.  I recognize this branch is a work in progress, but currently it doesn't compile under watchOS due to the lack of popover APIs in watchOS.  This PR correctly marks the popover APIs as unavailable in watchOS to address the issue.
=> Mark popover as unavailable in watchOS (navigation)

Sources/ComposableArchitecture/SwiftUI/Binding.swift
This PR makes `BindableState` conditionally conform to `Sendable`, as was done in #1790 but was subsequently lost when that PR was reverted. I can add any other desired conformances as well.
=> Conditionally Conform BindableState to Sendable.

Sources/ComposableArchitecture/ViewStore.swift
Fixes #1812.
This regression was subtle, but it's better to retain the old crashing behavior than introduce this change since it's been with the library for a very long time, and we have workarounds like `ForEachStore`.
We'll try to re-explore these subtle binding behaviors in the future.
=> Revert #1802

Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md
Basically copied and pasted some stuff from this: https://github.com/pointfreeco/swift-dependencies/pull/33
=> Testing gotchas

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-FocusState.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUI.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
The -`able` naming evokes protocols in Swift, and is an outlier when considered alongside the rest of TCA's binding tools:
- `BindingAction`: concrete type
- `BindableAction`: protocol
- `BindingReducer`: concrete type
So, let's make things consistent and rename `@BindableState` to `@BindingState`.
The one caveat is that Swift diagnostics for such a deprecation aren't great, so users won't get proactive warnings here for the time being:
https://github.com/apple/swift/issues/63139
We may just want to keep the deprecation around till it does...
=> Rename `BindableState` to `BindingState`

Examples/TicTacToe/tic-tac-toe/Tests/GameSwiftUITests/GameSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginSwiftUITests/LoginSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/NewGameSwiftUITests/NewGameSwiftUITests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorSwiftUITests/TwoFactorSwiftUITests.swift, Sources/ComposableArchitecture/TestStore.swift
It's a bit easy to dive into testing and be met with bad ergonomics if you forgot to conform `State` to be `Equatable`. Right now it doesn't require `Equatable` because it's possible to scope test stores and assert against view state/actions. This feature is pretty niche, though, and shouldn't make the more general case painful, so let's take a few steps to improve things:
1. We can deprecate the `TestStore.init` that takes non-equatable state
2. We can introduce a `TestStore.init(…:observe:send:…)` for testing view state/actions.
3. We can deprecate `TestStore.scope` (scoping a test store multiple times doesn't seem useful enough to support).
=> Improve `TestStore.init` ergonomics

Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
These methods are currently defined in a constrained extension, but it's not necessary, so let's loosen the constraint.
=> Unconstrain TestStore action for predicate/case path `receive`

Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift
Just a small win I found. Eventually we want to move a lot of `@ObservedObject`s to `@StateObject`s in the library, but can't until we drop iOS 13. However, these two instances can be done now.
=> Use @StateObject for iOS 15+ alert modifier.

Examples/TicTacToe/tic-tac-toe/Tests/LoginSwiftUITests/LoginSwiftUITests.swift, Makefile, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/EffectSend.md, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/CompatibilityTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
With the `Effect<Action, Failure>` -> `Effect<Action>` migration, `Effect.init(value:)` and `Effect.init(error:)` no longer make sense. We will be retiring the latter some time in the future, so let's also get a head start and rename the former to `Effect.send`.
For now it will call `Effect.init(value:)` under the hood, but in the future we will want a non-Combine-driven way of running synchronous effects.
=> Add `Effect.send`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/UIKit/AlertStateUIKit.swift
Alerts in SwiftUI Navigation are having a small breaking change in 0.6.0, so we need to release TCA shortly after to prevent folks from being in a broken state.
=> Update SwiftUI Navigation to support new alert mappings

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md
The discussion #1870 noted that our migration guide could include more of a breadcrumb that migrating to the Dependencies library isn't a simple matter of changing every environment property to a `@Dependency` property.
=> Add note to reducer protocol dependency section

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/ViewStore.swift, Tests/ComposableArchitectureTests/BindingLocalTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
A new implementation of #849. This time it will _only_ ignore actions sent via view store bindings, which is a common SwiftUI bug. If you send an action explicitly, _i.e._ in `.onDisappear { … }`, we will still surface runtime warnings to the end user.
=> `IfLetStore`: ignore view store binding writes to `nil` state

Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/BindingTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
This PR will address the crash found in #1877. The fact that `BindingAction` holds onto an `Any` existential directly means that attempting to extract another action from an enum that holds a `BindingAction` can lead to crashes in release mode depending on the layout.
This Swift bug is fixed in Swift 5.8, but we will need to provide a workaround.
Will start by pushing a test case to verify the crash on CI, then will push a workaround that boxes the existential in < 5.8.
=> Workaround for BindingAction existential layout crash

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreFilterTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
We're not ready to make it `public`, and `@_spi` APIs can still come up in autocomplete somehow. Xcode surfaces internal stuff in autocomplete too, occasionally, but maybe this will suppress it a bit.
=> Make `Store.filter` internal

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift
We currently interpolate the action directly, which prints in a pretty crude format that becomes almost incomprehensible for deeply nested actions (common in "integration" tests). So let's leverage Custom Dump instead!
=> Improve expected action test store failure message

Sources/ComposableArchitecture/TestStore.swift
Now that `TestStore` requires equatable state, we lose a bit of autocomplete and create a confusing situation while the user has to figure out how to fix.
We can help things along by defining a `unavailable` send/receive methods when state/action are not equatable, which helps with autocomplete, but also immediately tells the user what is wrong.
=> Unavailable TestStore.send/receive when state/action is not Equatable

Sources/ComposableArchitecture/Effect.swift
Fix a tiny typo found in the code snippet of `.task(...)`
=> Fix documentation

Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift
While this is a breaking change, its impact is likely pretty low, as trailing closure syntax should be overwhelmingly preferred in usage, and Xcode should provide automatic migration to the new parameter names:
- `Scope(...:child:)`
- `forEach(...:element:)`
The one exception that still is nameless is `CombineReducers` because it already includes the `Reducers` in its name, and a parameter name comes across redundant/verbose.
=> Make reducer builder closure parameters explicit

Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Tests/ComposableArchitectureTests/DebugTests.swift
For optimization reasons, `Reducer._printChanges()`'s isn't generating output for Xcode previews (#1625).
The new beta version of Xcode 14.3 now displays `Swift.print(…)` messages in the console under the "previews" tab, so we should probably revert the changes from #1625 and re-enable `_printChanges()`'s output in `preview` context.
I don't think there is a way to detect when previews are reloaded, so the output of successive reloads concatenates. It's better than nothing I guess, but this can maybe be improved in a subsequent PR.
=> Re-enable `_printChanges()` for previews

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Store.swift
Right now, `Send<Action>` being a top-level type makes it the preferred autocompletion choice when you type "Send…" to make some type `Sendable` (a very frequent operation). This is suboptimal.
Fortunately, this value is always provided by the library in standard operations, and the user usually doesn't have to handle its type directly. This PR relocates `Send<Action>` in `EffectTask<Action>.Send` (that is `EffectPublisher<Action, Never>.Send`, but it should transparently migrate to `Effect<Action>.Send` for the `v1.0`.). The current top-level `Send` is deprecated (which lowers its autocompletion rank and gives way to `Sendable`), but this shouldn't impact existing user code which should seamlessly resolve to `Effect<Action>.Send` instead of `Send<Action>` in the vast majority of cases. …
=> Nest `Send<Action>` as `Effect<Action>.Send`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration/BindingsAnimationsTestBench.swift, Examples/Integration/Integration/EscapedWithViewStoreTestCase.swift, Examples/Integration/Integration/ForEachBindingTestCase.swift, Examples/Integration/Integration/NavigationStackBindingTestCase.swift, Examples/Todos/Todos/Todo.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/Animation.swift, Sources/ComposableArchitecture/Effects/Publisher.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/SignpostReducer.swift, Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/BindingLocalTests.swift, Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/DependencyKeyWritingReducerTests.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/EffectFailureTests.swift, Tests/ComposableArchitectureTests/EffectOperationTests.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift, Tests/ComposableArchitectureTests/EffectTaskTests.swift, Tests/ComposableArchitectureTests/EffectTests.swift, Tests/ComposableArchitectureTests/ReducerBuilderTests.swift, Tests/ComposableArchitectureTests/ReducerTests.swift, Tests/ComposableArchitectureTests/ScopeTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
I've qualified a few missed occurrences of unqualified `Send` that I missed in #1911. I can rebase these changes in `main` if you prefer.
I've used `EffectTask` as this alias is still used through the codebase.
This should fix #1924
=> Qualify `Send` as `Effect(Task)<Send>`

Examples/Integration/Integration/ForEachBindingTestCase.swift, Examples/Integration/IntegrationUITests/EscapedWithViewStoreTests.swift, Examples/Integration/IntegrationUITests/ForEachBindingTests.swift, Examples/Integration/IntegrationUITests/NavigationStackBindingTests.swift, Makefile, Tests/ComposableArchitectureTests/ViewStoreTests.swift
In #1845 we reverted #1802 and as such our UI test for the strange binding behavior inside `ForEach`'s started to crash. However, apparently app crashes do not cause test failures (would love to know if anyone knows how to do that though).
So, I've updated the test to be more resilient and not crash, and as such added a `XCTExpectFailure` in the UI test. This way if we ever do finally fix this behavior we will have a test that will fail and then can be corrected.
=> Fix UI test for ForEach bindings.

Package.resolved, Package.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
We recently added `XCTModify` to our case paths library that makes it easy to apply an in-place mutation to a case of an enum. We employ exhaustive checking in the function so that if you apply a mutation that doesn't actually change anything it will cause a test failure. However, we need to opt out of that behavior in non-exhaustive test stores, so that is what this PR does.
=> Make the new XCTModify play nicely with non-exhaustive testing.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ReduceDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ReducerDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/SwiftUIDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/TestStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ViewStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Reduce.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Store.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TaskResult.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/TestStore.swift
We have a number of outdated DocC references. This PR should hopefully take care of them!
=> DocC fixes

README.md
Link the 0.51.0 documentation in README.md and move the 0.50.0 link under the collapsable Other versions section.
=> Update latest version documentation link in README

Sources/ComposableArchitecture/Effects/Publisher/Timer.swift
Show deprecation warnings only for versions [that support](https://github.com/pointfreeco/swift-dependencies/blob/d3406a54315daccc2c86a21da04584b1fefa7136/Sources/Dependencies/DependencyValues/Clocks.swift#L2) `@Dependency(\.continuousClock) var clock`.
=> Deprecations only for versions supporting clock.timer

Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/SignpostReducer.swift
When using reducer operators (e.g. `.ifLet`, `.forEach`, etc.) it's possible to accidentally forget the `.`:
```swift
var body: some ReducerProtocolOf<Self> {
Reduce { … }
ifLet { … }
^ 
```
This will cause a mysterious infinite loop and crash. The same happens in SwiftUI, and luckily Swift has an attribute that will warn if you ever use the method without qualifying the receiver, so let's use it!
=> Add @warn_unqualified_access to reducer operators.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreTests.swift
The issue #1947 for something related to the navigation beta (#1944) has surfaced a small problem in the library that exists on `main` today.
Right now effect actions (i.e. actions sent into the system from effects) are executed with the dependencies that were active at the moment the effect was constructed. This allows some surprising behavior in which dependency changes "accumulate" when you have an effect that emits an action, and that action returns an effect that emits an action, and on and on.
Take this for example:
```swift
switch action {
case .tap:
return withDependencies {
$0.count.value += 1
} operation: {
.task { .response1(self.count.value) }
}
case let .response1(count):
state.count = count
return withDependencies {
$0.count.value += 1
} operation: {
.task { …
```
=> Do not propagate dependencies to effect actions.

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
This was reported by @oronbz in Slack. We call `prepareDependencies` immediately in the `TestStore` initializer which means accessing a dependency in the trailing closure can trigger a test failure. We need to move it into `withDependencies` so that such failures are suppressed.
=> Fix TestStore.init with prepareDependencies.

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
I just went through the `ForEachStore` doc examples and noticed a couple of small inconsistencies that prevent them from compiling as is. Hope that helps!
=> Fix types, .forEach() call

Sources/ComposableArchitecture/Documentation.docc/Extensions/Effect.md, Sources/ComposableArchitecture/Effects/Publisher.swift
We are looking to deprecate TCA's dependence on Combine, _e.g._ the direct conformance of `Effect` to `Publisher`, as well as many Combine-centric APIs, but that doesn't mean we want to eliminate support for using Combine with TCA. Our current advice given by our soft deprecations is to iterate over `publisher.values`, but this is unavailable in iOS 13 and 14, so let's introduce a dedicated bridging mechanism, instead.
=> Add 'Effect.publisher' for bridging effects from Combine

Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
Hi there, 
While reading the documentation for `WithViewStore` I've found one small grammar error.
=> Fix grammar in doc

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestHelpers.swift
This discussion #1717 brings up some interesting behavior with child task cancellation that I think we want to address eventually. For now I'm getting a test in place that documents the behavior so that we can decide how to handle later.
=> Get some test coverage on child/parent effect cancellation behavior.

Sources/ComposableArchitecture/Effects/Publisher.swift, Tests/ComposableArchitectureTests/EffectPublisherTests.swift
Currently the escaping closure drops them.
=> Escape dependencies to `EffectTask.publisher`

Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift
It can be handy to have this logging during a test, so let's not go out of our way to suppress it.
=> Don't disable `_printChanges()` in tests

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Tests/ComposableArchitectureTests/DebugTests.swift
We recently worked around a Swift 5.8 crash in swift-custom-dump, and so it would be nice to get some visibility into this and encourage everyone to update their dependencies.
=> Update swift-custom-dump to 0.10.0.

.github/workflows/ci.yml, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration.xcodeproj/project.pbxproj, Examples/Integration/Integration/IntegrationApp.swift, Examples/Integration/Integration/SwitchStoreTestCase.swift, Examples/Integration/IntegrationUITests/SwitchStoreTests.swift, Examples/TicTacToe/tic-tac-toe/Sources/AppSwiftUI/AppView.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
Rather than rely on many, many overloads of `SwitchStore.init` to strictly accept only `CaseLet`s and an optional, final `Default` view, let's introduce a single initializer without constraints that is passed the current state whenever the case changes. This state can be switched on and route to the appropriate view via `CaseLet`.
The pros:
* We get exhaustive switching at compile time.
* We get more flexibility in the view layer. Previously, any customization needed to be pushed into the `CaseLet` builder, but now `CaseLet` can freely apply view modifiers.
* We can deprecate and eventually remove the many, many initializer overloads, and hopefully slim down binary size in the process, and improve view builder compile times when dealing with `SwitchStore`. We can also deprecate and …
=> Pass state to `SwitchStore.init` view builder

README.md
Hello 👋 I would like to propose my small contribution to this amazing project. Hopefully it will make it even more accessible to polish developers 😊 
Love this architecture, it's the least I can do 🙌
Best Regards,
Marcel
Special thanks to @sochalewski and @kbabis for reviewing the translations and finding typos and misspellings 🙏
=> Polish translation of TCA's README

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, ComposableArchitecture.xcworkspace/xcshareddata/xcschemes/ComposableArchitecture.xcscheme, ComposableArchitecture.xcworkspace/xcshareddata/xcschemes/swift-composable-architecture-benchmark.xcscheme, Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/CaseStudies/CaseStudies.xcodeproj/xcshareddata/xcschemes/CaseStudies (SwiftUI).xcscheme, Examples/CaseStudies/CaseStudies.xcodeproj/xcshareddata/xcschemes/CaseStudies (UIKit).xcscheme, Examples/CaseStudies/CaseStudies.xcodeproj/xcshareddata/xcschemes/tvOSCaseStudies.xcscheme, Examples/Integration/Integration.xcodeproj/xcshareddata/xcschemes/Integration.xcscheme, Examples/Search/Search.xcodeproj/xcshareddata/xcschemes/Search.xcscheme, Examples/SpeechRecognition/SpeechRecognition.xcodeproj/xcshareddata/xcschemes/SpeechRecognition.xcscheme, Examples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/TicTacToe.xcscheme, Examples/Todos/Todos.xcodeproj/xcshareddata/xcschemes/Todos.xcscheme, Examples/VoiceMemos/VoiceMemos.xcodeproj/project.pbxproj, Examples/VoiceMemos/VoiceMemos.xcodeproj/xcshareddata/xcschemes/VoiceMemos.xcscheme, Tests/ComposableArchitectureTests/EffectRunTests.swift
We had some warnings related to new Xcode 14.3 settings.
=> Bump Xcode settings

Sources/ComposableArchitecture/SwiftUI/NavigationLinkStore.swift
Renamed the `action` parameter to mirror other inits and differentiate itself from `action fromDestinationAction`
=> Renamed action to onTap in NavigationLinkStore

Sources/ComposableArchitecture/Effects/Cancellation.swift
=> Fix withTaskCancellation documentation

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Bindings-Forms.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer/Reducers/BindingReducer.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
In #1855, `@BindableState` was renamed to `@BindingState`.
However, there are still some unchanged keywords in the repository.
This PR updates all remaining `bindable state` to `binding state` for consistency.
=> Update remaining 'bindable state' to 'binding state'

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
This is from our backlog, but we have some unneeded code in `skipInFlightEffects` so deleting that. Also I wrote a test to capture the existing behavior that skipping effects only removes the effect from consideration as far as the test store is concerned, but does not actually cancel it. We can think more about if we _should_ cancel it in the future, or leave things as is.
=> Clean up skipInFlightEffects and write test on beahvior.

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Effects/TaskResult.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Internal/RuntimeWarnings.swift, Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift
Runtime warnings are not test helpers that should propagate XCTest failures to the original file/line, so we should always omit that information. This leads to better test failures that show up alongside the test, not buried in application code.
=> Don't pass file and line to runtime warnings

Sources/ComposableArchitecture/TestStore.swift
To unify with:
* https://github.com/pointfreeco/swift-clocks/pull/18
* https://github.com/pointfreeco/combine-schedulers/pull/82
=> Make mega yield configurable by environment variable

Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
For some reason, using `memcmp` with an empty ordered set and a non-empty ordered set returns true:
```swift
areOrderedSetsDuplicates([1, 2, 3], []) // true
```
Because of this, we should always check the count before delegating to `memcmp`. We should also be on the lookout for other exceptions in case `memcmp` is not appropriate to use here.
=> Fix ordered set comparison check

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndConfirmationDialogs.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift, Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-SharedState.swift, Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ReusableFavoriting.swift, Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift, Examples/TicTacToe/tic-tac-toe/Sources/GameUIKit/GameViewController.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginSwiftUI/LoginView.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginUIKit/LoginViewController.swift, Examples/TicTacToe/tic-tac-toe/Sources/NewGameUIKit/NewGameViewController.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorSwiftUI/TwoFactorView.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorUIKit/TwoFactorViewController.swift, Examples/Todos/Todos/Todos.swift, Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Tests/ComposableArchitectureTests/EffectDebounceTests.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift, Tests/ComposableArchitectureTests/EffectTaskTests.swift, Tests/ComposableArchitectureTests/EffectThrottleTests.swift, Tests/ComposableArchitectureTests/MemoryManagementTests.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
Explicit scoping is most appropriate for transforming domains, which almost always requires an action transform. In the rare case it doesn't, we should prefer an explicit `{ $0 }`.
Scoping for the view has been deprecated for awhile for the `observe` parameter when creating view stores, so let's lead folks that direction.
=> Deprecate `Store.scope(state:)` for view store `observe`

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
@alexito4 brought up in Slack that `prepareDependencies` was called twice when creating a `TestStore`. On the hand one probably shouldn't do work in `prepareDependencies` that couldn't be done twice, but on the other hand the call site does make it look like it's a simple setup function (and even copies the `withDependencies` style from swift-dependencies), so it probably should only be called once.
=> Call prepareDependencies once when initializing TestStore.

Sources/ComposableArchitecture/TestStore.swift
There was an internal helper in `TestStore` that wasn't `@MainActor` and it could cause trouble. Eventually for 1.0 we'd probably prefer if `TestStore` was just `@MainActor` entirely, but we will explore that later.
=> Make internal helper @MainActor.

Sources/ComposableArchitecture/Documentation.docc/ComposableArchitecture.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ReducerDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/StoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/TestStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ViewStoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerProtocol.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Store.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ViewStore.md, Sources/ComposableArchitecture/Internal/Deprecations.swift
Just some things I found while browsing.
=> DocC organization

.github/workflows/ci.yml, Makefile
Make doesn't override env vars in the traditional way, so portions of our CI (library tests) were only running tests in debug mode. This should fix.
=> Fix CI: Actually pass configuration to make

README.md
PointFree supports new localizations. The world supports Ukraine now. So, let's add support for Ukrainian in TCA.
// PS: It would be great to automate localizations in the future to reflect updates in other Gist files as well.
=> Ukrainian translation of TCA's README

Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Stephen and I discussed this helper this morning. It can be handy in non-exhaustive test stores where you want an ergonomic way to assert on the current state of the store without having to explicitly `receive` an action.
=> Add TestStore.assert.

Sources/ComposableArchitecture/Documentation.docc/Tutorials/03-04-code-0008.swift
It's just a small bug in tests when assertion values don't contain a comma character.
=> Fix assertion values

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingToTheReducerProtocol.md
There is a minor modification on the article: "Migration to the Reducer Protocol". 
The given code snippet declares the action as `struct` type, but it should be `enum`.
=> [Documentation] Fixed action type: `struct` to `enum`

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/Documentation.docc/Articles/WhatIsNavigation.md
Fixed some typos in documentations below.
- `WhatIsNavigation.md`
- `TreeBasedNavigation.md`
=> Fix typos in DocC

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
Fix some typos in StackBasedNavigation documentation
=> Minor fixes in StackBasedNavigation.md

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0006.swift
fireAndForget was used in the official tutorial.
Since `Effect.fireAndForget` is soft deprecated in version 0.53.0, I rewrote it to `Effect.run`.
#2099 
Is there a reason why fireAndForget is used?
=> `Effect.fireAndForget` is soft deprecated

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
I found several modifications regarding the use of 'Effect' in the [Navigation document](architecture/blob/main/Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md). I updated the deprecated methods in the code snippets.
This PR is related to the [issue #2158](https://github.com/pointfreeco/swift-composable-architecture/issues/2158)
=> Update StackBasedNavigation.md to use `.run` instead using `.fireAndForget`

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
This PR changes `struct Action` to `enum Action` in the documentation for `PresentationReducer`.
=> Update PresentationReducer Documentation

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
A simple typo fix in the documentation for stack-based navigation.
=> Update StackBasedNavigation Documentation

Sources/ComposableArchitecture/Effects/Publisher.swift
I just saw while working on a migration to 'EffectTask'.
The friend who develops watchOS may misunderstand, so it looks better to fix it. 🤗
=> Fix 'EffectPublisher.run' deprecation message

Sources/ComposableArchitecture/Internal/NavigationID.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
Fixes #2189
These `@usableFromInline` attributes seem to be running into a Swift compiler bug where under certain project set ups the following error occurs when building for release:
> error: <unknown>:0: unsupported relocation with subtraction expression, symbol '_$s12Dependencies16DependencyValuesV22ComposableArchitectureE16navigationIDPathAD010NavigationG0VvpACTKq' can not be undefined in a subtraction expression
We're not sure why some projects build just fine (such as all the demo apps in this repo) and others do not (such as the one shared in #2189). 
But either way it should be relatively harmless to remove these annotations. TBH the bodies of the `ifLet`, `forEach` and `ifCaseLet` reducers are probably so substantial that they do not benefit from inlining anyway. We also have …
=> Remove inlineable attributes to work around Swift compiler bug.

Sources/ComposableArchitecture/ReducerProtocol.swift
This PR corrects the comment associated with the `ReducerProtocolOf` typealias. Previously, the comment inaccurately stated that the feature was "only in Swift 5.7.1". The revised comment now specifies that the feature is available "starting from Swift 5.7.1", more accurately reflecting that it can be accessed in Swift 5.7.1 and all subsequent versions.
Changes made:
- Updated the comment for the `ReducerProtocolOf` typealias to accurately reflect its Swift version availability.
This update ensures clearer and more accurate documentation for developers.
---
Related Documents:
- https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/reducerprotocolof
=> Fix Swift version comment for `ReducerProtocolOf` typealias

Sources/ComposableArchitecture/Internal/AreOrderedSetsDuplicates.swift, Sources/ComposableArchitecture/Store.swift
There's one more warning around `SwiftUI.Transaction` not being sendable (`@preconcurrency` is not enough)...
=> Fix a few  Xcode 15 warnings (Swift 6 errors)

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
This API has been more problematic than not, especially when folks accidentally type `.cancel(id:)` and pass a hashable array when they expect to be passing multiple tokens along to each cancel. Let's avoid the confusion by deprecating the functionality.
Cancelling multiple tokens at once should also be less common these days now that navigation tools bakes cancellation into dismissal.
=> Deprecate `Effect.cancel(ids:)`

Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducerSignpost.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Right now in non-exhaustive test stores showing skipped assertions, it is possible to get a skipped assertion complaining of "Expected state to change, but no change occurred.". That should only happen with exhaustive test stores.
=> Don't show 'expected state to change' error in non-exhaustive test stores.

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md
I don't know if contributions just to the documentation are welcome, but I think I spotted a few instances of outdated or incorrect sample code in Tree-based navigations.
1. The store scope misses the `$` e.g:
```diff
- store: self.store.scope(state: \.destination, action: { .destination($0) }),
+ store: self.store.scope(state: \.$destination, action: { .destination($0) }),
```
2. The Destination model is missing when isolating the specific state and action, e.g:
```diff
- state: /InventoryFeature.State.addItem,
+ state: /InventoryFeature.Destination.State.addItem,
```
3. The forward slash can be removed when isolating to action
```diff
- action: /InventoryFeature.Action.addItem
+ action: InventoryFeature.Destination.Action.addItem
```
I got stuck here a little bit, while following along …
=> Update code examples of Tree-based navigation documentation

Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift
I resolved CaseStudies' compile error.
The 'state' argument label in `CaseLet` init should have been omitted.
=> Resolve CaseStudies crash

Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md
This adds a missing argument label to documentation sample code.
=> Fix WithViewStore argument label in Bindings.md

Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md
Another documentation sample code fix.
Not sure how I missed this in #2256, but the `observe` parameter should be `ViewState.init`–not `ViewStore.init`.
=> Fix ViewStore.init that should be ViewState.init in Bindings.md

Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
This fixes a recurring punctuation error I came across in documentation
=> Fix commas that should be periods in docs

Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift, Examples/Standups/StandupsTests/AppFeatureTests.swift, Sources/ComposableArchitecture/Reducer/Reducers/Reduce.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/swift-composable-architecture-benchmark/StoreSuite.swift, Tests/ComposableArchitectureTests/Reducers/BindingReducerTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Fixes #2253.
If a store state change results in only updating a view store's `BindingViewState`, it was considered equivalent, since the `Binding` would always contain the latest value. This PR fixes things by holding a snapshot of state in `BindingViewState` instead.
=> Fix view state binding equatability

Sources/ComposableArchitecture/ViewStore.swift
Currently, `ViewStoreTask.cancel` works like `TestStoreTask`, where it'll cancel _and_ await cancellation to complete. This is needlessly limiting, and probably not what you want when interacting with cancellation.
=> Make `ViewStoreTask.cancel` synchronous

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Publisher/Debouncing.swift, Sources/ComposableArchitecture/Effects/Publisher/Throttling.swift, Sources/ComposableArchitecture/Effects/Publisher/Timer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
Fixes #2233.
On iOS 14, `DismissEffect` is broken because effect cancellation uses `AnyHashable` throughout, which can lead to nested `AnyHashable(AnyHashable(...))` IDs, which can hash differently depending on the level of nesting. By preserving the hashable ID up to being stored in the internal cancellation token type, we can avoid a hash lookup failure that prevents a dismissal from happening.
=> Fix cancellation ID existentials in iOS 14

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/ViewStore.swift
v0.55 deprecates the `WithViewStore` initialiser that takes Void state and recommends using `Store.send` instead, however there isn't parity with the `ViewStore` APIs as those do let you specify an animation or transaction parameter, while Store.send doesn't. This PR adds those methods for full parity
=> Added the ability to specify an animation or transaction with `Store.send`

Examples/Integration/Integration/NavigationStackTestCase.swift, Examples/Integration/IntegrationUITests/NavigationTests.swift, Sources/ComposableArchitecture/SwiftUI/NavigationStackStore.swift
=> Fix for infinite loop when combining Stack and Tree navigation

Sources/ComposableArchitecture/TestStore.swift
The messaging stood out to me as a little confusing in isolation:
> **Warning**: 'send(_:assert:file:line:)' is unavailable: State must conform to Equatable to send actions.
So I think a little clarification reads better.
> **Warning**: 'send(_:assert:file:line:)' is unavailable: 'State' must conform to 'Equatable' to assert against sent actions.
=> Clean up test store deprecation messages

Examples/Integration/IntegrationUITests/PresentationTests.swift, Sources/ComposableArchitecture/SwiftUI/NavigationDestination.swift, Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift
Fixed https://github.com/pointfreeco/swift-composable-architecture/issues/2182.
Added `.id(id)` modifier to update value of `id` in `compactSend` closure when presenting a child feature.
=> Fixed tree-based navigation: dismiss action is not sent when navigating back

Sources/ComposableArchitecture/TestStore.swift
I kept finding myself wishing for a convenience initialiser for `TestStore` when I'm not scoping or using an environment, so I don't have to type out/copy and paste the rather verbose `TestStore<Reducer.State, Reducer.Action, Reducer.State, Reducer.Action, Void>`.
After adding it to my own project and liking it, I thought I may as well try my first PR here.
If you feel it's unnecessary, then no worries.
=> Add TestStoreOf typealias

Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/ViewStoreTests.swift
StoreTask cancel has been changed to synchronous in #2282, so await is not necessary.
=> StoreTask.cancel is not an asynchronous method

Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
`TestStore.init(initialState:reducer:prepareDependencies:file:line:)` is deprecated, so I rewrote it to `TestStore.init(initialState:reducer:withDependencies:file:line:)`.
=> `TestStore.init(initialState:reducer:prepareDependencies:file:line:)` is deprecated

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/DebugTests.swift
Now that binding action key paths cannot use dynamic member lookup, dumps are a little more unwieldy to read when nested state is involved. Generally one can look at the state diff to figure out what changed, so let's abbreviate the action's state when we can.
=> Abbreviate nested binding action values

Sources/ComposableArchitecture/Effects/Cancellation.swift
Noticed when trying `release/1.0` and moving from the old `EffectTask` debounce to the `.run` debounce that the comment docs don't match reality
Missing a try on the `withTaskCancellation` call, and a dot on the `send` call that shouldn't be there
Pointed this at main because it's there too, and I assume changes will be merged into the 1.0 branch
=> Typo in withTaskCancellation debounce documentation

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift
I think the addition of Store.send is very innovative because it makes it clear that the View does not need to observe changes in State.
However, I noticed that Store.send is not returning a StoreTask, unlike ViewStore.send.
I want Store.send to also use `.task { await store.send(.task).finish() }`, just like ViewStore.
Is there any reason why Store.send isn't implemented that way?
If so, you can ignore this PR.
Thanks.
=> Add Store.send(_ action:) return StoreTask

Sources/ComposableArchitecture/Documentation.docc/Extensions/UIKit.md, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/ViewStore.swift
Now that `ViewStore`s have a limited future, we should surface functionality that was `ViewStore`-only to the `Store` instead.
While we could probably start discouraging using `ViewStore` at all in UIKit apps by deprecating the existing API, it's pretty close to the 11th hour of shipping 1.0, and we are probably better off deprecating `ViewStore` all at once when the Observation framework is released.
=> Expose `StorePublisher` directly on `Store`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Standups/Standups/App.swift, Examples/Standups/Standups/AppFeature.swift, Examples/Standups/Standups/RecordMeeting.swift, Examples/Standups/Standups/StandupDetail.swift, Examples/Standups/StandupsTests/AppFeatureTests.swift, Examples/Standups/StandupsTests/RecordMeetingTests.swift, Examples/Standups/StandupsTests/StandupDetailTests.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
We uncovered a few improvements to be made to Standups while recording the new series, so just bringing the repo's app up-to-date with those changes.
=> Some small improvements to Standups.

Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/Reducers/BindingReducerTests.swift
Currently, `BindingViewStore`s can only directly derive `BindingViewState` for a view state struct, and then the view store can derive a binding and use dynamic member lookup to pluck out a field for a view. This means potentially exposing view state to far more state than necessary.
To prevent this we can add dynamic member lookup to the binding view state itself, which allows a view state struct to chip away any state it doesn't care about.
=> Allow chaining into `BindingViewState`

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-AlertsAndConfirmationDialogs.swift, Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-AlertsAndConfirmationDialogsTests.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift
An 11th hour deprecation/removal, but these APIs should be removed since they work differently depending on the iOS version (13-14 uses the old alert APIs, 15+ uses new, but this means different behavior on different OS versions).
We don't ship an alternative API for iOS 13, but SwiftUI Navigation comes with helpers for constructing `Alert` from `AlertState`, which can be used manually.
=> Deprecate old alert APIs in favor of new presentation APIs

Sources/ComposableArchitecture/Dependencies/Dismiss.swift
Hi ✌️,
Firstly, a big thank you for your remarkable work on the Composable Architecture 😀. Recently, while using a new navigation API, we referenced the `DismissEffect` documentation for a child feature dismissal test. In doing so, we spotted a small area for improvement. This PR aims to correct it for better reflecting the testing context.
Thank you for your time and consideration.
=> Documentation update in DismissEffect example

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/TestStore.swift
Right now if a test failure occurs while creating a reducer/state (e.g. accessing a dependency that hasn't been overridden), the test failure doesn't show up in the best spot. This uses the new `XCTFailContext` from xctest-dynamic-overlay to improve the situation.
=> Improve TestStore failures on init.

Examples/Integration/IntegrationUITests/PresentationTests.swift, Makefile, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
Fixes two things:
* Right now an integration test crashes due to an iOS 17 bug, so we are just not going to run that test on iOS 17. We should also really file a bug report with Apple about it.
* When using shortened syntax for state initialization (i.e. `initialState: .init()`) in `TestStore` you get an incorrect deprecation warning.
=> Fix integration test and incorrect deprecation warning on TestStore

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-02-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-TestingYourFeature.tutorial
A couple of people brought up that the timer test does now tend to pass since we upped the default timeout in `TestStore` to 1 second. So, let's add a little nuance to the discussion.
=> Small clarification for timer test in tutorial.

Sources/ComposableArchitecture/Internal/Deprecations.swift
After updating to 0.58.0 I noticed that these didn't get flagged as deprecated, causing a bunch of errors when I attempted a move to 1.0.0
Hopefully this is the correct change 🙏
=> Additional deprecations

Sources/ComposableArchitecture/Effects/TaskResult.swift
- Fix enum case with Associated Value having no 'let' to get local value.
- hope it helps!
```diff
- case .factResponse(.success(fact)):
+ case let .factResponse(.success(fact)):
```
=> Fix TaskResult Example in Documentation

Sources/ComposableArchitecture/Effects/TaskResult.swift
- Type `FeatureAction` is now Type `Action` which is conformance of `Reducer`
```diff
- enum FeatureAction: Equatable {
+ enum Action: Equatable {
case factButtonTapped
case factResponse(TaskResult<String>)
}
```
=> Fix TaskResult Action enum name in Documentation

Sources/ComposableArchitecture/Effects/Debounce.swift, Tests/ComposableArchitectureTests/EffectDebounceTests.swift
Having brought back an explicit interface for `throttle` [here](https://github.com/pointfreeco/swift-composable-architecture/pull/2368) we should also consider providing an explicit interface for `debounce`.
Though a clock-based debounce is a matter of:
```swift
return .run { send in
try await withTaskCancellation(id: CancelID.debounce) {
try await clock.sleep(for: .seconds(1))
await send(.action)
}
}
```
A dedicated operator simplifies and flattens:
```swift
return .send(.action)
.debounce(id: CancelID.debounce, for: .seconds(1), clock: clock)
```
This PR only brings back the scheduler-based API, so alongside #2368 we are reintroducing two Combine-forward APIs for this work. Before we release a 1.1 that fully commits these APIs, we should consider if we can make clock-based APIs work, …
=> Bring back debounce?

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
When a store is initialized with presentation state that is already presented, we use a flag on `@PresentationState` to determine if we need to integrate the `\.dismiss` effect to allow the child to dismiss itself.
This flag currently stays `true` for the lifetime of the presenting feature, which means if a parent re-presents a feature after dismissal, the `\.dismiss` effect will fail to do anything when called from the child.
This PR ensures that the flag is reset to `false` when a presenter detects that a child feature has been dismissed, fixing this bug.
=> Tear down presentation state on dismissal

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
This PR cherry-picks the [fix](https://github.com/pointfreeco/swift-composable-architecture/pull/2347) for an incorrect `TestStore` deprecation warning onto the `prerelase/1.0` branch. 
I'm opening the PR because it seemed an easy fix and should help folks getting rid of some noise while preparing for `1.0`. For instance, in highly tested codebases these incorrect warnings could hide the important deprecations that `0.57`/`0.58` should help fixing. It would be nice to include this into a `0.58.2` or `0.59` release 🙂
=> 0.x: Fix deprecation warning on TestStore

Sources/ComposableArchitecture/Store.swift
While `Store.send`'s internal access to `Box<[Task]>` does seem mutually exclusive between the synchronous body of the method and the `Task` that is spun off at the very end, we should probably be a little more diligent with the threading model here. We even had `@MainActor` on this task at some time, but may have pruned it a bit aggressively.
=> Fix potential threading issue in `Store.send`

Sources/ComposableArchitecture/Effect.swift
There's a very minor modification on API description of ``EffectOf``.
The description uses `EffectTask` in the code snippet, but it should be `Effect`.
I also searched for EffectTask, but there are no more results of its usage.
=> [FIX] Fixed API description to use the recent name: `EffectTask` -> `Effect`

README.md
Small for now, but we can add more later and solicit for folks to submit ones we don't know about.
=> Add README section for companion libraries

Examples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/TicTacToe.xcscheme, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/BindableStoreTests.swift
Because `@BindingViewState` is populated by a live store, there is no way to easily test `ViewState` structs that use `@BindingViewState`. This adds a `bindings` property on `TestStore` (`bindings(action:)` method when using view actions) that makes it possible to write assertions against view state.
=> Add `TestStore.bindings` for testing bindable view state

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-04-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-01-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-01-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-02-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-02-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-01-code-0006-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-01-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0015-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0015.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0016.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0017.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0018.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0005-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-NavigationStacks.tutorial
I believe that **`ContentView`** is a typo.
=> Fix the typos in the tutorial reference

Sources/ComposableArchitecture/Internal/NavigationID.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift
Right now, `ifLet` checks the presented state before and after it runs the parent reducer, and if it changes, it cancels any in-flight effects for the previous state. It will not, however, detect when child state changes _outside_ the parent reducer, _e.g._:
```swift
Reduce { state, action in
// ...
state.child = nil // or `= .someOther(child)`
}
Reduce { state, action in
// ...
}
.ifLet(\.$child, action: /Action.child) {
Child()
}
```
While we generally recommend structuring reducers in a way in which this doesn't happen, as a library we should attempt to improve the situation. In our case `@PresentationState` already uses some internal state to detect if it needs to install the child's dismiss effects, _e.g._ if it was deep-linked into at app launch. We can leverage this same state to …
=> Enhance `Reducer.ifLet` child effect cancellation

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-AddingSideEffects.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-TestingYourFeature.tutorial
The file names in the tutorial for the argument `previousFiles` were missing a suffix, resulting in a wrong file name and breaking the code diffs shown. This PR fixes those wrong file names.
All the changes were verified by building documentation in Xcode and the documentation previews in Xcode 15.
=> Fix Tutorials Code Diff

Sources/ComposableArchitecture/Dependencies/Dismiss.swift
Propose `dismiss(transaction:)`
=> feat: add dismiss with transaction

Sources/ComposableArchitecture/Dependencies/Dismiss.swift
File and line parameters were not passed along to the main implementation in `Dismiss.swift`.
=> Add missing file and line parameters to dismiss call

Tests/ComposableArchitectureTests/StoreTests.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
switch-case formatting with general with TCA code convention.
=> Get local value with 'let' in switch-case

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
Hi, while reviewing the PresentationReducer and StackReducer, I noticed that some of the documentation uses names like `ParentFeature / Parent` and `ChildFeature / Child` together, which can be a bit confusing. Throughout the library, the terms `Parent` and `Child` are more commonly used, including the tests.
For now, I've made the necessary changes, not in the test code. If you prefer me to rename every ParentFeature to Parent and ChildFeature to Child, please let me know. Additionally, I've considered changing the Reducer<State, Action> to `ReducerOf<Self>`. For the consistency, I've only modified what's in the PresentationReducer.swift. If you have any better suggestions or feedback, I'd love to hear them. Thanks!
=> Fix mismatched reducer names

README.md
Hi~!   
I corrected the README document because there was a part that could cause a syntax error.
Since `FeatureView` is not `Scene`, I wrapped it in `WindowGroup`.
Please check it out! 😊
=> correcting readme.md syntax

Sources/ComposableArchitecture/Internal/EphemeralState.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
Fixes #2463.
While receiving an action from another domain is a programmer error and will emit a runtime warning, we should avoid having this error negatively impact the end user experience by dismissing alerts and dialogs when they shouldn't be. This PR addresses things by expanding the ephemeral state protocol to describe its action type, and comparing this action type to whatever it can extract from the given action using CasePaths' enum metadata runtime APIs.
=> Only dismiss alert/dialog state when receiving a domain-specific action

Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md
I found a missing `)` in the documentation that'd be helpful to fix for others.
=> fix: documentation error for the getting started example

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
Fixed `self.path` to `state.path`
```swift
case let .path(.element(id: id, action: .editItem(.saveButtonTapped))):
-   guard case let .editItem(editItemState) = self.path[id: id]
+   guard case let .editItem(editItemState) = state.path[id: id]
else { return .none }
```
=> [Docs/StackBasedNavigation] Fixed `self.path` to `state.path`

Sources/ComposableArchitecture/ViewStore.swift
Rewrote `task.rawValue?.cancel()` instead of `task.rawValue?.cancel()` because `ViewStoreTask.cancel()` cancels the underlying task and also waits for the task to finish.
However, since the current `StoreTask.cancel()` only cancels the task, it is no longer necessary to write `task.rawValue?.cancel()`.
So, I changed the writing style to use `StoreTask.cancel()`.
=> Use `StoreTask.cancel()` instead of `task.rawValue?.cancel()`

Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Tests/ComposableArchitectureTests/DebugTests.swift
Prior to the `ReducerProtocol` we would queue print changes in the debug operator on reducers:
https://github.com/pointfreeco/swift-composable-architecture/blob/54c384581cd0ed395d4f314dfdaca14dc70acf4c/Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift#L118
We lost that in #1283, but we still used `fireAndForget` which had a sync overload, and so queuing just naturally happened on the main thread.
But, with 1.0 we got rid of `fireAndForget` and so instead used `run`, but then that introduced asynchrony and possible ordering issues with logs. So, currently it is possible for `actionA` to be sent before `actionB`, yet the logs for `actionB` will appear in the console before `actionA`.
This PR brings back the queue. Alternatively we could `@MainActor` the `run` effect. Each …
=> Bring back _printChanges queue.

Examples/Search/Search/SearchView.swift
The docs and code comments suggest that the debounce duration is 300ms, not 3 seconds. This small patch ensures the example works as described.
=> Fix search example debounce duration

Sources/ComposableArchitecture/Reducer/ReducerBuilder.swift, Tests/ComposableArchitectureTests/ReducerBuilderTests.swift
Discovered this while troubleshooting a Swift bug, but seems like we should allow the builder to promote an existential to an erased `Reduce`.
=> Allow existential reducers in builders

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/LegacyAlert.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Sources/ComposableArchitecture/ViewStore.swift, Sources/swift-composable-architecture-benchmark/StoreSuite.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Both an internal readability win and will make it easier to provide a public `state` property in the future.
=> Internal: rename `Store.{state,stateSubject}`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Effects/Animation.swift
Fixes #2539.
We expect reducers to be called on the main thread, so the transaction should hopefully be safe to commute across non-sendable boundaries, but we should keep this workaround in mind when we do polish TCA's sendability story in the future.
=> Silence SwiftUI sendability warning

Examples/CaseStudies/SwiftUICaseStudies/Internal/TemplateText.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift
=> Use `Text.init(verbatim:)` to avoid localization warnings

Package.swift, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/Reducer.swift
Since April, the apps and SDKs must be built in Xcode 14.1 + to submit to the AppStore. To support Xcode 14.1+, I modified the swift version to **5.7.1** from 5.7
> Reference: [developer.apple.com/news](https://developer.apple.com/news/?id=jd9wcyov)
After this changes, it no longer needs to worry about the apple-side bug that caused `ReducerOf` to specify support for versions 5.7.1+ : https://github.com/apple/swift/issues/60550
```swift
- #if swift(>=5.7.1)
public typealias ReducerOf<R: Reducer> = Reducer<R.State, R.Action>
- #endif
```
---
In addition, since April 2024, the apps and SDKs must be built in Xcode 15+ to submit to the AppStore.  Therefore, versions under 5.9 will no longer be needed to be supported after that date
> Reference: …
=> [FIX] Updated Swift compiler version to 5.7.1 to follow Apple's policy

README.md
The former version of Japanese translation was outdated. You can check it in the answer of FAQ part. It still talks about pullback which is now gone.
=> Update Japanese Translation of README.md

Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-Recursion.swift
HI loving the new macros in introduced in 1.4.0!
After studying how to use the new @Reducer macro with the CaseStudies example code, there seemed to be some unnecessary code left
As stated in the [docs](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/reducer()#overview), when a @Reducer macro is used, it applies the @CasePathable macro to the enum Action. 
however there seemed to be a unnecessary @CasePathable in one of the case studies so i removed it
Also, the docs says that when a @Reducer macro is used you no longer have to explicitly confrom to the Reducer protocol so i also removed it too. 
(not sure if this was intentional for making the compiler happy but every other example didnt explicilty conform Reducer)
=> Remove unnecessary Reducer conformance and @CasePathable macro in CaseStudies

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.4.md
As the title says, this PR fixes a typo in Migrating to 1.4.
=> Fix a typo in Migrating to 1.4

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.4.md
I found and fixed an error in the syntax of enum.
=> Fix syntax error in Migrate To 1.4.

Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift
TCA 1.4 perhaps unintentionally removed the `Reducer.forEach` code which allowed creating a `ForEachReducer` with a `AnyCasePath<Action, (ID, ElementAction)>` as the `action` parameter.
Unfortunately, it seems that:
`AnyCasePath<Action, (ID, ElementAction)>`, and 
`AnyCasePath<Action, (id: ID, action: ElementAction)>`
are not (always) considered equivalent by the Swift compiler.
The helper library, [TCACoordinators](https://github.com/johnpatrickmorgan/TCACoordinators), relies on the previous behaviour by passing an `AnyCasePath<Action, (ID, ElementAction)>`. I have tried updating TCACoordinators to use `AnyCasePath<Action, (id: ID, action: ElementAction)>`, but this has the effect of breaking TCACoordinators when used with TCA 1.3. Without re-adding this particular method, …
=> Re-adds `Reducer.forEach` method removed in 1.4

Package.swift
I think that `Package.swift` and `Package@swift-5.9.swift` should be the same and we should not pin `swift-case-paths` to given release by `branch:`.
Also it kinda breaks SPM in my project so that's how we were able to spot this issue.
=> Fix `swift-case-paths` being pinned to 1.1.0 the wrong way

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/TestStore.swift
This PR fixes links to the migration guide in deprecation messages.
=> Fix links to the migration guide

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.5.md
I found a typo in MigratingTo1.5.md and fixed it.
=> Fix typo in MigratingTo1.5.md

Sources/ComposableArchitecture/Observation/ObservationStateRegistrar.swift
Since it's a struct, its two sole stored members are also `Sendable`, this should be trivially safe.
=> Annotate `ObservationStateRegistrar` with `Sendable`

Sources/ComposableArchitecture/SwiftUI/NavigationStackStore.swift
This fixes an issue brought up in [Slack](https://pointfreecommunity.slack.com/archives/C04KQQ7NXHV/p1701187137240159?thread_ts=1701178804.247879&cid=C04KQQ7NXHV).
We only used `@StateObject` because we thought it would be a small performance improvement for caching stores, and since `NavigationStackStore` was already iOS 16+. But we have seen in the past the `@StateObject` introduces some really strange behavior, and we don't even need the caching behavior anymore since the `Store` takes care of that automatically.
=> Use @ObservedObject instead of @StateObject in NavigationStackStore.

Sources/ComposableArchitecture/Store.swift
Scoping can sometimes be invalid, _e.g._ SwiftUI may scope through an index of a collection that no longer exists while diffing in a `ForEach`, which can cause a crash when the child state is eagerly evaluated. This commit introduces the idea of an invalid store that will only crash if the store's state is interacted with, avoiding crashes that could happen deeper in SwiftUI.
=> Return "invalid" stores from scoping

Sources/ComposableArchitecture/Store.swift
1.5 introduced the store tree, which works well when the entire tree is cached, but can produce invalid stores when an uncached store caches a child store and is then reinitialized. While folks upgrading to 1.5 should be in a good state, adopting the new `scope` operator can introduce this problem. To mitigate, we should only cache from the root to nodes as far as the cache resolves.
This is a temporary limitation to avoid breaking existing apps. We should be able to remove this workaround when uncached scopes are fully deprecated and removed from the library.
=> Short-circuit the store cache from uncached stores

ComposableArchitecture.xcworkspace/xcshareddata/xcschemes/ComposableArchitecture.xcscheme, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift, Sources/Perception/Macros.swift, Sources/Perception/Perceptible.swift, Sources/Perception/PerceptionRegistrar.swift, Sources/Perception/PerceptionTracking.swift, Sources/Perception/WithPerceptionTracking.swift, Tests/ComposableArchitectureMacrosTests/MacroBaseTestCase.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateTests.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift, Tests/PerceptionMacrosTests/PerceptionMacrosTests.swift, Tests/PerceptionTests/PerceptionTests.swift, Tests/PerceptionTests/Tests.swift
Fixes the issue brought up [here](https://github.com/pointfreeco/swift-composable-architecture/discussions/2594?sort=new#discussioncomment-7734054).
Essentially when a binding's getter is accessed in SwiftUI, it does not happen in the call stack of the `AttributeGraph`. So, we will separately detect bindings and allow them to go by without a runtime warning. I was also able to get some test coverage on this which was nice.
=> Fix perception bindings

Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.5.md, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift
We mentioned how to subscript into identified actions in the testing section of the migration guide, but not the main section.
=> Update migration guide 1.5

Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Counter.swift, Examples/SyncUps/SyncUps/AppFeature.swift, Examples/SyncUps/SyncUps/RecordMeeting.swift, Examples/SyncUps/SyncUps/SyncUpDetail.swift, Examples/SyncUps/SyncUps/SyncUpForm.swift, Examples/SyncUps/SyncUps/SyncUpsList.swift, Sources/ComposableArchitecture/Observation/IdentifiedArray+Observation.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/NavigationLinkStore.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift, Sources/ComposableArchitecture/SwiftUI/SwitchStore.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift
These uncached operations can be problematic, especially when working with observation, which often depends on the stable identity of stores.
=> Deprecate closure-based `store.scope` operations

Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Use CaseKeyPath in test code where `@Reducer` is used.
=> Use CaseKeyPath in UnitTest.

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-YourFirstPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-MultipleDestinations.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-TestingPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-NavigationStacks.tutorial
While tutorials appear to compile just fine when files are referenced as strings and omitting the file suffix, it mysteriously breaks the diffing between each step. This PR fixes things.
=> Fix tutorial diffs

Sources/ComposableArchitecture/Reducer/Reducers/BindingReducer.swift
After discussion with Jon Shier (@jshier) on the Slack, he suggested making this change.
It appears to fix the key path getter error that was appearing when trying to archive a project using the `BindingReducer`.
I've tested a project which compiled but failed to archive on TCA 1.4 onwards, when macros were introduced, and this change allows it to compile and archive successfully.
For context, the Slack discussion is here: https://pointfreecommunity.slack.com/archives/C04KQQ7NXHV/p1702313629767679
This fix is entirely thanks to @jshier's suggestions! I take no credit for this!
=> Fix archiving problem since 1.4.0

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift, Tests/ComposableArchitectureTests/Internal/BaseTCATestCase.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/StoreLifetimeTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
A [Slack conversation](https://pointfreecommunity.slack.com/archives/C04KQQ7NXHV/p1702049135565039) pointed to a potential leak of the `Store` when it was executing an effect. This PR allows cancellation to properly propagate during deinitialization, and ensures that async effects don't strongly capture the store.
=> Fix Store leak when async effect is in flight

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreLifetimeTests.swift
This reverts commit b86012c82d6c75f29edd3b53d76a7f3910473412.
While we would like to adopt this change, it is incompatible with uncached stores, which are still the dominant kind of store these days.
We can revisit this in 2.0, when we have fully removed the old scoping operations and when stores have more defined lifecycles, cached in their parents.
=> Revert "Fix Store leak when async effect is in flight (#2643)"

Package@swift-5.9.swift, Sources/Perception/Internal/Locking.swift, Sources/Perception/Internal/Memoization.swift, Sources/Perception/PerceptionRegistrar.swift
This PR adds memoization to the calculation of `isInSwiftUIBody` during perception checks as originally discussed [here](https://github.com/pointfreeco/swift-composable-architecture/discussions/2620#discussioncomment-7768616).
This substantially increases performance while exercising an app in a simulator running iOS 16 (or older). In my standard test case of text input in a back-ported SyncUps app, typing a single character now only takes 0.0005 secs when the memoization cache has been pre-warmed.  It was previously taking approximately 0.15 secs after the fixes in #2622.
The memoization cache is built on top of an `OrderedDictionary` and caps the capacity to a fixed number of entries. As new entries are added, the oldest entry is evicted. In my experiments with SyncUps, fully exercising …
=> Implement memoization for perception checks

Sources/Perception/Internal/Memoization.swift, Sources/Perception/PerceptionRegistrar.swift
Just a few small updates to @scogeo's work on caching in the perception checks (see #2630). I've mainly just removed the stats and moved things around. I considered removing the `maxCapacity` entirely to keep things simple, but I do think it's necessary. The cache does get quite big over time.
=> Perception caching updates

Sources/ComposableArchitecture/Store.swift
Store rescoping optionalizes the action embedding in order to short-circuit actions sent from invalid bindings, but we can push that bit of logic into the reducer itself.
=> Refactor rescoping for non-optional action sending

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration/Legacy/LegacyPresentationTestCase.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/MigratingTo1.4.md
Came up on Slack. Tweaks the 1.4 migration guide a bit to note that `@CasePathable` is explicitly needed in some cases.
=> Migration guide: `@CasePathable` tweaks

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-01-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-01-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0001-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0005-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-03-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-ComposingFeatures.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-TestingPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/MeetComposableArchitecture.tutorial, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift
Realized that there was an opportunity to do a basic intro to composition during the essentials tutorial. And then the navigation tutorial provides a more advanced look into composition.
=> Basics of composition in the "essentials" tutorial

Sources/swift-composable-architecture-benchmark/Dependencies.swift, Sources/swift-composable-architecture-benchmark/StoreScope.swift, Sources/swift-composable-architecture-benchmark/StoreSuite.swift
The internal benchmarks package was no longer building in 5.7.
=> Fix package build in 5.7

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/scheduled-ci.yml, Examples/CaseStudies/SwiftUICaseStudies/CaseStudiesApp.swift, Examples/Integration/IntegrationUITests/EnumTests.swift, Examples/Integration/IntegrationUITests/IdentifiedListTests.swift, Examples/Integration/IntegrationUITests/NavigationTests.swift, Examples/Integration/IntegrationUITests/OptionalTests.swift, Examples/Integration/IntegrationUITests/PresentationTests.swift, Sources/ComposableArchitecture/Store.swift
This is a continuation of our work in #2664.
This PR cleans up a few of the internals of the revamped store scoping, including:
- It avoids a retain cycle between parent and child store. This retain cycle does not generally matter, as cached stores live as long as the lifetime of the app at this time, but in the future when we more proactively prune invalidated stores, it could prevent stores from being reinitialized.
- It brackets some debug codes to debug builds only.
- It cleans up some unused code.
=> Fix ownership between parent and child stores

Sources/ComposableArchitecture/Internal/SubscriptDefault.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/NavigationLinkStore.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift, Sources/ComposableArchitecture/SwiftUI/IfLetStore.swift, Sources/ComposableArchitecture/SwiftUI/NavigationStackStore.swift, Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift, Tests/ComposableArchitectureTests/ScopeCacheTests.swift, Tests/ComposableArchitectureTests/StoreFilterTests.swift
When scoping a store over a "presentation" boundary (optional, stack element, list element), we maintain a local, memoized value so that during dismissal, views still have access to the last element should SwiftUI render.
This PR introduces private subscripts so that these scopes can be done via key path.
=> Optimization: Key path subscript presentation scopes

Sources/ComposableArchitecture/ViewStore.swift
I noticed this when taking SyncUps for a spin on `main`. When I was editing an attendee and added a new one while the current attendee autocompleted, I'd get a warning in the `ViewStore`'s `sink` where `objectWillChange` was getting pinged during a render.
I'm pretty sure we should be dropping the first value from the `sink` to prevent `objectWillChange` from being pinged when the `ViewStore` is being initialized in the view.
=> Fix SwiftUI warning

Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift
I have a macro library that I'm developing for TCA that helps generate members of `Action` and `State`. This also requires that I manage the `AllCasePaths` struct when implementing `CasePathable` conformance.  The current `@Reducer` macro automatically applies the `@CasePathable` macro to the `Action` and `State` enums, even though my implementation has explicitly conformed to `CasePathable`.
For example the following code produces multiple compiler errors due to the application of `@CasePathable` to `Action` by the `@Reducer` macro, resulting in duplicate declarations of `AllCasePaths` and `allCasePaths`.
```swift
@Reducer
struct Feature {
// ...
enum Action: CasePathable {
struct AllCasePaths {}
static var allCasePaths: AllCasePaths { AllCasePaths() }
}
// ...
}
```
This PR changes the …
=> Updates @Reducer to no longer apply @CasePathable macro to enums with explicit conformance.

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
This commit improves the failure messaging for the new `TestStore.receive` method by rendering a diff of the value when the payload doesn't match up.
=> Improve `TestStore.receive(\.action, payload)` failures

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-02-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-04-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-01-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0000-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0000.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0004-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-04-code-0006.swift
Just removing all trailing whitespaces 😄
=> Prevent unnecessary diffs in the tutorials

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Store.swift
Right now we are "preparing" dependencies every time an action is sent, but we really only need to do it once when the `Store` is created.
=> Prepare dependencies a single time when creating Store.

.github/workflows/ci.yml
A simple `swift build` hopefully won't slow things too much.
=> Add CI for Swift 5.7.1

Makefile
We need to point to the latest OSes on GitHub for examples to build, and they recently updated their Xcode image.
=> Fix Examples CI

Sources/ComposableArchitecture/TestStore.swift
If you want to skip received actions before calling `assert`, you must do so explicitly.
=> Fix `TestStore.assert` docs

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.swift, Package@swift-5.9.swift, Sources/ComposableArchitecture/TestStore.swift
The test store has dynamically loaded this helper for awhile now, but now we can offload that work to another library.
=> Use `XCTExpectFailure` from `XCTestDynamicOverlay`

Sources/ComposableArchitecture/Documentation.docc/Articles/WhatIsNavigation.md
> It makes it possible to **expressive** navigation paths that are completely non-sensical.
should be
> It makes it possible to **express** navigation paths that are completely non-sensical.
Otherwise, it would be non-sensical. 😉
=> Documentation typo fix

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/04-ComposingFeatures/01-04-ComposingFeatures.tutorial
In Composing features of Tutorial Chapter 1, `AppFeatureTests` will not pass unless `State` is not conform to `Equatable`. So, I made `State` conform to `Equatable`.
https://pointfreeco.github.io/swift-composable-architecture/main/tutorials/composablearchitecture/01-04-composingfeatures/
=>  Fix Composing features tutorial; Modify Make the State conform to Equatable to pass the test.

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md
I have corrected a syntax error in MigratingTo1.7.md
=> Fix syntax error in MigratingTo1.7.md

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md
> You are most likely going to want to incrementally your application
should be:
> You are most likely going to want to incrementally **migrate** your application
otherwise, the sentence does not make sense.
Another proposal could also be:
> You are most likely going to incrementally migrate your application
=> Documentation: Fix a small typo in the 1.7 migration guide

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md
I noticed that there is no `var` keyword on the line where `isOn` is declared 🙂
=> Add missing `var` keyword to Migrating to 1.7 doc

Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/ReducerDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerOnChange.md, Sources/ComposableArchitecture/Reducer/Reducers/OnChange.swift
The `removeDuplicates` overload is just too tough on the compiler to resolve, so we don't think it's worth shipping in the library in the long run. SwiftUI's `View.onChange` doesn't have such an option, and adding such a signature results in the same compiler issues. Let's stick with the interface that most closely matches SwiftUI's and avoid interfaces that are problematic for the compiler.
=> Deprecate `Reducer.onChange(of:removeDuplicates:)`

Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Sources/ComposableArchitectureMacros/ViewActionMacro.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateMacroTests.swift, Tests/ComposableArchitectureMacrosTests/PresentsMacroTests.swift, Tests/ComposableArchitectureMacrosTests/ViewActionMacroTests.swift
`@ObservableState` macro was not support `package` access modifier.
| Before | After |
| :----: | :----: |
| ![before](https://github.com/pointfreeco/swift-composable-architecture/assets/9856514/3af133ad-0ced-4c4a-8957-b4b253ae4416) | ![after](https://github.com/pointfreeco/swift-composable-architecture/assets/9856514/02f7f4fa-0240-430f-9361-341ddd0da375) |
=> Support `package` access modifier for Observation architecture

Sources/ComposableArchitecture/Observation/Binding+Observation.swift
This is likely not the proper solution, but it does get my projects building.
=> Workaround for the build break on visionOS

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, .github/workflows/ci.yml, Makefile
Should catch regressions in visionOS builds.
=> Add visionOS CI

Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift
It was pointed out in the Slack that the `Codable` conformance was confusing and seems like a requirement, but neither `Codable` nor `Hashable` is necessary, so I think these conformances are vestigial and should be removed.
=> Simplify Stack Navigation Demo

Examples/CaseStudies/SwiftUICaseStudies/02-Effects-WebSocket.swift, Examples/CaseStudies/UIKitCaseStudies/Internal/IfLetStoreController.swift, Examples/Search/Search/SearchView.swift, Examples/TicTacToe/tic-tac-toe/Sources/LoginUIKit/LoginViewController.swift, Examples/TicTacToe/tic-tac-toe/Sources/NewGameUIKit/NewGameViewController.swift, Examples/TicTacToe/tic-tac-toe/Sources/TwoFactorUIKit/TwoFactorViewController.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-YourFirstFeature.tutorial, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Observation/Alert+Observation.swift, Sources/ComposableArchitecture/RootStore.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/LegacyAlert.swift, Sources/ComposableArchitecture/TestStore.swift, Sources/ComposableArchitecture/UIKit/AlertStateUIKit.swift, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
- `if/guard let x = x` -> `if/guard let x`
- Remove unneeded `self` from a few demos
- Fix up some presentation logic in TicTacToe
=> Some cleanup

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
=> Fix navigationDestinationWrapper in docs.

README.md
Adds TCAComposer to Companion libraries per @mbrandonw's [suggestion](https://github.com/pointfreeco/swift-composable-architecture/discussions/2766#discussioncomment-8351916).
=> Add TCAComposer to Companion libraries.

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.6.md
I found a small typo in migration guide 1.6 .
=> fix typo in migration guide 1.6

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md, Sources/ComposableArchitecture/Documentation.docc/Articles/ObservationBackport.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Observation/IdentifiedArray+Observation.swift
`ForEachStore` implicitly used `id: \.state.id` under the hood, so a naive migration to `ForEach` might miss this detail. Let's be more explicit in our documentation and migration guide to avoid this issue.
In the future it might be possible to address better in the library itself, but for now the requirement for stores to be identifiable for other forms of navigation means allowing for this.
=> Better document explicit `id` with scoped `ForEach`

Sources/ComposableArchitectureMacros/ViewActionMacro.swift, Tests/ComposableArchitectureMacrosTests/ViewActionMacroTests.swift
Right now availability on the parent is not propagated down to the extension, which can cause build failures.
=> Propagate `@ViewAction` macro availability

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md
I found a typo in the 1.7 migration guide.
=> Fix typo in the 1.7 migration guide

Sources/ComposableArchitecture/Observation/ObservableState.swift, Tests/ComposableArchitectureTests/ObservableTests.swift
It's possible for nested, inert enums to have the same "tag" and thus identity when they are distinct structures, which prevents cases changes from being observed. Let's allow tagging to happen recursively, which will allow for distinct identity in these cases.
=> Properly tag observable enums

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.8.md
=> Document `@Reducer(state: .equatable)` in the migration guide

Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj, Examples/Integration/Integration.xcodeproj/project.pbxproj, Examples/Search/Search.xcodeproj/project.pbxproj, Examples/SpeechRecognition/SpeechRecognition.xcodeproj/project.pbxproj, Examples/TicTacToe/TicTacToe.xcodeproj/project.pbxproj, Examples/Todos/Todos.xcodeproj/project.pbxproj, Examples/VoiceMemos/VoiceMemos.xcodeproj/project.pbxproj, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
This updates project files to use the dedicated setting rather than older flags. It also cleans up a few test warnings.
I started looking into fixing a bunch of new XCTest warnings in Xcode 15.3, but it's not clear to me what the correct path is [at the moment](https://forums.swift.org/t/swift-5-10-concurrency-and-xctest/69929).
=> Adopt complete concurrency and fix a few warnings

Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateMacroTests.swift, Tests/ComposableArchitectureMacrosTests/PresentsMacroTests.swift
Opening this PR per our discussion on Slack :) 
When using the following syntax:
```swift
public extension Feature {
@ObservableState
struct State { } 
}
```
A macro isn't able to determine `State` is public since the macro isn't aware of its surrounding context.
A solution to this is to always give the generated `_$id` and `_$willModify()` a public ACL, which should have no negative effect on other use cases.
=> [macro] Make _$id and _$willModify() public

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.8.md
Just add colon before the code clock.
=> A small change on migration guide 1.8

README.md
Hi folks 👋 
Just a small fix to the `README.md` file where `viewStore` was still being used within the UIKit code.
=> Replace usage of 'viewStore' with 'store' in UIKit code

Package.resolved, Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift, Tests/ComposableArchitectureTests/MacroTests.swift
Fixes #2824.
There is a Swift compiler/macro bug that causes the compiler to choke on constrained opaque types (e.g. `some Reducer<State, Action>`) when the `State` and `Action` are also generated by the macro. It doesn't happen in all situations, but something about enum reducers exacerbates the problem (perhaps it's cause of the `static var body`?).
The fix is to just not use opaque types in the macro generated code and instead expand the whole type for the `static var body`. It's a bit messy, but it works.
=> Fix macro compiler bug in release mode.

Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift, Tests/ComposableArchitectureTests/MacroTests.swift
=> More fixes for @Reducer macro.

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md
Just adding a missing opening brace in one of the examples in TreeBasedNavigation.md
=> Add missing opening brace in a TreeBasedNavigation example

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-01-code-0006.swift
Unnecessary diff were created by spaces, so spaces were added and diff were eliminated
=> fix unnecessary diff

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift
Hi, I thought this part should be `@Presents`, not `@PresentationState`.
The document just before says
> This version of `ifLet` requires the usage of the ``Presents()`` macro
so I thought maybe it should be `@Presents`.
=> fix document in PresentationReducer.swift

Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md
There were a few minor typos in the latter half of the Sharing State documentation I thought I could clean up.
=> Clean up some typos in SharingState.md

Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift
Came up on Slack.
These current disfavored overloads can lead to more difficult to debug error messages, like when trying to form a binding over bindable actions with state that isn't equatable.
=> Undisfavor some `Store[dynamicMember:]` overloads

Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift
This new reducer operator can be used to directly assign a dependency key value to the reducer's dependencies.
```swift
// Before;
@Dependency(\.apiClient) var apiClient
// ...
.dependency(\.apiClient, apiClient)
// After:
@Dependency(APIClient.self) var apiClient
// ...
.dependency(apiClient)
```
=> Add `Reducer.dependency(value)`

Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/ViewStore.swift
We currently scope in `WithViewStore.init`, which can lead to perception warnings. We can safely silence those.
=> Don't perception check in `WithViewStore`

Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateMacroTests.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift, Tests/ComposableArchitectureTests/EnumReducerMacroTests.swift, Tests/ComposableArchitectureTests/MacroTests.swift, Tests/ComposableArchitectureTests/ObservableStateEnumMacroTests.swift
This adds support for `#if` branching across enum cases in observable state and reducer enums.
=> Support `#if` branching in enum reducers/state

Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Version 1.9 introduced a new `Case` subscript to allow the `store.send(\.field, …)` syntax for binding actions, but that created potential ambiguity. This fixes #2874 and #2872.
=> Disfavor new subscript

README.md
This is trivial, but these migration guides are important yet a bit hard to find if you don't know the layout of the documentation. I've added links to the guides for each version alongside their documentation links.
=> Add Links to Migration Guides in README

Examples/CaseStudies/SwiftUICaseStudiesTests/01-GettingStarted-BindingBasicsTests.swift, Examples/SyncUps/SyncUpsTests/AppFeatureTests.swift, Examples/SyncUps/SyncUpsTests/SyncUpDetailTests.swift, Examples/SyncUps/SyncUpsTests/SyncUpsListTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/AppCoreTests/AppCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/LoginCoreTests/LoginCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/NewGameCoreTests/NewGameCoreTests.swift, Examples/TicTacToe/tic-tac-toe/Tests/TwoFactorCoreTests/TwoFactorCoreTests.swift, Examples/Todos/TodosTests/TodosTests.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Bindings.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.9.md, Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0011.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0012.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0013.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0014.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0016.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0017.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-TestingPresentation.tutorial, Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Tests/ComposableArchitectureTests/ObservableTests.swift
TCA 1.9 introduced a shorthand for accessing a case key path of a particular binding state directly:
```swift
store.send(\.name, "Blob")
```
This unfortunately regressed type-checking performance of downstream projects, which could lead to builds beginning to fail.
Because this introduction was a breaking change to some projects, we will remove it and instead folks should chain in from `\.binding`:
```swift
store.send(\.binding.name, "Blob")
```
=> Fix regression: remove `BindableAction` dynamic case lookup

Sources/ComposableArchitecture/SwiftUI/PresentationModifier.swift
Addresses the problem raised in #2907 where using legacy presentation APIs (e.g. `sheet(store:)`) result in the presented destination always receiving a store that does not support store caching due to the hardcoded `nil` ID given to the internal store that is created.
This prevents you from presenting features that uses observation tools using these APIs without lots of purple runtime warnings even though there's no reason why you shouldn't be able to do this.
Note: An [earlier implementation](https://github.com/pointfreeco/swift-composable-architecture/commit/087b6b5730df5494ec7cefa8add8ced89c645429#diff-a7aa3773363760502a84ef57acd54a1b745cee8cedad7a01a065bd9083546c7eL220) in of this logic used to have a comment stating that a `\.self` ID could not be used because it would prevent …
=> Give internal presentation store an id

Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift, Examples/Integration/Integration/Legacy/BindingLocalTestCase.swift, Examples/Integration/Integration/Legacy/NavigationStackTestCase.swift, Examples/Integration/Integration/iOS 16/NavigationTestCase.swift, Examples/Integration/Integration/iOS 17/ObservableBindingLocalTest.swift, Examples/Integration/Integration/iOS 17/ObservableNavigationTestCase.swift, Examples/SyncUps/SyncUps/AppFeature.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/Navigation.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerForEach.md, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/ScopeLoggerTests.swift
It turns out that this typealias is not real, and now real.
https://github.com/pointfreeco/swift-composable-architecture/blob/a0acf426f7e8e794563b6bcbe4fcf5a9fd6cebef/Sources/ComposableArchitecture/Observation/NavigationStack%2BObservation.swift#L22
=> Add `StackActionOf`

Examples/Integration/IntegrationUITests/Internal/BaseIntegrationTests.swift, Examples/Integration/IntegrationUITests/iOS 16+17/NewContainsOldTests.swift, Examples/Integration/IntegrationUITests/iOS 16+17/NewPresentsOldTests.swift, Examples/Integration/IntegrationUITests/iOS 16+17/OldContainsNewTests.swift, Examples/Integration/IntegrationUITests/iOS 16+17/OldPresentsNewTests.swift, Sources/ComposableArchitecture/Observation/ObservableState.swift, Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateMacroTests.swift, Tests/ComposableArchitectureTests/ObservableTests.swift
Fixes #2887 and #2899.
Right now we think of non-`@ObservableState` as "inert" in that its ID never changes. Really it should be the opposite. Non-`@ObservableState`'s ID should change every time you ask it for an ID so that it forces the view to always re-render.
We thought we had already made this change, but perhaps it was in one of our experiments that didn't get merged.
=> Change "inert" state to have an ever-changing ID

Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-01-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/01-YourFirstFeature/01-01-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-01-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-03-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-01-code-0003-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-01-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/03-TestingYourFeatures/01-03-TestingYourFeature.tutorial, Sources/ComposableArchitecture/TestStore.swift
This fixes some old DocC references to the proper overload and as suggested in #2808 defers the introduction of equatable state to the testing section of the tutorial.
=> Test store tutorial/documentation fixes

Sources/ComposableArchitecture/SharedState/PersistenceKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/InMemoryKey.swift, Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift, Tests/ComposableArchitectureTests/SharedTests.swift
This PR modifies the `PersistenceKey` protocol so that its `load` and `subscribe` endpoints are handed the initial value and must return a non-optional value. By feeding this value in, we can ensure that `.appStorage` declared in a feature is registered outside the feature.
=> Pass initial shared value to strategy / register app storage

Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/ReducerTests.swift
Due to a Swift bug, stores and test stores initialized with type inference are broken when it comes to autocomplete:
https://github.com/apple/swift/issues/72399
For example, this test store cannot be completed from:
```swift
let store = TestStore(initialState: Feature.State()) {
Feature()
}
```
While this can affect regular stores, as well, it is less likely outside of root stores, since stores are typically declared in views and view controllers as properties, and inference isn't required:
```swift
let store: StoreOf<Feature>
```
While the user can employ a workaround in their project by making the types very explicit:
```diff
-let store = TestStore(initialState: Feature.State()) {
+let store: TestStoreOf<Feature> = TestStore(initialState: Feature.State()) {
Feature()
}
```
This PR takes …
=> Swift bug workaround for `TestStore` completion

Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift
This adjusts the `@Reducer` macro to expand extra `case feature(Never)` for actions that aren't TCA features.
This allows folks to scope down to stores of non-features for sheets, etc.:
```swift
.sheet(
item: $store.scope(state: \.meeting, action: \.meeting)
) { meetingStore in
// Must use 'Store.withState' here for non-observed feature.
MeetingView(meeting: meetingStore.withState(\.meeting))
}
```
=> Enum reducers: generate `Never` actions for non-features

Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift
Addresses https://github.com/pointfreeco/swift-composable-architecture/discussions/2936
I'm not sure why the access modifier inserts a leading line break but that seems to have been the case already for `public` so I've left it as is.
Shout if anything needs tweaking!
=> Add package access modifier support to @Reducer on enums

Package.swift, Package@swift-5.9.swift, Sources/ComposableArchitecture/PrivacyInfo.xcprivacy
Food for thought: GRDB recently, added a Privacy manifest file which is explicitly shows no tracking. That PR is [here](https://github.com/groue/GRDB.swift/commit/1920482158af699c6b3a55860b7697f91a318bf8). This may seem pointless, but I suspect it will be best practice going forward. By explicitly saying that our library does not track the user, we reduce the surface area that devs need to search for compliance. 
Thankfully it looks like Apple added a privacy reason which perfectly matches our use case: 
- `C56D.1`: https://arc.net/l/quote/aqxlpvkx
> Declare this reason if your third-party SDK is providing a wrapper function around user defaults API(s) for the app to use, and you only access the user defaults APIs when the app calls your wrapper function.
My guess is that this reason will …
=> Added Privacy Manifest file

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Effects/Publisher.swift
Makes the trailing closure of `Effect.publisher { … }` non-escaping, and hence the publisher is created eagerly when the effect is constructed. This means you can access `state` inside the closure, which will be handy in the shared state tools coming to TCA soon:
```swift
return .publisher { 
state.$shared.publisher
.map(Action.sharedUpdated)
}
```
Note, however, the publisher is not _run_ eagerly. That is still delayed until state changes have been processed and all effects are started together.
We don't think there is a big use case for needing the construction of a publisher to be lazy since the publisher itself can encapsulate lazy work, but if for whatever reason one needs to lazily create the publisher then you can use `Deferred`:
```swift
return .publisher {
Deferred {
// create …
```
=> Make Effect.publisher eager

Sources/ComposableArchitecture/Internal/NotificationName.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
This was brought up by @jegnux in [Slack](https://pointfreecommunity.slack.com/archives/C04L56P2VEF/p1712753624317759?thread_ts=1712534913.585879&cid=C04L56P2VEF). Right now observation of user defaults is broken if someone uses a "." in their key, e.g. `@Shared(.appStorage("pointfree.isOn"))`. To fix we will use `NotificationCenter` to subscribe to the whole firehose of _any_ change to `UserDefaults`. 
Now technically this does mean we could be playing back changes to `@Shared` when the key does not actually change. We can't easily de-dupe the `didSet` from within `AppStorageKey` because we don't have access to the current value. So we could explore doing some de-duping in `ValueReference`, but then we'd need to cast to `any Equatable` and open the existential. That might be worth it …
=> Use notification center instead of KVO for user defaults observation.

Sources/ComposableArchitecture/SharedState/PersistenceKey.swift
This makes `Shared.Subscription.cancel` public so that we can wrap a `PersistenceKey` and correctly implement `subscribe(initialValue:didSet:)`.
See https://github.com/pointfreeco/swift-composable-architecture/discussions/2857#discussioncomment-9087925
=> Make Shared.Subscription.cancel public

Sources/ComposableArchitecture/Internal/NotificationName.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
This was brought up a few weeks ago and then again today in discussions and we just never got around to it.
=> Save to file storage when app is about to be terminated

Examples/SyncUps/SyncUps/AppFeature.swift, Examples/SyncUps/SyncUps/Meeting.swift, Examples/SyncUps/SyncUps/Models.swift, Examples/SyncUps/SyncUps/RecordMeeting.swift, Examples/SyncUps/SyncUps/SyncUpDetail.swift, Examples/SyncUps/SyncUps/SyncUpForm.swift, Examples/SyncUps/SyncUps/SyncUpsList.swift, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift, Sources/ComposableArchitecture/SharedState/Shared.swift, Sources/ComposableArchitecture/SharedState/SharedChangeTracking.swift, Sources/ComposableArchitecture/TestStore.swift
In #2976, shared state snapshots were moved off the `Shared` reference and into the change tracker, which allowed multiple change trackers to observe changes independently, but not concurrently, so when change trackers observed changes in a nested fashion, the outer trackers would fail to observe some changes. This was mainly a problem for testing reducers that also had `_printChanges()` attached to them.
This PR makes the following changes:
- Change tracking is now done by a set of trackers that are added/removed from a task local pool for the duration of their scoped tracking
- Change tracker assertions are synchronously scoped to a single tracker and the changes it observed
=> Shared change tracking enhancements

Examples/SyncUps/SyncUpsTests/AppFeatureTests.swift, Sources/ComposableArchitecture/SharedState/Shared.swift, Sources/ComposableArchitecture/SharedState/SharedChangeTracking.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/SharedTests.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift
This tweaks shared change tracking a bit further:
1. Test stores now maintain their own, isolated change trackers instead of sharing the default test change tracker
2. Test stores now emit state-related failures on `deinit` when shared state changes before the end of the test but wasn't asserted on (_e.g._ in an effect)
=> Better shared state change tracking and `TestStore` interactions

Sources/ComposableArchitecture/UIKit/NSObject+Observation.swift, Tests/ComposableArchitectureTests/ObserveTests.swift
It is possible for `observe` to be invoked inside an `observe` closure, especially if a view controller navigates to another view controller from its `observe`. This can lead to the parent `observe` over-observing all the child access/mutation.
Let's runtime warn to detect this problem so that folks can better avoid it.
=> Runtime warn for nested `observe` calls

README.md
Just updating the readme to reflect the UI on Xcode 15.3
=> README.md: Update package addition wording to match latest Xcode

Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md
There is a small typo in the shared-state examples. This PR fixes that. A computed property property should use the `var`-keyword instead of `let`.
Keep up the good work!
=> fix typo in examples: `let` -> `var`

Package.resolved, Package.swift, Package@swift-5.9.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift
I was digging around in the internals of the library, and I noticed this comment about removing this `@unchecked` when Swift Collections 1.1 is released.
I checked, and it has been released now. So I've updated TCA's dependency version, removing the `@unchecked` bit of `StackState`'s `Sendable` conformance.
This does have the potentially unfortunate side effect of needing to update the minimum Swift version to 5.7.2 from 5.7.1, as Swift Collections 1.1 bumps its minimum Swift version: https://github.com/apple/swift-collections/releases/tag/1.1.0
=> Remove `@unchecked` from `StackState`'s `Sendable` conformance

Package.resolved, Package.swift, Package@swift-5.9.swift
The `swift-custom-dump@1.2.1` contains a fix to prevent crashes during release builds that occurred with Xcode 15.3.
https://github.com/pointfreeco/swift-custom-dump/releases/tag/1.2.1
I noticed that this fix was already included in the Shared State's PR, but I created this PR because I thought this fix might should be released earlier.
=> Updated swift-custom-dump to latest version

Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
If the observed value in `UserDefaults` is a `RawRepresentable` type, simply casting to `Value` might fail because the raw representing type could be different from `Value`.  Instead of querying `UserDefaults` directly here, we should call `loadValue()` which will do the right thing for raw representable types (esp. try to call `Value.init(rawValue:)` with the value obtained from `UserDefaults`).
Or am I missing something and there is a reason this is using `UserDefaults.value(forKey:)` directly?  I am especially curious because `CastableLookup` on line 374 is using `UserDefaults.object(forKey:)` instead, so it does look somewhat deliberate.
=> Don’t assume CastableLookup

Examples/SyncUps/SyncUps/App.swift, Examples/SyncUps/SyncUpsTests/AppFeatureTests.swift, Sources/ComposableArchitecture/Documentation.docc/Extensions/AppStorageKey.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/FileStorageKey.md, Sources/ComposableArchitecture/Internal/Deprecations.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift, Tests/ComposableArchitectureTests/ObserveTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Previously, we had a public protocol and conformances, but we don't expect anyone to conform outside the library, so instead let's hide things in a more opaque struct.
The downside of this PR is that it's a breaking API change pretty late in the game:
```diff
-$0.defaultFileStorage = InMemoryFileStorage()
+$0.defaultFileStorage = .inMemory
```
We could add public deprecated functions that emulate the old initializers if we think it's worth it...
=> Make `FileStorage` more opaque

Sources/ComposableArchitecture/CaseReducer.swift, Sources/ComposableArchitecture/Documentation.docc/Extensions/ReducerBody.md, Sources/ComposableArchitecture/Reducer.swift
This type was mainly introduced to improve Xcode autocomplete of the `body` property, but since the `@Reducer` macro we don't really get any autocomplete anyway...
=> Remove `Reducer._Body` workaround

Sources/ComposableArchitecture/Resources/PrivacyInfo.xcprivacy
Revision of: https://github.com/pointfreeco/swift-composable-architecture/pull/2930
Per: https://github.com/pointfreeco/swift-composable-architecture/issues/3021
The Xcode behavior appears to be different from when I submitted PR 2930. I originally created the manifest without NSPrivacyCollectedDataTypes (since TCA is not actually collecting anything) and Xcode generated an empty Privacy Report. 
Now it generates the error `Missing an expected key: 'NSPrivacyCollectedDataTypes'`
I've now added the key in however, it no longer generates an empty Privacy Report, so I think it needs to be a library decision how we proceed. Here's the new generated report. 
According to this we are collecting "other" data even though TCA isn't collecting anything and even though we already have an …
=> Add missing NSPrivacyCollectedDataTypes to PrivacyInfo.xcprivacy

Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
=> Fix @Shared initializer with default nil.

Sources/ComposableArchitecture/Observation/Store+Observation.swift
Currently, popping two layers in a nav tree will cause intermediate, invalid stores to send `dismiss` actions when they shouldn't. This branch avoids this by checking the store's validity before sending the action along.
Fixes #3031.
=> Don't warn when dismissing two layers of tree nav

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package@swift-5.9.swift, Sources/ComposableArchitecture/Observation/ObservationStateRegistrar.swift
Perception 1.1.6 introduced availability changes intended to prevent crashes in iOS 17.0 beta users, but had unintended downstream consequences in projects with a minimum deployment target of 17.0 (in particular these projects began to emit runtime warnings when they shouldn't have), and so it was reverted. This PR is a follow-up that pins to the latest Perception 1.1.7, which reverts these checks.
=> Revert perception availability changes

Tests/ComposableArchitectureTests/StoreTests.swift
Adds a test for the behavior added in #3037.
=> Add test for store invalidation.

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, .github/package.xcworkspace/xcshareddata/xcschemes/ComposableArchitecture.xcscheme, Package.resolved, Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.4.md
This came up recently and I was hoping to point to a part of the migration guide that explained it, but it didn't exist.
=> Add `@CasePathable @dynamicMemberLookup` to 1.4 migration guide

Examples/SyncUps/SyncUpsTests/RecordMeetingTests.swift, Examples/SyncUps/SyncUpsTests/SyncUpDetailTests.swift, Sources/ComposableArchitecture/Documentation.docc/Extensions/TestStore.md, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/TestStoreTests.swift
Right now, if a leaf feature is tested and it dismisses itself while effects are in-flight, the only way to get tests passing is to explicitly tell the store or any tasks returned by `store.send` to cancel. Further, you must use an expectation in such tests to assert that `dismiss` was called in the first place.
This PR changes this behavior to automatically cancel a test store's effects if it is dismissed, and it prohibits sending more actions to it after dismiss has been called.
=> Cancel `TestStore` effects when root feature is dismissed

Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StoreTests.swift
Right now we only propagate dependencies to the reducer in `Store` when using the `withDependencies` trailing closure. But let's do it all the time for when one needs to do `withDependencies { Store }`.
=> Propagate dependencies to reducer all the time.

Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
If SwiftUI writes to a binding and the state is invalid (it is not inserting or removing elements from the stack), then the most likely cause is a missing `forEach` in the reducer (or a missing integration in some parent reducer).
This commit adds a runtime warning to detect this issue:
=> Runtime warn when stack integration is missing from store's reducer

Sources/ComposableArchitecture/Documentation.docc/Articles/Testing.md, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/SharedTests.swift, Tests/ComposableArchitectureTests/TestStoreFailureTests.swift
`store.finish()` should do much of the same work as `store.deinit`, but asynchronously with a timeout. This PR updates things so that folks with long-living test stores (_e.g._ held onto by the test case) have the ability to assert that there are no unreceived actions.
=> Have `store.finish()` assert no received actions

Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift
Reduce unnecessary code execution by enabling customDump only in debug mode, as in .run Effect. 
https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/Effect.swift#L101
=> Enable customDump only in debug mode

Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/SharedTests.swift
Extends PR #3057 to include initial values in addition to default values.
Persistent Shared values are often declared with an initial value.
```swift
@Shared(.appStorage("key")) var value = 0
```
This initial value is eagerly evaluated and passed to the Shared initializer. When there's an existing reference, this initial value is thrown away. For simple types like the one above, this isn't a problem. However, when the initial value is more complex, it can be wasteful if the Shared value is declared in many features of an app.
More significantly, the initial value may have side effects. For example, consider a `Folder` model that creates a `UUID` id using the `uuid` dependency. If you want to persist the `Folder`, you would declare a `PersistenceKey`.
```swift
extension PersistenceKey …
```
=> Lazy loading of Shared initial values

Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps.tutorial
Fixes #3073.
We've had a few people confused about the tagged digression, so I added a note to clarify that we will not be using `Tagged` for the rest of the tutorial. It's just a side quest. If it continues to be confusing we should consider just removing it from the tutorial.
=> Clarify that tagged is not assumed in the tutorial.

Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation.tutorial
Minor typos I noticed while reading the new SyncUps tutorial.
=> SyncUps: typos fixes

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md
The 1.7 guide doesn't have examples of more complex bindings, so let's add one.
Trying out the column-based format:
---
=> Add `ViewStore.binding` migration examples to guide

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Store.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/SwiftUIIntegration.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/04-PresentingSyncUpForm/PresentingSyncUpForm.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/06-SyncUpDetail/EditingAndDeletingSyncUp.tutorial, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
We recently added a warning when we detect that `forEach` wasn't integrated with a reducer when path elements are pushed or popped from the stack, and I realized that we could do similarly for `ifLet` during dismissal.
=> Add `ifLet` SwiftUI integration warning

Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
When using AppStorageKey persistence strategy with the Value associated type `URL` or `URL?`, saving values to UserDefaults causes a NSInvalidArgumentException exception to be thrown. To avoid it, dedicated APIs for saving and retrieving URLs to/from UserDefaults need to be used.
=> Fix exception when using AppStorageKey with URL Value

Sources/ComposableArchitecture/Internal/StackIDGenerator.swift, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift
I'm working on back-porting iOS 16 NavigationStack and every TCA related apis. I managed to make a demo [here](https://github.com/Alex293/swift-composable-architecture/tree/observable-navigation-backport) but I needed to `@testable  import ComposableArchitecture` 
This branch contains the apis required but keep them behind `@_SPI(Internals)` as the rest of those apis.
=> Add @_SPI(Internal) to some more navigation apis

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-MultipleDestinations.tutorial
* While following the tutorial, I noticed an incorrect file reference `02-02-02-code-0011-previous.swift`, which has been corrected to `02-02-02-code-0012-previous.swift`.
#
Thank you for your time and attention in reviewing this PR. I hope this helps improve the tutorial for everyone! 🙇🏻‍♀️
=> Fix typo in tutorial file reference for ContactsFeatures.swift

Sources/ComposableArchitecture/Effects/Cancellation.swift
This PR adds missing syntax highlighting to the `withTaskCancellation(id:cancelInFlight:operation:)`'s comment.
=> Add syntax highlighting

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-YourFirstPresentation.tutorial
The "Meet the Composable Architecture" tutorial was not updated to make use of `@Shared`, and one could argue that maybe it shouldn't. It should be just a very basic introduction to the library, and it may be too advanced to jump into state sharing topics.
However, that does lead people to believe that delegate actions are the only way to achieve what we do in the tutorial, so I have added a note to make it clear that is not the case.
=> Add important note about delegate actions.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/SharedState/Shared.swift, Sources/ComposableArchitecture/SharedState/SharedReader.swift
Currently, `Shared`'s dynamic member lookup is overloaded for convenience:
```swift
$shared                // Shared<Root>
$shared.value          // Shared<Value>
$shared.optionalValue  // Shared<Value>?
```
Unfortunately, this is also perhaps surprising, and goes against the grain when folks might expect to be handed a `Shared<Value?>`.
Also, there are times when you have a `Shared<Value?>` already, and you want to unwrap it. Dynamic member lookup doesn't help there (unless you know you can call `$shared[dynamicMember: \.self]`), and so you need a totally different operation to handle it:
```swift
if let unwrappedShared = Shared($optional) {
// Do something with 'Shared<Value>'
}
```
So let's avoid this confusion in the future and focus on a single API for unwrapping shared values, which …
=> Deprecate `Shared`'s optional dynamic member lookup overload

Sources/ComposableArchitecture/SharedState/Shared.swift, Sources/ComposableArchitecture/SharedState/SharedReader.swift
Inspired by #3124, this helper may help when needing to provide `SharedReader` values in previews and tests.
At the end of the day it is only a helper for doing `Shared(value).reader`, so maybe not worth it.
=> Add a SharedReader.constant helper.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/SyncUps/SyncUps/RecordMeeting.swift, Examples/SyncUps/SyncUpsTests/AppFeatureTests.swift, Examples/SyncUps/SyncUpsTests/SyncUpDetailTests.swift, Examples/SyncUps/SyncUpsTests/SyncUpsListTests.swift, Package@swift-5.9.swift, Sources/ComposableArchitecture/Internal/NavigationID.swift, Sources/ComposableArchitecture/Internal/PresentationID.swift, Sources/ComposableArchitecture/Observation/ViewAction.swift, Sources/ComposableArchitectureMacros/Extensions.swift, Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Sources/ComposableArchitectureMacros/ReducerMacro.swift, Sources/ComposableArchitectureMacros/ViewActionMacro.swift
The Xcode 16 beta generates macro projects using these swift-syntax snapshots. Luckily things seem to be backwards compatible, so we can expand our supported range.
=> Support swift-syntax from 600.0.0-latest

Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/01-WhatIsSyncUps/WhatIsSyncUps.tutorial
This PR fixes extension typos in 01-WhatIsSyncUps.
=> Fixed extension typos in the Building SyncUps tutorial

Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
`AnyCasePath` closures will be required to be `@Sendable` for Swift 6 data race checking, but `Enum.case` functions are not `@Sendable` implicitly. As such we cannot pass `Enum.case` directly to functions that expect sendable closures. Instead, we must explicitly write:
```swift
{ .case($0) }
```
=> Don't pass embed functions directly to `AnyCasePath.init`

Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/SharedTests.swift
This PR allows deleting elements from an `AppStorageKey` when it loads with a **non-null** value and we attempt to delete that value in persistence.
=> Share state appstorage nullable

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.11.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.12.md, Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md, Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md, Sources/ComposableArchitecture/SharedState/Shared.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift, Tests/ComposableArchitectureTests/SharedTests.swift
Details in the migration guide.
=> Make withLock main actor.

Sources/ComposableArchitecture/UIKit/AlertStateUIKit.swift
Now resides in swiftui-navigation repository: https://github.com/pointfreeco/swiftui-navigation/blob/uikit-navigation-beta/Sources/UIKitNavigation/Navigation/UIAlertController.swift
=> Remove duplicate UIAlertAction convenience initializers

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
I've moved all of the state for throttling to a single struct that is isolated rather than a bunch of isolated fields. I also fixed an edge case bug where one could delete the persisted file while a throttling task is inflight. We now cancel that task.
=> Some improvements to throttling

Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift
Discovered a minor typo in the `ifCaseLet` documentation. Cheers:)
=> Fix minor typo in ifCaseLet documentation

Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift
While checking out the UIKit CaseStudies, I noticed that a couple of ViewControllers were missing the `final` keyword.
I didn't see any subclassing, and all the other ViewControllers seem to have `final`, so I assumed it was an oversight. Let me know if I'm missing something 👍
=> Add `final` to `UIViewController`s in UIKit CaseStudies

Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift
I have improved the ListsOfState example.
The `tableView(_:cellForRowAt:)` delegate method can be called multiple times for the same indexPath, and in the current code, the `observe(_:)` method is executed multiple times for the same indexPath.
When the `observe(_:)` method is executed multiple times, the closure is called unnecessarily many times when the Counter model at the corresponding index is changed.
To prevent this, I have added the observation cancellation logic.
=> Improve UIKit case studies: ListsOfState

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
Considering the context, this should be named `store`.
=> Fix variable naming in StackBasedNavigation.md

Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift, Examples/CaseStudies/UIKitCaseStudies/Internal/IfLetStoreController.swift, Examples/CaseStudies/UIKitCaseStudies/ListsOfState.swift, Examples/CaseStudies/UIKitCaseStudies/LoadThenNavigate.swift, Examples/CaseStudies/UIKitCaseStudies/NavigateAndLoad.swift
I noticed that a few ViewControllers in the UIKit example code had some methods and properties that could be hidden. 
I also thought the stores would be better off hidden as well. (Please give me your thoughts if you think they should be left alone. )
Cheers🙂
=> Hide UIViewController method/properties in UIKit Example code

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitectureMacros/ReducerMacro.swift, Tests/ComposableArchitectureMacrosTests/ReducerMacroTests.swift
Currently, the following reducer enum:
```swift
@Reducer
enum Destination {
case alert(AlertState<Never>)
}
```
Generates the following action:
```swift
@CasePathable
enum Action {
case alert(AlertState<Never>.Action)
}
```
And this produces a warning in Case Paths 1.5 due to the nested `Never` not being referenced directly.
This PR plucks the action type out and embeds it directly, instead:
```diff
-case alert(AlertState<Never>.Action)
+case alert(Never)
```
Which will allow us to better suppress warnings Swift emits for uninhabited types.
=> Enum reducers: generate direct action cases for ephemeral state

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.11.md, Sources/ComposableArchitecture/Internal/DispatchQueue.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKeyPathKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/PersistenceKeyDefault.swift, Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
This fixes an issue brought up here: https://github.com/pointfreeco/swift-composable-architecture/discussions/3182#discussioncomment-9841265
In order for a `@Shared` value to subscribe to changes to an external system (e.g. file system, user defaults, etc.), one uses the `subscribe` endpoint and feeds data to `didSet`. Sending data to `didSet` ultimately mutates the `@Shared` value and triggers SwiftUI re-renders, and so that should take place on the main thread.
This enforces that contract by making the `didSet` argument `@MainActor`. It is _technically_ a breaking change, but really it's a bug fix. This is a problem people may have in their custom persistence strategies right now, and they may want to investigate how to fix them.
=> Make 'didSet' main actor.

Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
This PR generalizes the `fileStorage` persistence key so that it can be used with values that are not `Codable`, by adding the ability to provide custom decode/encode closures as parameters. Also, for `Codable` values, the json decoder/encoder can now be customized.
=> Add support for custom decoding/encoding to `fileStorage`

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/01-Essentials/02-AddingSideEffects/01-02-02-code-0004.swift
This PR fixes a typo in Tutorial. According to the documentation for [String.init(decoding:as:)](https://developer.apple.com/documentation/swift/string/init(decoding:as:)), this initializer never returns `nil`.
=> Fix a typo in Tutorial

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/ComposableArchitecture/Documentation.docc/Articles/SharingState.md, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift
While we should get both dependencies picked up from swift-dependencies' exports, we've heard reports from folks that they're getting linker/symbol errors here:
https://github.com/pointfreeco/swift-issue-reporting/issues/100
We should update these uses regardless!
=> Reference IssueReporting symbols instead of XCTestDynamicOverlay

Sources/ComposableArchitecture/SwiftUI/Alert.swift, Sources/ComposableArchitecture/SwiftUI/ConfirmationDialog.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/ActionSheet.swift, Sources/ComposableArchitecture/SwiftUI/Deprecated/LegacyAlert.swift
fixes small typos on `alert` and `confirmationDialog`
=> fix typos in on `alert`

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/SyncUps/SyncUpsTests/SyncUpFormTests.swift, Sources/ComposableArchitecture/Internal/AssumeIsolated.swift, Sources/ComposableArchitecture/Internal/DispatchQueue.swift, Sources/ComposableArchitecture/SharedState/Shared.swift, Tests/ComposableArchitectureTests/DebugTests.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift, Tests/ComposableArchitectureTests/Reducers/ForEachReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/SharedTests.swift, Tests/ComposableArchitectureTests/TaskResultTests.swift, Tests/ComposableArchitectureTests/TestStoreNonExhaustiveTests.swift
We have a few warnings, mostly in the test suite, that have cropped up with deprecations and Xcode 16 strict concurrency, so let's address them.
=> Fix some warnings

Sources/ComposableArchitecture/Observation/Store+Observation.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
This regression was introduced to fix a UIKit warning, but it causes state to not be `nil`'d out in SwiftUI. Luckily we caught it before a release.
=> Fix ephemeral dismissal

Package.resolved, Package.swift
Update links for repositories moved to the swiftlang org on GitHub
+ Package.resolved
+ Package.swift
Correct the link:
+ https://github.com/apple/swift-docc-plugin => https://github.com/swiftlang/swift-docc-plugin
+ https://github.com/apple/swift-docc-symbolkit => https://github.com/swiftlang/swift-docc-symbolkit
=> Update swiftlang repository link for Package.swift, Package.resolved

Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Tests/ComposableArchitectureTests/AppStorageTests.swift
Potential fix for the issue https://github.com/pointfreeco/swift-composable-architecture/issues/3247
=> Fix: Crash when writing to user defaults in background thread

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration/IntegrationApp.swift, Examples/Integration/Integration/iOS 16+17/NewContainsOldTestCase.swift, Examples/Integration/Integration/iOS 17/ObservableBindingLocalTest.swift, Examples/Integration/IntegrationUITests/Internal/BaseIntegrationTests.swift
This gets the Integrate test suite compiling and passing again. Maybe someday soon we can add it back to CI.
=> Fix integration tests.

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.swift, Sources/ComposableArchitecture/UIKit/NSObject+Observation.swift
We accidentally lost the `observe` function on AppKit with a recent release, and so we are bringing it back directly in TCA. Eventually this function will move to swift-navigation once that library fully supports AppKit.
=> Bring back 'observe' for non-UIKit targets.

Sources/ComposableArchitecture/Documentation.docc/Articles/TreeBasedNavigation.md
I found that the `onNavigate` closure isn’t being passed a parameter and is only being called when `isActive` is true.
I believe the `onNavigate` closure should also be called when isActive becomes false 🤔
=> Add missing parameter in NavigationLink docs

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
2.1.0 restores the ability for TCA AppKit apps to access the `observe` function.
=> Bump Swift Navigation

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/Integration/Integration.xcodeproj/project.pbxproj, Examples/Integration/Integration/IntegrationApp.swift, Examples/Integration/Integration/Test Cases/MultipleAlertsTestCase.swift, Examples/Integration/IntegrationUITests/Legacy/BindingLocalTests.swift, Examples/Integration/IntegrationUITests/Legacy/EscapedWithViewStoreTests.swift, Examples/Integration/IntegrationUITests/Legacy/ForEachBindingTests.swift, Examples/Integration/IntegrationUITests/Legacy/IfLetStoreTests.swift, Examples/Integration/IntegrationUITests/Legacy/LegacyNavigationTests.swift, Examples/Integration/IntegrationUITests/Legacy/LegacyPresentationTests.swift, Examples/Integration/IntegrationUITests/Legacy/SwitchStoreTests.swift, Examples/Integration/IntegrationUITests/Test Cases/MultipleAlertsTests.swift, Examples/Integration/TestCases/TestCase.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
When we added support for vanilla SwiftUI modifiers, we lost the ability to present one alert after another because `nil` writes to the alert bindings unconditionally dismissed the feature, even if the feature was freshly presented.
This fixes things by suppressing dismissal when the identity of a presented item has changed.
Fix #3272.
=> Allow an alert to present another alert

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md
I found some deprecated content in the `Performance.md` file and have made corrections. However, I'm concerned that this change might potentially alter the original intent of the document. I would appreciate your feedback. Thank you!
=> Fix typo and deprecated content in `Performance.md`

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Debounce.swift, Sources/ComposableArchitecture/Effects/Throttle.swift, Sources/ComposableArchitecture/Observation/IdentifiedArray+Observation.swift, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift
Many of our APIs warn that we are passing hashable identifiers across concurrency boundaries, so we should require that they're sendable.
=> Require sendable IDs in cancellation/reducers

Sources/ComposableArchitecture/Effects/Throttle.swift
Addressing some more sendability warnings.
=> Address `Effect.throttle` sendability

Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/swift-composable-architecture-benchmark/StoreSuite.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift, Tests/ComposableArchitectureTests/Internal/BaseTCATestCase.swift
Some more changes to avoid sendability warnings in effect cancellation.
=> Address effect cancellation sendability

Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift
Because printing is done on a queue, both `State` and `Action` must be sendable. While `State` is easy enough to make sendable, it might be a pain to do so in a large, modularized application. Actions are not always so easy, but are in simple cases.
Alternately, since this is a debugging affordance:
1. We could forego sendability since all we're doing is hitting it with a `Mirror` at the end of the day, and traffic the state/action along in a `nonisolated(unsafe)`.
2. We could ditch the queue...but that could affect the performance pretty negatively in some cases.
=> Address `Reducer._printChanges()` sendability

Sources/ComposableArchitecture/Observation/IdentifiedArray+Observation.swift
We can eliminate sendable warnings and improve the error handling via `MainActor.preconditionIsolated`.
=> Require main actor isolation in store collection

Sources/ComposableArchitecture/Documentation.docc/Articles/WhatIsNavigation.md
While working through the documentation, I noticed that the items in the array were missing commas, so I fixed that.
=> Fix document in WhatIsNavigation.md

Tests/ComposableArchitectureTests/ObservableTests.swift
Added failing test to document behavior with observation and identified array.
=> Added failing test to document behavior with observation/identified array

Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Tests/ComposableArchitectureTests/RuntimeWarningTests.swift
Looks like the warnings we emit when we detect `BindingReducer` is missing are only applied to view stores, and were not ported over to the newer observable store bindings.
This PR fixes that, though the main caveat is the messages can't seem to point to any good context. These bindings are derived from dynamic member lookup, which can't include source context like file/line.
=> Warn if bindable store binding action isn't processed

Examples/CaseStudies/SwiftUICaseStudies/04-Navigation-Lists-NavigateAndLoad.swift
I found the `if let` code in the `04-Navigation-Lists-NavigateAndLoad` file and made significant modifications to improve it. However, I'm concerned that these changes might unintentionally alter the original intent.
I would appreciate your feedback. Thank you!"
=> Edit `04-Navigation-Lists-NavigateAndLoad` file in SwiftUI CaseStudies

Sources/ComposableArchitecture/Documentation.docc/Articles/GettingStarted.md, Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-MultipleDestinations.tutorial, Sources/ComposableArchitecture/Reducer/Reducers/ForEachReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfCaseLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/IfLetReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/Reducer/Reducers/Scope.swift, Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift, Tests/ComposableArchitectureTests/Reducers/ForEachReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/IfCaseLetReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/IfLetReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/Reducers/StackReducerTests.swift, Tests/ComposableArchitectureTests/ScopeTests.swift
Found and fixed spots where the viewStore name was unnecessarily used in runtimeWarning sections and docs.
Since viewStore is deprecated, I think keeping it around might cause some confusion.
=> Replace deprecated `viewStore` with `store`

Sources/ComposableArchitecture/Internal/Exports.swift, Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Sources/ComposableArchitecture/Observation/IdentifiedArray+Observation.swift, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift, Sources/ComposableArchitecture/Observation/ObservableState.swift, Sources/ComposableArchitecture/Observation/ObservationStateRegistrar.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift, Sources/ComposableArchitecture/RootStore.swift, Sources/ComposableArchitecture/SharedState/References/ValueReference.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
We originally conditionally branched on Perception availability for Swift <5.9, but we removed support for Swift 5.9 awhile back and these branches should never compile.
=> Remove `#if` Perception branching

.github/workflows/ci.yml, Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.7.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/StoreDeprecations.md, Sources/ComposableArchitecture/Documentation.docc/Extensions/Store.md, Sources/ComposableArchitecture/UIKit/IfLetUIKit.swift
We can prefer `observe` and `if let store.scope` now.
=> Soft-deprecate `Store.ifLet`

Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides.md, Sources/ComposableArchitecture/Documentation.docc/Articles/MigrationGuides/MigratingTo1.15.md
This is a potential small issue that could come up with 1.15, and we've seen it brought up at least 2 or 3 times so far, so thought we could get a migration guide for it.
=> Added migration guide for 1.15

Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-01-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0005-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0003-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004.swift
This PR adds import `modules` to the NavigationStacks tutorial's source code. 
This may help with compiling the source code.
=> Add import modules on NavigationStack tutorial source code.

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/CaseStudies/SwiftUICaseStudies/03-Effects-LongLiving.swift, Examples/CaseStudies/SwiftUICaseStudies/FactClient.swift, Package.swift, Package@swift-6.0.swift, Sources/ComposableArchitecture/Effect.swift, Sources/ComposableArchitecture/Internal/NavigationID.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
Rather than use an ad hoc implementation with an `AnyHashable` under the hood that may not be concurrency safe, let's adopt the helper we added to the Concurrency Extras packages.
=> Use `AnyHashableSendable` from Concurrency Extras

Sources/ComposableArchitecture/Internal/KeyPath+Sendable.swift
Bit-casting a type to the type it already is produces a warning.
=> Fix Swift <6 warning

README.md
It looks like the Russian translation hasn't been updated since version 0.51, so I’ve bumped it to the latest 1.15. I’ll try to keep it up to date if it gets merged. Thanks!
=> Update Russian translation in README.md

Sources/ComposableArchitecture/Internal/CurrentValueRelay.swift, Tests/ComposableArchitectureTests/CurrentValueRelayTests.swift
As it's currently written, `CurrentValueRelay` seems to have several race conditions. These are infrequent enough to make them rather elusive in typical usage, but we believe that these are the root cause behind 0.X% of Ramp iOS sessions crashing.
This PR includes a test case that fails on `main`, as well as a fix that solves it, but is slow. It's probably worth you folks writing a fix yourself (without needing the lock to be recursive) to resolve the issue, but I hope that the test case helps. FWIW you should also be able to trip up TSAN when running the failing test case pre-fix; it catches a number of the ways in which the race can be triggered.
=> Fix race conditions in CurrentValueRelay

Tests/ComposableArchitectureTests/SharedTests.swift
When modifying a `@Shared` value in a delegate action, the `TestStore` shows the state change in the original action, not the delegate. 
This PR is a failing test only. In reality this would be a parent feature responding to the delegate, but the test works within a single reducer.
=> Shared state shows test change in the wrong action

Sources/ComposableArchitecture/Internal/KeyPath+Sendable.swift, Sources/ComposableArchitecture/Observation/Binding+Observation.swift, Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Sources/ComposableArchitecture/SharedState/Shared.swift, Sources/ComposableArchitecture/SwiftUI/Binding.swift
There are a few compiler bugs that prevent us from declaring sendability for key paths where it's needed.
First, doing so breaks autocomplete, which really hurts the developer experience: https://github.com/swiftlang/swift/issues/77035
Second, even though recovering autocomplete might be preferable at the cost of safety, there is no safety to begin with right now because sendable diagnostics don't propagate through dynamic member lookup: https://github.com/swiftlang/swift/issues/77105
Because of this, let's only use non-sendable key paths for now, and force cast them under the hood.
=> Avoid sendable key paths in dynamic member lookup

.github/workflows/ci.yml, Makefile, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKey.swift, Sources/ComposableArchitecture/SharedState/PersistenceKey/AppStorageKeyPathKey.swift
Observing the firehose notification from Notification Center is not only less performant, but it can cause crashes in SwiftUI if a notification is posted during a view body update, which can occur in certain situations.
Instead, we will prefer KVO unless we detect an invalid key, such as one that contains a `.` or is prefixed with an `@`.
Fixes #3311.
=> Prefer KVO for app storage observation

Sources/ComposableArchitecture/Internal/Create.swift
After landing #3447, we found another race condition — this time in `DemandBuffer`, which is marked `@unchecked Sendable` (and should indeed be thread safe) but has no synchronization around `DemandBuffer.buffer` (as well as other slightly less critical properties) in some spots.
A similar fix was actually applied to the original `CombineExt.DemandBuffer` impl back in 2021, but wasn't ported over to TCA. See https://github.com/CombineCommunity/CombineExt/pull/90.
=> Fix race in DemandBuffer

Sources/ComposableArchitecture/Internal/CurrentValueRelay.swift
Minor improvement I forgot to mention while looking at #3447
=> Avoid extra lock when getting `subscriptions` in `CurrentValueRelay.send`

Sources/ComposableArchitecture/SharedState/PersistenceKey/FileStorageKey.swift, Tests/ComposableArchitectureTests/FileStorageTests.swift
This fixes a race condition between mutating `@Shared(.fileStorage)` directly and the file system notifying it of changes on disk.
=> Fix race condition in FileStorageKey

Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift
Adding view builder annotation to `NavigiationStack. init`. This matches the functionality of the built in initializer's root view. See #3483 
Note that I'm not sure if there is a way to add a test for this exactly, but what I did to confirm was to modify `NavigationDemoView` in SwiftUICaseStudies locally (not checked in) like so: 
```
var body: some View {
NavigationStack(path: $store.scope(state: \.path, action: \.path)) {
Text("Fred")
Form {
Section { Text(template: readMe) }
...
```
=> Add `@ViewBuilder` to `NavigationStack` root view

Sources/ComposableArchitecture/SharedState/PersistenceKey.swift, Tests/ComposableArchitectureTests/SharedTests.swift
We have a custom conformance of `PersistenceKey` that called `Shared<Value>.Subscription.cancel()` on the base persistence key in its own `onCancel` closure:
```swift
struct PersistenceKeyProjection<Value: Sendable, Base: PersistenceReaderKey>: PersistenceReaderKey {
let base: Base
// ...
func subscribe(
initialValue: Value?,
didSet: @escaping @Sendable (_ newValue: Value?) -> Void
) -> Shared<Value>.Subscription {
let subscription = self.base.subscribe( /* ... */ )
return Shared.Subscription {
subscription.cancel()  // ← ⚠️
}
}
}
```
When upgrading to 1.16.0, that logic started crashing with `AppStorageKey` because `Shared<Value>.Subscription` also calls `cancel()` from its `deinit` and key-value observing does not allow that:
> [!CAUTION]
> Cannot remove an observer …
=> Fix crash when cancelling subscription for custom PersistenceKey

Tests/ComposableArchitectureTests/StoreTests.swift
This was inspired by #3497. We've known for a long time that cancelling a root effect will cancel its child effects too. We've investigate fixes for this, but sadly we do think it's just how things have to be right now. Fortunately we do have some changes coming to the library that will allow us to improve this behavior. But for the time being let's at least document this behavior in a test.
=> Add a test to document how 'task tree' cancellation  happens.

Examples/CaseStudies/SwiftUICaseStudies/03-Effects-WebSocket.swift
When websocket.receive() encounters an error, it cannot be properly thrown, resulting in an infinite loop within AsyncStream, which negatively impacts performance.
Writing this way allows the error to be handled properly, avoiding the issue mentioned earlier.
socket.receive() is a throwing function.
```swift
extension URLSessionWebSocketTask {
// ...
public func receive() async throws -> URLSessionWebSocketTask.Message
}
```
In the case of SwiftUICaseStudies: `03-Effects-WebSocket.swift`
```swift
func receive(id: ID) throws -> AsyncStream<Result<Message, any Error>> {
let socket = try self.socket(id: id)
return AsyncStream { continuation in
let task = Task {
while !Task.isCancelled {
continuation.yield(await Result { try await Message(socket.receive()) }) // 🚨throw error indefinitely
} …
```
=> Fix the infinite loop issue when WebSocket returns an error message in the example case.

Sources/ComposableArchitecture/Reducer/Reducers/StackReducer.swift
Looks like `StackElementID` [was once backed by a UUID](https://github.com/pointfreeco/swift-composable-architecture/commit/341b09bb4f5eb18a841722599c31ad6f127b3207#diff-41bfac62990a3b8f3c78d97ce4eac2d1a9f94a4a3dab24d797edb0c407d3d021R452), but later on in #1945 the implementation was simplified down to just a wrapped `Int`. This change fixes the confusing documentation accordingly.
=> Fix obsolete detail on StackElementID documentation

.github/workflows/ci.yml, Tests/ComposableArchitectureTests/Reducers/OnChangeReducerTests.swift, Tests/ComposableArchitectureTests/StorePerceptionTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
This PR makes the necessary changes to make the test suite build and pass on Xcode 16 (tested on 16.2) on at least the following destinations:
- macOS 15.2
- iPhone 16 simulator running iOS 18.2
- iPhone 15 simulator running iOS 17.5
- iPhone 14 simulator running iOS 16.4
(Unfortunately I can't seem to pass the test suite on iPhone 13 simulator running iOS 15.5, as several test cases seem to crash with `EXC_BAD_ACCESS` at `static Shared<A>.== infix(_:_:)`. 🤷‍♂️)
Code coverage on the perception checking logic is slightly improved by not skipping the test even if running on iOS 17+.
I think these changes should be enough to enable running adding `test` to `matrix.strategy` on the `xcodebuild-latest` job in `ci.yml`.
=> Fix unit tests for Xcode 16 and older iOS destinations

.github/package.xcworkspace/xcshareddata/swiftpm/Package.resolved, ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/SyncUps/SyncUps/AppFeature.swift, Examples/SyncUps/SyncUps/SyncUpsList.swift, Package.resolved, Sources/ComposableArchitecture/Reducer/Reducers/DebugReducer.swift
Not sure if we can change the package file to require at least 0.1.4 of the 0 major version and at least 1.0.4 of 1 major, otherwise this won't compile if they only update TCA.
=> Don't report unasserted shared changes in `Reducer._printChanges()`

Sources/ComposableArchitecture/Store.swift
Hello, I modified the code for the readability of the function.
Please review the changes, Thanks! 😄
Detail: Fix formatting by removing extra space before 'public'. (#Line: 335)
- origin code
```swift
public
func scope<ChildState, ChildAction>(
```
- changed code
```swift
public func scope<ChildState, ChildAction>(
```
=> Fix typos in Store.swift

.gitignore, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/01-YourFirstPresentation/02-01-YourFirstPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-02-code-0012-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/02-MultipleDestinations/02-02-MultipleDestinations.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0011.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0012.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0013.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0014.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0016.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-01-code-0017.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-03-code-0010.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/03-TestingPresentation/02-03-TestingPresentation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0000.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/MeetTheComposableArchitecture/02-Navigation/04-NavigationStacks/02-04-NavigationStacks.tutorial
Hi Brandon & Stephen! 
I've just finished doing the Meet TCA tutorial to refresh my knowledge about the framework and I've found a few details that I think deserve some adjustments:
- Fix tests using dot chaining CasePath to avoid Xcode 16 compilation error mentioned in https://github.com/pointfreeco/swift-composable-architecture/discussions/3158 
- Fix a copy/paste error mentioning syncups instead of contacts while talking about `@Shared` feature
- Add `@CasePathable` to tested Alert actions to simplify the tests and better follow best practices
- Use of `.foregroundStyle` instead of deprecated `.foregroundColor` in an example view
- Use `StackActionOf` instead of `StackAction` for shorter syntax with a tip to explain why
- add `.docc-build/` to `.gitignore` file for when we create the …
=> Meet The Composable Architecture tutorial various fixes and improvements

.gitignore, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-02-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-02-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-02-code-0008.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-02-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-03-code-0001-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/02-ListsOfSyncUps/ListsOfSyncUps-03-code-0001.swift
Hi!
Following my last PR, I'm currently reviewing the "Building Sync-ups" tutorial and so far, there is a lot of changes so I've splitted up into one PR per chapter to ease the review of them, starting with the "Lists of sync-ups" chapter here…
**Changes Made:**
- Replaced all instances of the deprecated `foregroundColor` with `foregroundStyle` in the `CardView` implementation.
=> [Building Sync-ups Tutorial] fixes in "Lists of sync-ups" chapter

Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-01-code-0009.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0001-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm-02-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/SyncUpForm.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/03-SyncUpForm/TestingSyncUpForm.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/04-PresentingSyncUpForm/TestingSyncUpFormPresentation-01-code-0013.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/04-PresentingSyncUpForm/TestingSyncUpFormPresentation.tutorial
Hi!
Following my last PR, I'm currently reviewing the "Building Sync-ups" tutorial and so far, there is a lot of changes so I've splitted up into one PR per chapter to ease the review of them, continuing with the "Sync-up form" chapter here…
**Changes Made:**
- **Update ThemePicker**: The `ThemePicker` component has been updated to utilize `foregroundStyle` instead of the deprecated `foregroundColor`.
- **Fix Typos in Documentation**: Minor grammatical and spelling errors have been corrected in the tutorial documentation for `SyncUpForm`, `TestingSyncUpForm` and `TestingSyncUpFormPresentation`.
- **Remove Duplicate TestStore Initialization**: The tutorial code has been cleaned up by removing a duplicate initialization of `TestStore` with a useless `await` keyword.
=> [Building Sync-ups Tutorial] fixes in "Sync-up form" chapter

Examples/SyncUps/SyncUps/Dependencies/SpeechRecognizer.swift
I've noticed that there is some unnecessary state in the preview implementation of the `SpeechClient` which is used in the _SyncUps_ example.
However in the _SpeechRecognition_ example, which also contains a `SpeechClient`, the `isRecording` state is used. But i'm wondering why there is an explicit `finishTask` endpoint instead of making use of cancellation.
=> SyncUps speech client preview

Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation-03-code-0001-previous.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation-03-code-0001.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation-03-code-0002.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation-03-code-0003.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation-03-code-0004.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/SyncUpDetailNavigation.tutorial, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/TestingNavigation-01-code-0005.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/TestingNavigation-01-code-0006.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/TestingNavigation-01-code-0007.swift, Sources/ComposableArchitecture/Documentation.docc/Tutorials/BuildingSyncUps/07-SyncUpDetailNavigation/TestingNavigation-01-code-0008.swift
Hi!
Following my last PR, I'm currently reviewing the "Building Sync-ups" tutorial and so far, there is a lot of changes so I've splitted up into one PR per chapter to ease the review of them, continuing with the "Navigating to sync-up detail" chapter here…
**Changes Made:**
- **CardView Update**: The `CardView` component has been updated to utilize `foregroundStyle` instead of the deprecated `foregroundColor`.
- **Refactoring for Compilation Errors**: 
- In SyncUps view encapsulate the shared collection within an `Array` in the `ForEach` loop.
- In navigation tests, encapsulate the `sharedSyncUp` within a `Shared` structure.
- Path manipulation has been updated to utilize case-based access.
- Modify `syncUps` list using `withLock`.
=> [Building Sync-ups Tutorial] fixes in "Navigating to sync-up detail" chapter

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Sources/ComposableArchitecture/RootStore.swift, Tests/ComposableArchitectureTests/StoreLifetimeTests.swift
We have wanted to do this for a long time, but our last attempt (#2643) needed to be reverted (#2648) because it meant that uncached stores (i.e. stores created using deprecated closure-based `scope`s) would accidentally cancel their effects prematurely since those kinds of stores are created, destroyed and recreated often.
However, in #2664 we separated the concept of the "root store" that powers a composition of features from a "child store" that can be derived and handed off to child features. The root store is what runs effects and holds onto cancellables, and now it is completely legitimate to tear down effects when the root store is deallocated.
=> Cancel effects when root store deallocates

Sources/ComposableArchitecture/Documentation.docc/Articles/Performance.md
I have found a bug when applying what is described in the Performance Article in the `Sharing logic in child features` section
Calling `Child().reduce` may break cancellation logic, while calling `self.reduce` makes it work perfectly
I have written a sample app to reproduce the issue, you can uncomment the code to fix the issue.
| Child().reduce  | self.reduce |
|-|-|
| ![Simulator Screenshot - iPhone 16 - 2025-03-21 at 01 40 15](https://github.com/user-attachments/assets/b588ddd5-e721-481c-849d-6135788fc4ed) | ![simulator_screenshot_4D98112C-F707-49F6-906A-0BBF833E8971](https://github.com/user-attachments/assets/84fefb28-705c-4bfa-972d-1a4c5e57032b) |
But I am not sure about the performances of `self.reduce` against `.send(.child)` tho
<details>
<summary>Full app code</summary>
```swift …
```
=> Performance Article: Sharing logic in child features issue

Sources/ComposableArchitecture/Core.swift, Sources/ComposableArchitecture/Effects/Cancellation.swift, Sources/ComposableArchitecture/Effects/Publisher.swift, Tests/ComposableArchitectureTests/StoreLifetimeTests.swift
Fix RootCore crash when released with effects outside of the MainActor
Because RootCore is a MainActor, every closure is expected to be called on MainActor, so when RootCore deinits outside of the MainActor the AnyCancellable closure is called and makes the app crash
Note: The crash also occurs on the latest release in RootStore
=> RootCore crash

Package.swift, Package@swift-6.0.swift
- [Stable swift-syntax@6.1 is released.](https://github.com/swiftlang/swift-syntax/releases/tag/601.0.0)
- https://github.com/search?q=org%3Apointfreeco+swift-syntax+601+path%3A*.swift&type=code
=> Support stable 6.1 in swift-syntax

.github/workflows/ci.yml, Examples/VoiceMemos/VoiceMemosTests/VoiceMemosTests.swift, Makefile, Tests/ComposableArchitectureTests/StoreLifetimeTests.swift
This is a draft PR to explore improvements we can make to our CI. GitHub actions has gotten noticeably flakey over time, so we should seek mitigation strategies.
=> Improve CI

.github/workflows/ci.yml, Sources/ComposableArchitecture/Core.swift, Tests/ComposableArchitectureTests/EffectRunTests.swift
The store will suppress warnings for invalid actions emitted by bindings to workaround a SwiftUI issue of bindings firing on dismissal when focussed, but only in debug builds.
We capture issues in release builds in Sentry so this can still be noisy and there doesn't seem to be any need to restrict this to just debug builds.
=> Enable binding workaround in release builds

Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift
=> Remove outdated warning text

Examples/Integration/Integration/iOS 17/ObservableSharedStateTestCase.swift, Sources/ComposableArchitecture/Store.swift, Tests/ComposableArchitectureTests/StorePerceptionTests.swift
In the current design of TCA, child stores must subscribe via the root store firehose of updates, and these subscriptions can grow over time and eventually lead to a performance issue. This branch attempts to mitigate the problem by terminating subscriptions on invalidated stores, _i.e._ after an optional store is dismissed.
Fixes #3634.
=> Invalidate child store subscriptions

Sources/ComposableArchitectureMacros/ReducerMacro.swift
Adds a Foundation import to get access to String's `capitalized`.  This fixes an error when building with SwiftSyntax 601.0.0:
```
Sources/ComposableArchitectureMacros/ReducerMacro.swift:271:85: error: value of type 'String' has no member 'capitalized'
269 |           conformances.append(
270 |             contentsOf: arguments[startIndex..<endIndex].compactMap {
271 |               $0.expression.as(MemberAccessExprSyntax.self)?.declName.baseName.text.capitalized
|                                                                                     `- error: value of type 'String' has no member 'capitalized'
272 |             }
273 |           )
```
Presumably `Foundation` was coming in transitively but that changed in 601?
=> Fix build error when using SwiftSyntax 601.0.0

Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift
Hi,
The latest release with Core refactoring broke our back port of the NavigationStack.init(path:) you provide. At first I tried to expose enough to make the same thing but it's far easier and maybe better to only expose a helper method that get the job done. What do you think ?
=> expose navigation stack helper behind SPI

Sources/ComposableArchitecture/SwiftUI/Binding.swift
Afaict the $ sign shouldn't used to match on a binding as was done in this documentation snippet.
=> Adjust documentation for binding action

Sources/ComposableArchitectureMacros/ObservableStateMacro.swift, Tests/ComposableArchitectureMacrosTests/ObservableStateMacroTests.swift
With the new release of SharingGRDB we have a few new property wrappers that can be used in TCA that do not need to be observed, so let's allow them through with no changes.
=> Ignore new property wrappers with @ObservableState.

Sources/ComposableArchitecture/Documentation.docc/Articles/StackBasedNavigation.md
I believe this was just a small typo, but I may be mistaken.
The example code in `StackBasedNavigation.md` referred to a `Counter` type, which I think was supposed to be the `CounterFeature` type created in the previous code block. 
---
The reducer `CounterFeature` was declared
```swift
@Reducer
struct CounterFeature {
// ...
}
```
and the main `Feature` was supposed to contain it in a `StackState`, to show testing stack-based navigation.
```swift
@Reducer
struct Feature {
@ObservableState
struct State: Equatable {
var path = StackState<Path.State>()
}
enum Action {
case path(StackActionOf<Path>)
}
@Reducer  
struct Path {
enum State: Equatable { case counter(Counter.State) }
enum Action { case counter(Counter.Action) }
var body: some ReducerOf<Self> {
Scope(state: \.counter, action: …
```
=> Change Counter to CounterFeature in StackBasedNavigation docs

Sources/ComposableArchitecture/Core.swift, Sources/ComposableArchitecture/Internal/NavigationID.swift, Sources/ComposableArchitecture/Reducer/Reducers/DependencyKeyWritingReducer.swift, Sources/ComposableArchitecture/Store.swift, Sources/ComposableArchitecture/TestStore.swift, Tests/ComposableArchitectureTests/Reducers/PresentationReducerTests.swift, Tests/ComposableArchitectureTests/StoreTests.swift
It's a little messy right now, but this is a proof-of-concept for isolating cancellation among root stores. I believe more work needs to be done in order for this to work with test stores.
Fixes #3658
=> Isolate cancellation in root stores.

Examples/CaseStudies/SwiftUICaseStudies/05-HigherOrderReducers-ResuableOfflineDownloads/ReusableComponents-Download.swift
This PR removes the unused (and old style) dependency from the CityMap Reducer
=> Remove the outdated unused dependency

Sources/ComposableArchitecture/Effects/Cancellation.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
=> Propagate current navigation path to cancellable publisher effects

ComposableArchitecture.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/ComposableArchitecture/Observation/NavigationStack+Observation.swift, Sources/ComposableArchitecture/Observation/Store+Observation.swift
View controllers embedded in SwiftUI views can lead to errant perception checks when constructing UIBindings, so let's disable perception checks entirely when projecting a UIBinding.
=> UIKit: Skip `UIBindable` perception checks

Sources/ComposableArchitecture/Effect.swift, Tests/ComposableArchitectureTests/EffectCancellationTests.swift
Turns out some async functions will detect cancellation and throw their own cancellation errors rather than just throwing `_Concurrency.CancellationError`. So we need to guard against those situations.
=> Better cancellation detection
